### ISSUE TITLE
Packagist badge occasionally shows "internal error"

### ISSUE THREAD

**Issue by tarampampam** [badges/shields#3684] opened 2019-07-10 13:57 UTC
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

Badge shows "internal error": ![](https://img.shields.io/packagist/v/avtocod/b2b-api-php.svg)
Packagist: https://packagist.org/packages/avtocod/b2b-api-php

:link: **Link to the badge**

`https://img.shields.io/packagist/v/avtocod/b2b-api-php.svg`

**Comment by chris48s** [comment] 2019-07-10 17:54
I'm seeing this intermittently in production - sometimes it works and sometimes it doesn't. e.g:

---

![Screenshot at 2019-07-10 18-36-23](https://user-images.githubusercontent.com/6025893/60991060-b0726700-a341-11e9-8fa6-681194af8aeb.png)

---

and I can't reproduce it locally.

I wonder if there is an intermittent issue with the upstream API?

**Comment by PyvesB** [comment] 2019-07-10 19:16
Could it be an hourly rate limit or something similar? Some of @RedSparr0w's status tooling was really helpful when tracking down issues with the Code Climate service.

**Comment by calebcartwright** [comment] 2019-07-10 19:43
I'd have thought upstream issues with the API (accessibility, rate limiting, etc.) would result in a different error message though, like `inaccessible`. The `internal error` message makes me suspect that there's probably something we've got going on our side as well, even if that's being triggered by an upstream issue.

**Comment by RedSparr0w** [comment] 2019-07-10 20:50
What happens when the response doesn't match the schema,
Does it produce this error message?

https://github.com/badges/shields/blob/a9d0f0d32342c50d3978fc32921628565ef9c6c8/services/packagist/packagist-version.service.js#L12-L26

I feel this problem is _probably_ caused by an unexpected response from packagist.
But hard to tell without seeing the error messages :sweat_smile:

**Comment by calebcartwright** [comment] 2019-07-10 20:55
Schema validation errors are `invalid response data` message. I can confirm that earlier today (when the issue was originally opened) the badge message was defintely `internal error`

**Comment by calebcartwright** [comment] 2019-07-10 20:57
I believe errors are viewable in Sentry, but I don't have access

**Comment by RedSparr0w** [comment] 2019-07-10 21:07
Thanks, looks like we may need @paulmelnikow to have a look into this,
Hopefully it's simple enough to find based on which service threw the error?
https://github.com/badges/shields/blob/9b3db0774b0444623d1ed7de9d1eca21bf9db2df/doc/production-hosting.md#L25

**Comment by paulmelnikow** [comment] 2019-07-11 03:56
There's nothing in Sentry. I don't think we log "unhandled" internal errors to sentry, though it makes sense to add that!

**Comment by paulmelnikow** [comment] 2019-07-11 04:01
One possible bug from reading the code: what happens if you call `latest([])`? I'm not sure the schema forbids an empty `versions` object.

**Comment by tarampampam** [comment] 2019-07-11 04:56
Now all looks fine!

**Comment by paulmelnikow** [comment] 2019-07-11 18:07
Suppose we could close this, and turn on logging for these errors, which would make it a bit easier to spot the actual problem next time 😉

I opened #3688.

**Closed** 2019-07-11 19:11 UTC
Labels: bug
