### ISSUE TITLE
[BUG] Github doesn't show badges (loading time too long).

### ISSUE THREAD

**Issue by mathieutu** [badges/shields#874] opened 2017-02-07 10:04 UTC
Hi, 
All my shieds.io badges aren't shown on github anymore : 
![screen shot 2017-02-07 at 10 55 40](https://cloud.githubusercontent.com/assets/11351322/22686554/ce38d43e-ed24-11e6-8308-877cfd5c5f97.png)
(the only one you can see is from another site)

In fact I've some errors during the loading of the badges : 
![screen shot 2017-02-07 at 10 59 52](https://cloud.githubusercontent.com/assets/11351322/22686594/f0b4c072-ed24-11e6-9044-beebfd13d71f.png)

And indeed, when I'm trying to directly reach a badge, the loading time is very long : 
![screen shot 2017-02-07 at 11 00 00](https://cloud.githubusercontent.com/assets/11351322/22686625/0e1fc03a-ed25-11e6-988f-445082802ca6.png)

Do you have the same problem ? Do you have any solution ?

Thanks.

**Comment by antoine-pous** [comment] 2017-02-07 11:00
Got similar issue since yesterday

**Comment by dansondergaard** [comment] 2017-02-07 11:33
I've had this issue for some time, some badges just don't show, but sometimes they pop up again, and then disappear. It's very random. However, I've noted that the problem only occurs when viewing the badges through GitHub. The requests seem to go through a GitHub server, which then times out because shields.io doesn't serve the badge fast enough:

![screen shot 2017-02-07 at 12 31 45](https://cloud.githubusercontent.com/assets/204911/22689490/838ace6c-ed31-11e6-81f6-8189c78866f1.png)

If I request the badge directly it shows up, but only after a long time (> 10s).

**Comment by erunion** [comment] 2017-02-07 12:16
Dupe of #868.

**Comment by mathieutu** [comment] 2017-02-07 12:29
Yep, thanks.
I let @espadrine close this issue if he want to, but I think this can add some information to it.

**Comment by espadrine** [comment] 2017-02-07 20:17
I'll close this as a dupe.

**Closed by espadrine** 2017-02-07 20:17 UTC
