### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#7176] opened 2021-10-19 19:48 UTC
As requested in #7129, it would be helpful to add a dark mode design to Shields.

Initially this probably can use the system light / dark setting.

In terms of process, I'd suggest creating a mockup or a draft PR, doing a quick design review, and then getting approval on the design. We can handle the technical aspects of the code afterward.

**Comment by oneamanish** [comment] 2021-11-17 06:45
see my pul req.

**Comment by tapanchudasama** [comment] 2021-12-22 11:45
This looks interesting. I'd like to pick this up.

**Comment by calebcartwright** [comment] 2021-12-22 16:03
> This looks interesting. I'd like to pick this up.

Awesome, please do! You can reach us here and/or on Discord if you have any questions or want to chat about it

**Comment by tapanchudasama** [comment] 2021-12-23 12:50
Okay, so I went thought the issues related to this topic of website design. And where do you think we should start from? Like how should i start work on this?

**Comment by paulmelnikow** [comment] 2021-12-23 19:42
Hit me up on Discord and let's find a time to chat about it! I would also suggest that we start working together on something that is focused and small (like dark mode!), and build up from there to bigger and bigger things.

**Comment by tapanchudasama** [comment] 2021-12-24 08:15
Yep, will do. How can i reach you on discord?

**Comment by chris48s** [comment] 2021-12-24 21:10
https://discord.gg/HjJCwm5

**Comment by Harsh-Shedge** [comment] 2022-07-03 09:21
Hi, Can I work on this issue?

**Comment by calebcartwright** [comment] 2022-07-03 16:33
> Hi, Can I work on this issue?

Thank you for the offer! I don't think there would be much point in trying to implement new features on top of the existing UI given the plans to overhaul it (see #7815). If you'd like to help with frontend work though, there's probably some other items discussed in that issue which may be up for grabs

**Comment by Andre601** [comment] 2022-07-20 20:28
I feel like closing this issue would only give the wrong impression. That of it being completed/done while it isn't.

It's understandable that people randomly appearing here and trying to work on this while it shouldn't is somewhat annoying, but closing the issue isn't really the best solution here due to the aforementioned reasons.

A solution could perhaps be a pinned issue (Perhaps #7815 itself?) to give a more prominent indicator that something is currently at work.

**Comment by calebcartwright** [comment] 2022-07-20 20:46
> Since this issue should not be picked up before https://github.com/badges/shields/issues/7815 is done,
could it be closed?

@PaulaBarszcz - I agree with the thrust of what @Andre601 said against closing, though I've adjusted the labels on both issues instead of pinning as that's more inline with the way we represent status/dependencies.

**Comment by PaulaBarszcz** [comment] 2022-07-20 20:54
In #7815 even the amount of comments is intimidating, thus I will search for something with more solidified criteria to pick up:)

Thank you both for your answers, and for labels adjustment. Have a great day 🍀

**Comment by calebcartwright** [comment] 2022-07-20 21:21
@PaulaBarszcz - are you looking for general opportunities to contribute to Shields, or were you specifically interested in the front end pieces? (and if either is true, that would be great! :pray: :tada:).

If it's the latter, it's indeed fair to say there's a large volume of up front analysis and then work needed before smaller, more granular pieces could be approach. However, if it's the former there's plenty of smaller, more solidified items we'd be happy to recommend!

**Comment by PaulaBarszcz** [comment] 2022-07-20 21:30
Hi @calebcartwright,
I just began my journey with open source projects and I am searching for projects to which I would be able to contribute. For now I feel that I would like to keep to small-scale tasks to gain confidence and fluency in the open source environment :)

That said, it would be great if you could recommend some tasks good for a Regular Front-End Dev starting her adventure with Open Source ☺️ 
Thanks for asking 😉

**Comment by calebcartwright** [comment] 2022-07-21 02:25
> Hi @calebcartwright, I just began my journey with open source projects and I am searching for projects to which I would be able to contribute. For now I feel that I would like to keep to small-scale tasks to gain confidence and fluency in the open source environment :)
> 
> That said, it would be great if you could recommend some tasks good for a Regular Front-End Dev starting her adventure with Open Source relaxed Thanks for asking wink

Unfortunately I think any and all of our pure front end work (React and TypeScript) is going to similarly be blocked.

If you're willing to give server-side JavaScript a try then I think we've got a few open issues that would be viable candidates. I want to be sure we don't take this particular issue off topic, but if you're interested then feel free to drop us a note in Discord (https://discord.gg/HjJCwm5) or just use an emoji reaction to this comment (let's say the Rocket emoji :rocket:) and we'll tag you on a couple such issues for consideration. No worries if not!

**Comment by chris48s** [comment] 2023-06-18 09:01
We have just launched a completely redesigned frontend https://shields.io/ which includes light/dark mode themes + toggle

**Closed by chris48s** 2023-06-18 09:01 UTC
Labels: frontend, on-hold
