### ISSUE TITLE
Github actions badge not working on private repo

### ISSUE THREAD

**Issue by danielgroen** [badges/shields#8398] opened 2022-09-14 08:02 UTC
### Are you experiencing an issue with...

My own instance of shields

### 🐞 Description

I have a private repo on github.

Also i have my own hosted shields server:
https://githubshieldsio.herokuapp.com

This is all set with a PAT token so it should read all the info from the repo.

Now the badge of the workflow can't find the repo.
When i set the repo to public, then the badge does work!

### 🔗 Link to the badge

Example of a badge reading the same repo (but does work)
https://githubshieldsio.herokuapp.com/github/package-json/v/danielgroen/affiliate-program

The badge that doesn't work.
https://githubshieldsio.herokuapp.com/github/workflow/status/danielgroen/affiliate-program/prod

**Comment by LitoMore** [comment] 2022-09-19 07:37
See https://github.com/badges/shields/discussions/5676.

**Comment by chris48s** [comment] 2022-09-20 20:17
Unlike most of our github badges which call an API endpoint, this one is basically a scraper or wrapper for github's own badge that allows you to apply the shields styles/icons/etc to it.
You will find that if you call https://github.com/danielgroen/affiliate-program/workflows/prod/badge.svg when you're logged in to github, it works. If you call it when you're not logged in, its a 404. With all our other badges that use the GitHub API, providing a token allows us access to private resources. This badge is an outlier in this respect. If it is possible to use a token in the request (I've not checked), we'd happily take a PR for this but at the moment this specific badge won't work for private repos.

**Comment by calebcartwright** [comment] 2022-09-25 20:30
Going to close this as a duplicate of #4681 in favor of keeping things consolidated under #4587

**Closed by calebcartwright** 2022-09-25 20:30 UTC
