### ISSUE TITLE
Lines of code just reports invalid data in the badge

### ISSUE THREAD

**Issue by ascopes** [badges/shields#9569] opened 2023-09-14 06:52 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Seems the lines of code badge just gives an error. The example suggests GitHub is valid.

### 🔗 Link to the badge

https://img.shields.io/tokei/lines/github/ascopes/java-compiler-testing

![](https://img.shields.io/tokei/lines/github/ascopes/java-compiler-testing)

![Screenshot_2023-09-14-07-49-58-84_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/badges/shields/assets/73482956/57b11e3d-1199-4e7c-bccc-c142794cdef1)

**Comment by calebcartwright** [comment] 2023-09-14 17:49
Closing as a duplicate of #9389 and #7569

Those issues have links to the upstream issues in the Tokei service (which is where the underlying issue resides and needs to be resolved)

**Closed by calebcartwright** 2023-09-14 17:49 UTC
Labels: question
