### ISSUE TITLE
Shields.io shows that my site is turned off. However, it is not.

### ISSUE THREAD

**Issue by dorokhin** [badges/shields#2812] opened 2019-01-19 06:44 UTC
Are you experiencing an issue with...

- [* ] [shields.io](https://shields.io/#/)

:beetle: **Description**

Shilds.io shows that my site is turned off. However, it is not.
This happened after I updated the certificates, and the SSL settings of the web server

www.ssllabs.com shows that my server has an A + rating

:link:  
[<img src="https://img.shields.io/website-up-down-green-red/https/dorokhin.moscow.svg?label=dorokhin.moscow">](https://dorokhin.moscow/)

https://img.shields.io/website-up-down-green-red/https/dorokhin.moscow.svg?label=dorokhin.moscow

[ssllabs report](https://www.ssllabs.com/ssltest/analyze.html?d=dorokhin.moscow)

** Screenshots **
[Screenshot 1](https://pasteboard.co/HX813xp.png)
[Screenshot 1](https://pasteboard.co/HX80jsp.png)

:bulb: **Possible Solution**

Update your ssl client library.

**Comment by chris48s** [comment] 2019-01-19 17:34
Tried this locally and its throwing:

```
{
Error: write EPROTO 139639970006848:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3
alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802: at
WriteWrap.afterWrite [as oncomplete] (net.js:868:14) errno: 'EPROTO', code: 'EPROTO', syscall: 'write'
}
```

Can make a `HEAD` request OK with curl:

```
$ curl -I --head "https://dorokhin.moscow/"
HTTP/1.1 200 OK
```

**Comment by paulmelnikow** [comment] 2019-01-19 19:40
I can't reproduce that locally in Node 10, though I can in Node 9 and Node 8. I don't have access to upgrade Node on the servers, but it seems like that's what we'll need to do.

**Comment by paulmelnikow** [comment] 2019-01-19 19:44
We could also try setting `secureProtocol` to the Node 10 value to see if it fixes this. There's some differences in [the docs in Node 9](https://nodejs.org/docs/latest-v9.x/api/tls.html) and the subsequent versions.

**Comment by chris48s** [comment] 2019-01-19 21:59
Suspect its probably this then: https://github.com/nodejs/node/issues/3692 Might be some settings we can fiddle with if you trawl that thread, but node 10 has a more recent version of openssl which fixes this.

**Comment by paulmelnikow** [comment] 2019-01-20 14:04
The ssl test report shows a handful of client failures:

This is from [their documentation](https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices):

> In order to support older clients, you may need to continue to support TLS v1.0 and TLS v1.1 for now. However, you should plan to retire TLS v1.0 in the near future. For example, the PCI DSS standard will require all sites that accept credit card payments to remove support for TLS v1.0 by June 2018.

<img width="972" alt="screen shot 2019-01-20 at 8 56 35 am" src="https://user-images.githubusercontent.com/1487036/51440142-be4c0700-1c91-11e9-9677-9d47382dd7ca.png">

<img width="913" alt="screen shot 2019-01-20 at 8 56 45 am" src="https://user-images.githubusercontent.com/1487036/51440140-bb511680-1c91-11e9-9cd0-331dfc105905.png">

Sort of tangential: it would be cool to have a TLS version support badge.

**Comment by paulmelnikow** [comment] 2019-01-21 18:35
So… it's failing for some other reason. I'm guessing it's related to the ciphers.

**Comment by ParveenBhadooOfficial** [comment] 2019-04-30 03:15
How to fix:

![Website](https://img.shields.io/website/https/inbox.bhadoomail.com.svg?down_message=inbox.bhadoomail.com%20is%20Offline&style=for-the-badge&up_message=inbox.bhadoomail.com%20is%20Online)

Site .htaccess is https://github.com/BhadooMail/BhadooMail/blob/master/.htaccess

at AWS with SSL Rating A at ssllabs.com

**Comment by mfominov** [comment] 2019-09-02 09:47
or u can add 
`require("tls").DEFAULT_ECDH_CURVE = "auto"`
to server.js

**Comment by ParveenBhadooOfficial** [comment] 2019-09-04 11:12
Check this https://site-status-php.herokuapp.com/?q=amazon.in or https://site-status-php.herokuapp.com/?q=amazon.com all shows down.

while https://site-status-php.herokuapp.com/?q=aws.amazon.com shows fine.

**Comment by derSoerrn95** [comment] 2019-10-13 18:00
@dorokhin: how did u solve your problem?

**Comment by mfominov** [comment] 2019-10-14 14:57
> @dorokhin: how did u solve your problem?

try my comment with server.js

**Comment by derSoerrn95** [comment] 2019-10-18 11:02
it works with self-hosted version. but the shield.io version always shows down.

**Comment by paulmelnikow** [comment] 2020-04-29 20:10
The production servers are now running Node 10.20.1 so this should be resolved.

Can anyone confirm?

**Comment by paulmelnikow** [comment] 2020-04-30 01:04
I can't confirm this is fixed but I'm going to close it. If this isn't fixed, feel free to comment here and we'll reopen.

**Closed by paulmelnikow** 2020-04-30 01:04 UTC
Labels: bug, service-badge

**Comment by derSoerrn95** [comment] 2020-05-01 14:24
nice, it works for my page now :)

**Comment by dorokhin** [comment] 2020-05-01 14:44
> I can't confirm this is fixed but I'm going to close it. If this isn't fixed, feel free to comment here and we'll reopen.

it works!

**Comment by ParveenBhadooOfficial** [comment] 2020-05-08 11:14
Not working for Cloud flare Site

https://site-status.hashapp.ga/?q=big.driveindex.ga

**Comment by paulmelnikow** [comment] 2020-05-08 16:10
Hi! Could you open a new issue, please?
