### ISSUE TITLE
Badge error: "social: unparseable json response" (Twitter)

### ISSUE THREAD

**Issue by caendesilva** [badges/shields#8838] opened 2023-01-22 18:46 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

Any Twitter follow shield badge returns `social: unparseable json response`

![img shields io_twitter_follow_twitter](https://user-images.githubusercontent.com/95144705/213934077-0abd149e-4b82-4f93-8e65-505fca24b8f2.png)

### 🔗 Link to the badge

https://img.shields.io/twitter/follow/twitter

**Comment by calebcartwright** [comment] 2023-01-22 19:03
Thanks but going to close as a duplicate of #8837

**Closed by calebcartwright** 2023-01-22 19:03 UTC
Labels: question

**Comment by caendesilva** [comment] 2023-01-22 20:38
> Thanks but going to close as a duplicate of #8837

Ah cool, no worries! I searched for the error message to find duplicates, didn't think to search for issues regarding Twitter.
