### ISSUE TITLE
Github Clone Count Badge

### ISSUE THREAD

**Issue by MShawon** [badges/shields#6136] opened 2021-02-02 19:05 UTC
:clipboard: **Description**
A GitHub clone count badge currently shows only 14 days count but I believe this can be extended to show all clone counts.

:link: **Data**
Which service is this badge for - GitHub
 What sort of information should this badge show? - Clone count
What sort of information should this badge show? -  
![image](https://user-images.githubusercontent.com/65315049/106647864-ad8d3600-65b9-11eb-8fe6-91cd6a1e6261.png)

:microphone: **Motivation**
- Is there a public API? Yes
- - Does the API requires an API key? Github personal access token
- - Link to the API documentation. https://docs.github.com/en/rest/reference/repos#get-repository-clones

I have already implemented this in my repository. But to work, we need to use GitHub action. This action will scrape GitHub API to find clone statistics and will upload the returned JSON output in the repository. Say this action will run every 8 hours or once a day would be enough also.
Now **shields.io** dynamic badge can read count from this JSON. 

Just take a look at my implementation https://github.com/MShawon/github-clone-count-badge

Right now it can only show 14 days count but I think with some shell coding we can make it store all clone statistics.

**Comment by calebcartwright** [comment] 2021-02-02 19:17
hi @MShawon :wave: thanks for reaching out with your suggestion and results!

I am going to have to close this though, as it's a duplicate of several previous issues and isn't something we can support for the Shields.io service due to the permission/authorization requirements (duplicate of #4637 & #880).

Our guidance to folks interested in using Shields.io to get a clone count badge is to leverage our [Endpoint badge](https://shields.io/endpoint) which can utilize your own token that has push rights.

**Closed by calebcartwright** 2021-02-02 19:17 UTC
Labels: service-badge

**Comment by andry81** [comment] 2021-11-11 01:39
I have an upgraded version of @MShawon implementation:

https://github.com/andry81/github-clone-count-badge
