### ISSUE TITLE
PowerShell Gallery support

### ISSUE THREAD

**Issue by tylerl0706** [badges/shields#1030] opened 2017-07-09 23:01 UTC
Hi there,

Big fan of Shields! I was wondering how we can get some support for the PowerShell Gallery - similar to that of the NuGet Gallery.

https://www.powershellgallery.com

an example package:
https://www.powershellgallery.com/packages/AzureRM.profile/3.1.0

just a typical:

PowerShell Gallery | version
![perfect](https://img.shields.io/badge/PowerShell%20Gallery-v3.1.0-blue.svg)

Let me know if there's anything I can do to help.

**Comment by Daniel15** [comment] 2017-07-10 01:02
Closing as duplicate of #1013. This has already been implemented, I think it's just waiting to be deployed to the live server.

**Closed by Daniel15** 2017-07-10 01:02 UTC
