### ISSUE TITLE
Feature request: use img link instead of base64 img...

### ISSUE THREAD

**Issue by sayantan300** [badges/shields#6153] opened 2021-02-05 16:35 UTC
:clipboard: **Description**
The usage of base64 image isn't very popular and isn't very reliable. Instead the shields server should download the image temporarily from that link and convert it to base64 if needed.
If shields has any problem with downloading img and changing into base64, I'm here to help.

**Comment by sayantan300** [comment] 2021-02-05 16:37
Moreover, encoding base64 image in the link makes the link very very BIG. so using image link will surely decrease the amount of data we send to the server (I mean the query or the params...)

**Comment by calebcartwright** [comment] 2021-02-05 16:55
Thanks for reaching out with your suggestion! I am going to have to close this though, as it's a topic that's been discussed at length both here in the GH repo and on Discord, and this is not a feature request we're willing/able to accept.

Duplicate of a few issues, including #760 and #2186

**Closed by calebcartwright** 2021-02-05 16:55 UTC
