### ISSUE TITLE
Badges look like malarkey. (padding, spacing, font size, rendering, etc. are poop-like)

### ISSUE THREAD

**Issue by mralexgray** [badges/shields#797] opened 2016-09-23 16:19 UTC
![crap](https://cloud.githubusercontent.com/assets/262517/18793237/cb6f7ce8-8187-11e6-96ee-cef76d1e70d3.png)

Top is actual, observed... bottom is what is supposedly going to be delivered...

This is using Chrome, on a Mac, with all standard font settings.  This is obviously unacceptable.  Any solutions?

**Comment by RedSparr0w** [comment] 2016-09-23 22:21
Perhaps you should change the title, being rude wont get you anywhere.

Maybe try something a little more constructive such as "Badges have no padding | words overlapping" or something that describes the problem without needing much more context.

**Comment by mralexgray** [comment] 2016-09-24 03:37
ok, so now that sensibilities being offended has been handled.. maybe the 800-pound gorilla canbe addressed.  i just assumed this project was dead... with 142 unresolved issues...

there are plenty of other issues related to this...  how best can i help?
 
- amass, and link this issue with the other, possibly more politely phrased issues that concern the same major problems?

- further clarify and prove that this module's functionality is broken?

- delve into and fork source code that likely would never be merged?

i'll do any of these.. but the latter would require a bit of encouragement / some kind of acknowledgement that this is a problem that needs solving...

**Comment by mralexgray** [comment] 2016-09-24 03:52
https://github.com/badges/shields/issues/746
https://github.com/travis-ci/travis-ci/issues/630

**Comment by RedSparr0w** [comment] 2016-09-24 05:22
Maybe we could start by making a table of browsers/OS where this problem occurs?
just so whoever has time to look into fixing the issue knows where to start as all of them look fine for me on windows 10 (as you can see below)

### example table:
_Screenshot of http://shields.io/#styles_

Operating System | Browser | Browser Version | [Screenshot](http://shields.io/#styles) | Status
:--: | :--: | :--: | --- | ---
Windows 10 | Chrome | 53 | ![](https://i.imgur.com/16c85qq.png) | Working As Expected
Windows 10 | Firefox | 47 | ![](https://i.imgur.com/maVyz34.png) | Working As Expected
Windows 10 | Edge | 25 | ![](https://i.imgur.com/3SpzXnu.png) | Working As Expected
Windows 10 | Internet Explorer | 11 | ![](https://i.imgur.com/W89evMI.png) | Working As Expected

_although the project may be dead for the moment as nothing seems to have changed in a long time (maybe lack of administrators)_

**Comment by aburgd** [comment] 2016-09-24 14:12
I thought I was the only one having such an issue, after scouring google for answers and turning up nothing. I borrowed the table @RedSparr0w thought up and took some notes of of my own, in Chrome, Opera, and Firefox.
Hope this can be of some use.

| Operating System | Browser | Browser Version | Screenshot | Status |
|------------------|---------|-----------------|------------|--------|
| Windows 10 | Chrome | 53.0.2785.116 | ![chrome](https://cloud.githubusercontent.com/assets/6305821/18808979/5f5af834-8236-11e6-8efc-76a060b7f220.png) | Not Working Correctly|
| Windows 10 | Opera | 40.0.2308.62 | ![opera](https://cloud.githubusercontent.com/assets/6305821/18808984/7c74bb4e-8236-11e6-96c7-14fcb8daf70f.png) | Working as Expected |
| Windows 10 | Firefox | 48.0.1 | ![firefox](https://cloud.githubusercontent.com/assets/6305821/18808989/99ff8a18-8236-11e6-9ab4-7f933a1a4694.png) | Working as Expected |

**Comment by RedSparr0w** [comment] 2016-09-24 21:33
Strange im using the same OS + Browser version as you, but all looks normal to me.

Does it look the same if you view the direct svg via url vs `<img src="..."/>`?

**Comment by aburgd** [comment] 2016-09-24 21:45
Same results, unfortunately. I thought it could have been a result of uBlock Origin and/or Privacy Badger but that wasn't the case either.

**Comment by RedSparr0w** [comment] 2016-09-25 04:05
how about in private browsing with no extensions running?

**Comment by aburgd** [comment] 2016-09-25 05:24
That was what I had done.

**Comment by mralexgray** [comment] 2016-09-25 18:08
This is very helpful. Obviously, this is a Chrome issue....

|   OS  | Browser |           Version          | Screenshot | Status |
|:-----:|:-------:|:--------------------------:|:----------:|:------:|
| MacOS | Chrome  | 54.0.2840.34 beta (64-bit) | ![chrome](https://cloud.githubusercontent.com/assets/262517/18817182/789cf976-8328-11e6-9ecb-32dbf50b4a1a.png) | Stinks |
| MacOS | Firefox | 45.0a2 (2016-01-08)        | ![firefox](https://cloud.githubusercontent.com/assets/262517/18817186/93d4e0c8-8328-11e6-9c6b-d65405176ab7.png) | OK!    |
| MacOS | Safari  | 10.0 (11602.1.50.0.10)     | ![chrome](https://cloud.githubusercontent.com/assets/262517/18817181/789ab18e-8328-11e6-8eae-3ab9e675367e.png) | OK!    |


PS:  @aburgd...  how did you "borrow" @RedSparr0w 's markup?  (I just had to write my own :-( )

**Comment by RedSparr0w** [comment] 2016-09-25 23:38
Does seem to be chrome that is the problem for both of you but @un1versal also seems to be having [the same problem with Windows 7 - Firefox](https://github.com/badges/shields/issues/746#issuecomment-249353794)

**Comment by un1versal** [comment] 2016-09-26 08:40
> how about incognito browsing with no extensions running?

its not about any other extensions.

> Does seem to be chrome that is the problem for both of you but @un1versal also seems to be having the same problem with Windows 7 - Firefox

I dont seem to be having same problem. It _is_ same problem, except different browser and OS as you noted FF + Win 7 issue (must be that OS + browser combo)

Win 7 + FF = issue
Win 7 + IE = OK
Linux Ubuntu + FF = OK

**Comment by aburgd** [comment] 2016-10-13 00:39
Okay so, since my commenting on this issue, I got another one of my computers available to me. Updated Windows, Chrome, yadda yadda - the short of it is, the badges don't look awful on it. Latest Chrome, latest public Windows 1607 - beautiful.

![](http://puu.sh/rH34a/2f7d4d4280.png)

**Comment by aburgd** [comment] 2016-10-13 11:34
ah alright, understood.

**Comment by paulmelnikow** [comment] 2017-04-17 22:49
I joined the project a few weeks ago and have been steadily merging PRs. Thaddée has been deploying the updates.

Would love to get this problem solved. I appreciate the investigation which has begun in this thread, though it does seem to be a duplicate of #746.

**Closed by paulmelnikow** 2017-04-17 22:49 UTC
