### ISSUE TITLE
Site now working as intended.

### ISSUE THREAD

**Issue by ParveenBhadooOfficial** [badges/shields#3161] opened 2019-03-05 05:28 UTC
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

react-dom.production.min.js:198 TypeError: Cannot read property 'replace' of undefined
    at o (make-badge-url.js:53)
    at Array.map (<anonymous>)
    at staticBadgeUrl (make-badge-url.js:65)
    at a.r.renderExample (badge-examples.js:42)
    at badge-examples.js:87
    at Array.map (<anonymous>)
    at a.r.render (badge-examples.js:87)
    at Oi (react-dom.production.min.js:173)
    at Ri (react-dom.production.min.js:172)
    at Mi (react-dom.production.min.js:180)
da @ react-dom.production.min.js:198
make-badge-url.js:53 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at o (make-badge-url.js:53)
    at Array.map (<anonymous>)
    at staticBadgeUrl (make-badge-url.js:65)
    at a.r.renderExample (badge-examples.js:42)
    at badge-examples.js:87
    at Array.map (<anonymous>)
    at a.r.render (badge-examples.js:87)
    at Oi (react-dom.production.min.js:173)
    at Ri (react-dom.production.min.js:172)
    at Mi (react-dom.production.min.js:180)

:link: **Link to the badge**

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment] 2019-03-05 05:32
Hi @ParveenBhadooOfficial, can you provide a little more info? The badge template for bugs includes a few sections where different data points can be shared that really helps in debugging issues. It would be great if you could fill some of those in!

**Comment by chris48s** [comment] 2019-03-05 21:00
Could you let us know what you were trying to do at the time you hit this error and what browser/OS you're using. Cheers

**Comment by ParveenBhadooOfficial** [comment] 2019-03-06 06:50
when i open https://shields.io/ and enter https://github.com/ParveenBhadooOfficial/hashhackers.com it shows blank page and below code in inspect element

loader.js:229 Network quality values are overridden using a holdback experiment, and so may be inaccurate
enqueue @ loader.js:229
2react-dom.production.min.js:198 TypeError: Cannot read property 'replace' of undefined
    at o (make-badge-url.js:53)
    at Array.map (<anonymous>)
    at staticBadgeUrl (make-badge-url.js:65)
    at a.r.renderExample (badge-examples.js:42)
    at badge-examples.js:87
    at Array.map (<anonymous>)
    at a.r.render (badge-examples.js:87)
    at Oi (react-dom.production.min.js:173)
    at Ri (react-dom.production.min.js:172)
    at Mi (react-dom.production.min.js:180)
da @ react-dom.production.min.js:198
make-badge-url.js:53 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at o (make-badge-url.js:53)
    at Array.map (<anonymous>)
    at staticBadgeUrl (make-badge-url.js:65)
    at a.r.renderExample (badge-examples.js:42)
    at badge-examples.js:87
    at Array.map (<anonymous>)
    at a.r.render (badge-examples.js:87)
    at Oi (react-dom.production.min.js:173)
    at Ri (react-dom.production.min.js:172)
    at Mi (react-dom.production.min.js:180)

**Comment by calebcartwright** [comment] 2019-03-06 16:16
Are you trying to use the suggest badges feature?

**Comment by chris48s** [comment] 2019-03-06 18:59
Yes it sounds like this is a duplicate of #3033. Lets track it there - thanks for reporting

**Closed by chris48s** 2019-03-06 18:59 UTC
Labels: frontend
