### ISSUE TITLE
504 Gateway Timeout on badges inside GitHub README

### ISSUE THREAD

**Issue by akosthekiss** [badges/shields#4878] opened 2020-04-08 08:59 UTC
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

We have some projects where we have started using shields.io badges only recently. However, it seems that when the READMEs of the projects are rendered on GitHub, the badges don't show up. (Yesterday, it was roughly 50% of the badges not showing, today they don't show, like, at all.)

Network monitor shows GET requests to camo.githubusercontent.com lasting 4100+ ms, ending in 504 Gateway Timeout (Error Fetching Resource).

A private GitLab instance is also hosting the repos, there the README is rendered with all badges visible. In that case, however, network monitor shows requests going directly to img.shields.io. But the requests take 17 secs each (or more).

The projects are:
- https://github.com/renatahodovan/fuzzinator
- https://github.com/renatahodovan/grammarinator

**Comment by paulmelnikow** [comment] 2020-04-08 14:23
Hi, thanks for posting. We deployed an experimental branch (#4756) last night to a canary server and it seems like that may be the cause of this issue. Rolling it back now and hoping it stabilizes things.

We are actively working to upgrade our hosting environment to replace it with something more modern, scalable, and reliable, and which removes our administration and deployment bottleneck. One of the remaining big pieces is being completed now #4874. I don't have a timeline to report on this, but am hoping it can happen soon.

**Comment by jrwrigh** [comment] 2020-04-08 14:27
Note that this has been going on longer than just last night. See https://github.com/latex-lsp/texlab/issues/195# and https://github.com/vmg/redcarpet/issues/688

**Comment by calebcartwright** [comment] 2020-04-08 15:49
One thing I've noticed is a strong correlation between OVH (our hosting provider) maintenance/incidents and the recent windows of delayed badge responsiveness.

It could certainly be coincidental, but we've had these responsiveness issues intermittently lately and there always seems to be corresponding OVH issues during/preceeding those same intervals. 

https://twitter.com/ovh_status?
https://github.com/badges/shields/blob/master/doc/production-hosting.md#badge-servers

**Comment by akosthekiss** [comment] 2020-04-08 21:28
I'm not sure whether it's the rollback or the hosting provider, but now the badges seem to show up "instantly" (40-600 ms). Thanks for the service!

**Comment by paulmelnikow** [comment] 2020-04-09 02:54
I highly suspect @calebcartwright is right that this one was the hosting provider.

**Comment by VladimirMikulic** [comment] 2020-04-15 14:02
This happens on [my project](https://github.com/VladimirMikulic/parcel-plugin-custom-dist-structure) as well every single time.

**Comment by paulmelnikow** [comment] 2020-04-15 15:21
Really sorry about the downtime today. OVH is having some issues which I think are affecting us. I've got a draft of a new hosting proposal which should fix this and also eliminate the bottlenecks (on Thaddée for handling the servers, and on me for deploying). Please bear with us!

**Comment by VladimirMikulic** [comment] 2020-04-15 16:26
@paulmelnikow I appreciate that very much. Thank you :+1:

**Comment by sblantipodi** [comment] 2020-04-20 18:30
same problem here, how to see a solution soon.
thanks for your work guys

**Comment by paulmelnikow** [comment] 2020-04-20 19:14
I'll have this proposal posted in the next day or two.

**Comment by julienw** [comment] 2020-04-22 11:40
I'm glad I'm not the only one :-)
But I'm a bit puzzled: requesting the badge directly works perfectly well, while requesting the same badge through github's camo URL times out every time. Could it be a problem with the hosting provider OVH actively filtering out requests coming from github, possibly because a lot of requests are coming from the same IP (or set of IPs)? Like an automatic DoS protection?

**Comment by julienw** [comment] 2020-04-22 12:26
I see problems for badges coming from other sources too, so this might be a transient problem with github.

**Comment by paulmelnikow** [comment] 2020-04-22 17:53
> But I'm a bit puzzled: requesting the badge directly works perfectly well, while requesting the same badge through github's camo URL times out every time. Could it be a problem with the hosting provider OVH actively filtering out requests coming from github, possibly because a lot of requests are coming from the same IP (or set of IPs)? Like an automatic DoS protection?

It's more likely that GitHub Camo's four-second request timeout is what's causing the problem.

The hosting proposal is up at #4929 and hopefully we'll be able to move forward with this soon!

**Comment by regevbr** [comment] 2020-04-23 08:42
I experience the same issue at https://github.com/PruvoNet/node-upgrade-checker/blob/master/README.md
The failed badges and the number of them are random

**Comment by fishcharlie** [comment] 2020-04-23 16:11
I know this is specific to GitHub, but it looks like there are problems on https://shields.io as well. I'm assuming it's the same underlying problem, but just wanted to make sure it was brought up as well.

<img width="1572" alt="image" src="https://user-images.githubusercontent.com/860375/80122369-ae813980-854a-11ea-8b21-0595d4a431d0.png">

**Comment by paulmelnikow** [comment] 2020-04-23 16:46
Yikes! We've got an active proposal to address this. I wonder if we can wait for that discussion to resolve or if we need some interim action.

**Comment by nekokatt** [comment] 2020-04-24 09:36
Can repro on GitLab too...

![image](https://user-images.githubusercontent.com/52883826/80198046-7267da80-8617-11ea-8c2c-a289253dda3b.png)

All of the ones lacking a preview are ones provided by shields.io

**Comment by LGouellec** [comment] 2020-04-24 14:20
Same issue with my repo https://github.com/LGouellec/kafka-streams-dotnet.

**Comment by fishcharlie** [comment] 2020-04-24 15:39
> Same issue with my repo https://github.com/LGouellec/kafka-streams-dotnet.

@LGouellec Please consider using the 👍 reaction instead of commenting information that has already been posted. It effects every usage of Shields, every repo. If you have new relevant information, commenting is the best method. Otherwise please be respectful to subscribers of this thread to the thread and use the reaction feature.

**Comment by paulmelnikow** [comment] 2020-04-24 18:34
I've set up a test server on Heroku at https://img-test.shields.io/badge/build-passing-brightgreen and sent a note to @espadrine asking his consent to move all the traffic over there, as an experiment.

**Comment by nekokatt** [comment] 2020-04-24 19:23
For what it is worth, we have observed intermittent 504s for around a month and a half now. They seem to have gone away at some point and come back again more recently, but it doesn't appear to be a new issue that we are observing.

This is from GitLab specifically though; I'm not sure what else could interfere with that. Not sure if that is useful context at all?

**Comment by paulmelnikow** [comment] 2020-04-27 18:08
The ops team has moved forward with an experiment to test hosting Shields on Heroku, which has been live on img.shields.io for about 14 hours. Overall it's working pretty well. We had a minor setback on the Discord badges (#4957) but have shimmed it for now. Please open an issue if you're seeing any new issues with badges, and follow https://github.com/badges/shields/issues/4929#issuecomment-620140625 if you'd like more information about the ops experiment. Let's keep this open for the duration.

**Comment by calebcartwright** [comment] 2020-05-02 04:03
I'm going to close this out given the success of the Heroku experiment and [decision to go forward](https://github.com/badges/shields/issues/4929#issuecomment-622664641) as the new runtime environment has resolved the timeout/latency issues.

**Closed by calebcartwright** 2020-05-02 04:03 UTC
Labels: operations
