### ISSUE TITLE
AppStore: Country param

### ISSUE THREAD

**Issue by m-ruhl** [badges/shields#4296] opened 2019-11-04 12:28 UTC
Some apps are only available in certain countries..
With the current implementation there is no way to get the badge for a restricted app.

It would work like this: `https://itunes.apple.com/${country}/lookup?id=${bundleId}`

**Comment by calebcartwright** [comment] 2019-11-04 15:36
Can you provide an example app for reference? IIUC, your ask is that we include a new param for our iTunes badge to support explicitly specifying the target country

**Comment by chris48s** [comment] 2019-11-04 19:40
Example app:
https://itunes.apple.com/lookup?id=737651307
https://itunes.apple.com/cn/lookup?id=737651307

I'm going to close this as a dupe of #1503 but feel free to pick up the conversation there. The approach suggested there of adding an optional param for country would be the best way to implement this. It shouldn't be a big  job to add this if someone is interested in picking it up.

**Closed by chris48s** 2019-11-04 19:40 UTC
