### ISSUE TITLE
Service not working

### ISSUE THREAD

**Issue by lauris** [badges/shields#506] opened 2015-08-11 19:19 UTC
Hi,

Just checked [shields.io](http://shields.io/) and most of the svg files are not loading, for example, [https://img.shields.io/github/stars/badges/shields.svg?style=social](https://img.shields.io/github/stars/badges/shields.svg?style=social). 

![screen shot 2015-08-11 at 22 20 27](https://cloud.githubusercontent.com/assets/625264/9207584/423db946-4077-11e5-9bb8-d9423cdaa95e.png)

Is this a temporary error or is this project no longer maintained?

**Comment by espadrine** [comment] 2015-08-14 20:32
Thanks for reporting!

It seems up now. We are planning on switching servers.

Closing as a duplicate of this issue: https://github.com/badges/shields/issues/481

**Closed by espadrine** 2015-08-14 20:32 UTC
