### ISSUE TITLE
PyPI badges often don't display

### ISSUE THREAD

**Issue by shaypal5** [badges/shields#1653] opened 2018-04-18 11:24 UTC
Hey!

This a great service which I use for several of my packages.

However, in the last few the PyPI badges (for package version and supported Python versions) on my repos / PyPI packages pages often won't display. Sometimes a hard refresh helps, but usually it does not. The badges will come back if I look later in the day, but then they might disappear again.

I use the exact same method all the major repos use; and usually, when I can't see my PyPI badges I can't see theirs as well. Also, note that this is not the case with travis or codecove badges.

I'd love to understand how this can be solved. Also, if this is the wrong repo to open this issue in then I apologise, and would appreciate you pointing me in the right direction.

Cheers,
Shay

Here's a screenshot:
![image](https://user-images.githubusercontent.com/917954/38929149-1256728e-4314-11e8-8fed-4127668ba305.png)

**Comment by chris48s** [comment] 2018-04-18 19:48
Suspect this is a duplicate of https://github.com/badges/shields/issues/1568

The other possibility is that if you've only started seeing this in the last few days and it only happens on the PyPI badges, it might be related to PyPI's recent [migration to warehouse](https://packaging.python.org/guides/migrating-to-pypi-org/).

Suspect it is https://github.com/badges/shields/issues/1568 though

**Comment by RedSparr0w** [comment] 2018-04-18 22:31
I think @chris48s is correct as the badge is not loading at all rather than displaying an error message.
But going to leave this open for now incase this is related to the [migration to warehouse](https://packaging.python.org/guides/migrating-to-pypi-org/).

Will keep track of the PyPI badges [here](http://shields.redsparr0w.com/1653/) for the next few days,
Will close if results look like this is a duplicate of #1568,
Otherwise this should hopefully not be a problem when #1648 goes live.

**Comment by RedSparr0w** [comment] 2018-04-23 21:27
No worries, Looks like it is the same problem as #1568 _(99.97% correct responses)_ so going to close for now.
Hopefully we can get it sorted out soon.

**Closed by RedSparr0w** 2018-04-23 21:27 UTC
