### ISSUE TITLE
Github Action status badge can't find my workflow

### ISSUE THREAD

**Issue by exoRift** [badges/shields#8309] opened 2022-08-12 18:18 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The native workflow badge seems to be working fine

![badge](https://github.com/exoRift/react-fluent-mobile/actions/workflows/quality_assurance.yml/badge.svg?branch=master)

But shield.io's doesn't seem to be

(quality_assurance.yml)
![badge](https://img.shields.io/github/workflow/status/exoRift/react-fluent-mobile/quality_assurance.yml/master)
(quality_assurance)
![badge](https://img.shields.io/github/workflow/status/exoRift/react-fluent-mobile/quality_assurance/master)

### 🔗 Link to the badge

https://img.shields.io/github/workflow/status/exoRift/react-fluent-mobile/quality_assurance.yml/master

https://img.shields.io/github/workflow/status/exoRift/react-fluent-mobile/quality_assurance/master

**Comment by calebcartwright** [comment] 2022-08-13 01:48
Thanks but I'm going to close as a duplicate of #8146

**Closed by calebcartwright** 2022-08-13 01:48 UTC
Labels: question

**Comment by chris48s** [comment] 2022-08-14 14:03
I think the correct URL for this would be

https://img.shields.io/github/workflow/status/exoRift/react-fluent-mobile/Quality%20Assurance/master

?

**Comment by calebcartwright** [comment] 2022-08-14 15:51
> I think the correct URL for this would be
> 
> https://img.shields.io/github/workflow/status/exoRift/react-fluent-mobile/Quality%20Assurance/master
> 
> ?

I should've included this in my closing comment, but I did try that yesterday and it didn't work. I almost feel like the old workflow path is a day(s) old cached version or something

**Comment by chris48s** [comment] 2022-08-14 20:18
> I did try that yesterday and it wasn't working then

Interesting.. :thinking:
I've moved the follow up to #8146
