### ISSUE TITLE
Accessing the website on a specific server has link breakage

### ISSUE THREAD

**Issue by espadrine** [badges/shields#1941] opened 2018-08-18 12:38 UTC
Reproduction:
1. Go to https://51.254.114.150/index.html (and accept the self-signed certificate).
2. Click on the ‘build’ link.

What happens:
- We are redirected to https://51.254.114.150/examples/build which is a 404.

What should happen instead:
- We should be redirected to https://51.254.114.150/#/examples/build as is the case with the main page, on shields.io.

**Comment by paulmelnikow** [comment] 2018-08-18 16:16
I've also noticed this issue on the main site over very slow connections. I can't easily reproduce it locally, though I notice there is a lag before that `#` gets added to the location bar. I think part of the problem is that Next has its own router and is designed for SSR, and then we're running _our own_ router inside of one of their pages. And we're not really using SSR.

We should adopt CRA or Gatsby which is the real fix. Meanwhile the workaround is to insert the hash manually.

Also, We could also server index.html from the server root instead of redirecting to shields.io as we do now. I think that would fix the problem.

**Comment by paulmelnikow** [comment] 2018-08-22 02:29
Hmm, actually, no. I think this was caused by a mistake I made at deploy time, of running `make deploy-s0` and, then later, `make deploy-s1`, without _first_ running `make website`.

I suspect when that happened, the servers got a copy of the previous gh-pages build.

This was addressed in #1793 but that hasn't been merged yet.

**Closed by paulmelnikow** 2018-08-22 02:29 UTC
Labels: developer-experience, frontend
