### ISSUE TITLE
Incorrect 'Donate' button label

### ISSUE THREAD

**Issue by sobolevn** [badges/shields#691] opened 2016-04-12 11:25 UTC
It looks this way for me:

<img width="367" alt="2016-04-12 14 21 13" src="https://cloud.githubusercontent.com/assets/4660275/14458504/5f324040-00ba-11e6-8191-eb0e8ff7d001.png">

I guess the `maxAge` part is not supposed to be shown to users.

**Comment by hugovk** [comment] 2016-04-25 13:51
Duplicate of https://github.com/badges/shields/issues/693?

**Comment by sobolevn** [comment] 2016-04-25 14:20
Pretty, much. It was just opened earlier.

**Comment by espadrine** [comment] 2016-04-26 07:55
Thanks for reporting!

> I guess the maxAge part is not supposed to be shown to users.

You guessed right! My sed one-liner was not generic enough. Now I have two sed one-liners!

**Closed by espadrine** 2016-04-26 07:55 UTC
