### ISSUE TITLE
Our public Jenkins builds show up as 'inaccessible'

### ISSUE THREAD

**Issue by LeoNatan** [badges/shields#1956] opened 2018-08-23 12:33 UTC
Hello,

Our Jenkins server is publicly available, but for some reason, it shows up as 'inaccessible':

![Build Status](https://img.shields.io/jenkins/s/https/jenkins-oss.wixpress.com/job/multi-detox-master.svg)

As I understand, the renderer uses the json API for Jenkins builds?

This is our json:
https://jenkins-oss.wixpress.com/job/multi-detox-master/api/json 

It is available publicly, but for some reason I am assuming the shields server is unable to reach it?

Thanks

**Comment by paulmelnikow** [comment] 2018-08-23 16:47
Hi! Thanks for reporting this.

Does the fix from #1809 help?

**Comment by LeoNatan** [comment] 2018-08-23 17:54
Interesting, using http and 8080 does work: ![Test](https://img.shields.io/jenkins/s/http/jenkins-oss.wixpress.com:8080/job/multi-detox-master.svg).

If possible, we would like to keep SSL. Do you have a log on your end that could shed light on what breaks when attempting to connect through SSL?

**Comment by paulmelnikow** [comment] 2018-08-23 18:51
Heh, yea, agreed. Only one person has access to the server logs. If the problem is reproducible in dev  and [on staging](https://shields-staging.herokuapp.com/) (it probably is) we could troubleshoot it that way, simply enough.

Btw, did you happen to try using https and specifying port 443?

**Comment by LeoNatan** [comment] 2018-08-23 19:02
Specifying 443 doesn't work (still 'inaccessible'). 

Reproduces on staging too:
![Test](https://shields-staging.herokuapp.com/jenkins/s/https/jenkins-oss.wixpress.com/job/multi-detox-master.svg)

**Comment by LeoNatan** [comment] 2018-08-23 19:02
Thanks for the quick responses, btw!

**Comment by calebcartwright** [comment] 2019-04-14 18:36
Underlying error the Shields server is getting when trying to hit your Jenkins instance:
`Inaccessible: unable to verify the first certificate`

**Comment by calebcartwright** [comment] 2019-04-14 18:45
I suppose we could set `strictSSL` to false in our request options to resolve this, but curious what others think

**Comment by paulmelnikow** [comment] 2019-04-14 20:04
Is this the issue from #2812? If so upgrading Node seems like a better solution.

**Comment by calebcartwright** [comment] 2019-04-14 20:16
I'm not sure if they're related, but either way I still get this same `inaccessible` error for Jenkins on Node v10.9.0

**Comment by paulmelnikow** [comment] 2019-04-14 20:48
Hmm, I guess it's something else then. It's strange; I seem to be able to hit https://jenkins-oss.wixpress.com/job/multi-detox-master/api/json through the browser or through curl.

I found this on SO: https://stackoverflow.com/a/32440021/893113

Also this: https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs#comment71644609_32440021

**Comment by calebcartwright** [comment] 2019-04-14 21:42
Yeah I'd seen those too. It has me wondering though about self-hosted Shields instance, especially if those self-hosted instances are hitting services/tools that are using self-signed certs and whether that creates similar issues.

**Comment by paulmelnikow** [comment] 2019-04-15 16:46
Right, self-signed certs is something worth addressing for the self-hosting case.

I think there is a node env var that completely disables SSL certificate checking, so that could be one option. Though it probably would be better to configure certain URLs for which the SSL checks are skipped.

An even better  way to deal with it would be certificate pinning. I wonder if there is a good Node solution for that.

FWIW I think the certificate on jenkins-oss.wixpress.com is not self-signed; rather it's missing its intermediate certificates.

**Comment by calebcartwright** [comment] 2019-04-15 17:04
> FWIW I think the certificate on jenkins-oss.wixpress.com is not self-signed; rather it's missing its intermediate certificates.

Agreed (that Qualsys tool mentioned in one of those SO threads was really helpful). I was thinking more in general

> Though it probably would be better to configure certain URLs for which the SSL checks are skipped

I was thinking maybe as a tactical short term fix we could add a query param to the Jenkins badges that would allow folks to disable the strict SSL check (`/jenkins/s/...../foo.svg?disableStrictSSL`) and we could conditionally use the setting that way.

**Comment by calebcartwright** [comment] 2019-04-19 21:16
@LeoNatan - in https://github.com/badges/shields/pull/3302 we added a new query param on the Jenkins badge that disables the default strict ssl behavior. Since there's a cert chain issue in your target Jenkins instance, you can leverage this new query param to get your Jenkins badges working again with https.

Here's what the badge URL will look like for the job mentioned in your OP (note this won't work until #3302 is deployed to production, [this comment](https://github.com/badges/shields/pull/3302#issuecomment-485007459) will be updated by the deployment bot once #3302 is deployed):

https://img.shields.io/jenkins/s/https/jenkins-oss.wixpress.com/job/multi-detox-master.svg?disableStrictSSL 
![](https://img.shields.io/jenkins/s/https/jenkins-oss.wixpress.com/job/multi-detox-master.svg?disableStrictSSL) 

Here's a couple examples from our staging environment to visualize the difference:

https://shields-staging.herokuapp.com/jenkins/s/https/jenkins-oss.wixpress.com/detox-android-56-master.svg
Old behavior, without the param: ![](https://shields-staging.herokuapp.com/jenkins/s/https/jenkins-oss.wixpress.com/detox-android-56-master.svg)

https://shields-staging.herokuapp.com/jenkins/s/https/jenkins-oss.wixpress.com/detox-android-56-master.svg?disableStrictSSL
New behavior, with the param: ![](https://shields-staging.herokuapp.com/jenkins/s/https/jenkins-oss.wixpress.com/detox-android-56-master.svg?disableStrictSSL)

Accordingly, I'm going to go ahead and close this issue

**Closed by calebcartwright** 2019-04-19 21:16 UTC
Labels: question, service-badge

**Comment by LeoNatan** [comment] 2019-04-19 21:24
Thanks guys!

**Comment by LeoNatan** [comment] 2019-04-19 21:25
BTW, regarding the certificate issue. It's peculiar you say so because no browser shows this error.

**Comment by calebcartwright** [comment] 2019-04-19 21:38
You can find more detailed info on the cert chain issue here: https://www.ssllabs.com/ssltest/analyze.html?d=jenkins-oss.wixpress.com&hideResults=on 

The browsers tend to be much less strict than the default settings used by http clients, hence our http client barking at the cert chain issue even though web browsers do not.

**Comment by LeoNatan** [comment] 2019-04-19 22:32
Cool, thanks, will take it with our IT
