### ISSUE TITLE
img.shields.io is down

### ISSUE THREAD

**Issue by paladox** [badges/shields#645] opened 2016-01-30 19:26 UTC
Hi when visting a link such as http://img.shields.io/travis/hexchat/hexchat.svg?style=flat it brings up the cloudflare error page also images shown on http://shields.io do not show. Please fix this.

**Comment by Foorack** [comment] 2016-01-30 22:52
Yes, this have been going on for several hours, nearly all day local time zone. :-1:

**Comment by standage** [comment] 2016-01-31 03:34
Wow, must be a serious problem to have over 8 hours of down time.

**Comment by marcwebbie** [comment] 2016-01-31 04:55
Any news on that? I am experiencing the same issue for about 10 hours

**Comment by jacebrowning** [comment] 2016-01-31 05:08
I am also experiencing this.

**Comment by montanaflynn** [comment] 2016-01-31 05:43
@espadrine I'm getting a 523 response code from the `img.shields.io` host for all my badges:

```
$ curl -I https://img.shields.io/travis/montanaflynn/toy-spelling-corrector.svg
> HTTP/1.1 523 Origin Unreachable

**Comment by IonicaBizau** [comment] 2016-01-31 09:44
Same here. Does somebody (still) take care of this project? :thought_balloon: 

![image](https://cloud.githubusercontent.com/assets/2864371/12701351/ea66a39c-c80f-11e5-8ae3-633916ad50e6.png)

**Comment by egoist** [comment] 2016-01-31 10:31
still down...

**Comment by luckytianyiyan** [comment] 2016-01-31 11:54
has been lasting one day.@espadrine

**Comment by nhz-io** [comment] 2016-01-31 12:24
2 days down

**Comment by marcwebbie** [comment] 2016-01-31 14:35
What is the best shields.io alternative out there?

**Comment by espadrine** [comment] 2016-01-31 14:38
Sorry, bad coincidence. I wasn't very available this week-end. I restarted the server computer… Linux crashed. It's usually really rare.

**Comment by IonicaBizau** [comment] 2016-01-31 14:38
Shields.io works again! Thanks! :tada:

**Comment by marcwebbie** [comment] 2016-01-31 14:45
Hello @espadrine 

Thanks for fix :smile:

**Comment by IvanGoncharov** [comment] 2016-01-31 15:23
@espadrine Thanks for fix.
You actually fixed 246,849 README files:
https://github.com/search?utf8=%E2%9C%93&q=filename%3AREADME.md+img.shields.io&type=Code&ref=searchresults

**Comment by Foorack** [comment] 2016-01-31 18:53
@IvanGoncharov Wow, that's an incredible number.
@espadrine Thanks :smiley:

**Comment by IonicaBizau** [comment] 2016-01-31 18:56
[250](https://github.com/search?o=desc&q=filename%3AREADME.md+img.shields.io+user%3Aionicabizau&ref=searchresults&s=indexed&type=Code&utf8=%E2%9C%93) of these `README.md` files are mine. :joy: :grin:

**Comment by nhz-io** [comment] 2016-01-31 18:57
thats it, time to make my own badger based on aws lambda

**Comment by swrobel** [comment] 2016-02-01 15:29
Seems to be down again...

**Comment by IonicaBizau** [comment] 2016-02-01 15:30
Same here... :sob:

**Comment by egoist** [comment] 2016-02-01 15:36
This is as bad as GitHub goes down 🙄

**Comment by espadrine** [comment] 2016-02-01 15:47
The server did not die, but it is getting a lot of load currently, way more than usually: something like 200 req/s. I'd suspect someone is playing with scripts and servers.

**Comment by espadrine** [comment] 2016-02-01 15:56
I put CloudFlare in "under attack" mode for a few minutes, presumably breaking those scripts. The load has gone back to around 50req/s.

**Comment by nhz-io** [comment] 2016-02-01 16:37
Just ban the origin

**Comment by nhz-io** [comment] 2016-02-02 15:41
Its not down, but the time that it takes to respond with svg content is longer than githubusercontent will wait for data, so, its not down but its pretty much defunct

**Comment by standage** [comment] 2016-02-02 15:49
@espadrine Are you still mitigating some kind of high request load or attack?

**Comment by nhz-io** [comment] 2016-02-02 15:56
Its back up again. Its feels like waves of spam hitting the service

**Comment by levigroker** [comment] 2016-02-03 17:11
Appears to still be highly unresponsive (down) as of last night and still today.

**Comment by tankerkiller125** [comment] 2016-02-03 22:24
Probably related to #445

**Comment by IonicaBizau** [comment] 2016-02-04 18:36
Down again! :disappointed: Isn't there a real fix for this behavior...?

**Comment by groggemans** [comment] 2016-02-07 12:43
250.000+ README files are using shields.io, so that's a substantial part of the github users/repo's..
Why don't u ask the Github team to help you out by hosting this awesome project?
They should have the infrastructure to keep it working flawlessly.

**Comment by kblanks** [comment] 2016-02-07 17:04
What @groggemans suggested could be great. GitHub can clearly see the popularity of this site so I'm sure that hosting it or integrating it into the site would be considered.

**Comment by julmot** [comment] 2016-02-07 18:29
Down again. If GitHub doesn't help you out try to use [Cloudflare](https://www.cloudflare.com/). I think availability is the most important in this project.

**Comment by foxylion** [comment] 2016-02-07 18:48
@julmot They are already using Cloudflare.

**Comment by espadrine** [comment] 2016-02-07 18:57
It's not done yet, but FYI, I'm configuring a new server. It will be DNS round-robin'ed. The peak requests has reached 60req/s, which despite my attempts at optimization seems to be overwhelming for a single core.

**Comment by kblanks** [comment] 2016-02-07 19:01
@espadrine If you need more capacity I'm more than happy to provide you with a few instances.

**Comment by espadrine** [comment] 2016-02-07 19:34
All right, folks, we are now running two servers. One is in the Americas, and one is in Europe, but since which IP picked is random (I have two A (DNS) fields set up on CloudFlare to two distinct IP addresses), your location doesn't matter much. Things should get better as the world learns this DNS change.

I still have some work to do to improve monitoring and filtering against bad actors, but I'll call it a day for today.

**Comment by julmot** [comment] 2016-02-07 19:35
:+1:

**Comment by julmot** [comment] 2016-02-07 19:49
@espadrine I think many requests will come from the main page shields.io, because you are embedding all the images to show an example. Did you think about using [base64_encode](http://stackoverflow.com/questions/35879/base64-encoding-image) to reduce the request amount (currently about ~235 with huge response times)?

**Comment by espadrine** [comment] 2016-02-07 19:52
@julmot That is absolutely something of a concern, although the plan is to load the images only when shown: https://github.com/badges/shields/issues/633. If you have time to do so, it would be a delight!

**Comment by julmot** [comment] 2016-02-07 19:55
For me in the latest FF all images will be loaded on start.
I'll have a look into this in the next week.
Cheers.

**Comment by foxylion** [comment] 2016-02-07 20:22
Maybe it would also be an idea to increase the cache heavily,  especially the cache time.
Digging into the code showed to me it is only caching 1000 badges with a 5 second cache time. 
Maybe increase it to 20.000 and 60 seconds? 
I think an update every 60 seconds should be fine for nearly all badges. 
As long as the bandwidth is not a problem, it could reduce the load. 
Do you have a metric how many cache hits you currently have?

**Comment by espadrine** [comment] 2016-02-07 20:46
> Maybe increase it to 20.000 and 60 seconds?

It used to cause too many OOM-killer crashes to be manageable, but it would probably be fine now, yes.

> Do you have a metric how many cache hits you currently have?

I don't, although that's a longstanding TODO.

**Comment by foxylion** [comment] 2016-02-08 17:43
By default Cloudflare should not cache any HTML-Contents, but the images.
The underlying problem is (as far as I can see) that it looks like all the headers you send are targeting that the CDNs (Cloudflare, GitHub-CDN) do not cache anything.

**Comment by espadrine** [comment] 2016-02-09 10:45
@foxylion What I had tried is [this](https://github.com/badges/shields/issues/445#issuecomment-158636192).

The minimum caching expiration available is 2h by default, and 30min through page rules. Don't you fear that people will find that to be too long?

![cf-1](https://cloud.githubusercontent.com/assets/100689/12914048/85cb56fc-cf22-11e5-8892-bbea1a1fe207.png)
![cf-2](https://cloud.githubusercontent.com/assets/100689/12914047/85c7b8c6-cf22-11e5-8efc-2178ac7036dc.png)

**Comment by groggemans** [comment] 2016-02-09 10:57
It depends on the badge. Things like a gitter chat badge can be cached for a very long time, a build status is a whole other thing. Maybe you could add a subdomein that provides longer caching? And keep the things that need short caching times like it is now?

**Comment by lfender6445** [comment] 2016-02-10 01:13
i think service is out

**Comment by foxylion** [comment] 2016-02-10 18:48
@espadrine Sorry, I didn't know that the lower times can only be used in the payed service of Cloudflare.

I would suggest another solution: Provide a service (if it does not already exists) where the complete configuration of a badge can be encoded in the url e.g. ``/badge/{bgcolor-left}/{bgcolor-right}/{color-left}/{color-right}/{text-left}/{text-right}/badge.[svg/png/gif]``. (Could be for example ``/badge/f00/0f0/00f/000/License/Apache%202.0%2F2.1/badge.svg``). Then refactor all existing services to Respond with `302 Found` status code and redirect to the static badge URL.

Now you can enable the permanent caching of ``/badge/`` on the Cloudflare side and every badge will only be generated once.

The cache in your server could be changed to only cache the badges contents (color, text) for a given and prevent calling the remote APIs too often. It should also reduce the cache size drastically.

The full solution should reduce both server load and network traffic.

**Comment by standage** [comment] 2016-02-10 18:57
@foxylion Works for badges that don't change, like license or gitter, but doesn't work for badges that read, for example, build status or version number from external services. And in my experience, that's what I see the vast majority of these badges being used for.

**Comment by foxylion** [comment] 2016-02-10 19:00
@standage I think it should work. Cloudflare should only cache the static badge (which has erverything encoded in the url). The dynamic badges will do a HTTP redirect to the static badge. So you reference the dynamic badge url in your README and it will resolve to a static version of the badges current state.

**Comment by standage** [comment] 2016-02-10 19:07
@foxylion Code coverage is an interesting case: you don't want on the order of a hundred (0%-100%) static cached badges for each project, although with a smart approach I suppose it would be possible to reduce redundancy (finite number of possible percentage values and styles).

**Comment by foxylion** [comment] 2016-02-10 19:11
@standage You won't cache anything. That does Cloudflare for you. ;-)

**Comment by espadrine** [comment] 2016-02-10 19:16
> Provide a service (if it does not already exists) where the complete configuration of a badge can be encoded in the url.

That seems roughly what shields.io's existing `/badge/` services does: http://shields.io/#your-badge.

I'm not sure why you're suggesting this, though. I think you assume that most of the CPU time is spent generating the images. However, that generation is a function call that does a string concatenation, which is pretty cheap. I probably could try to see how much CloudFlare would agree to cache, but I'd have to carefully monitor how many requests I get, as depending on CloudFlare, it could easily rise. In any case, I don't see how it could improve anything. In current requests, knowing when I need to call the vendors, calling them and treating the result is the expensive part.

**Comment by foxylion** [comment] 2016-02-10 21:39
> However, that generation is a function call that does a string concatenation, which is pretty cheap.

Okay, sorry then, when the traffic is not an issue that won't be a proper fix.

Maybe then just cache the responses of the APIs for a longer time.
Do the SVG generation always (if that is really near to 0 cost), so it will reduce cache size immensively.
And add a cache timeout per service to improve the performance even more.

**Comment by clifg** [comment] 2016-02-13 07:05
+1 -- I haven't been able to get any badges from the site today. All examples are currently failing (523) on www.shields.io as well.

**Comment by espadrine** [comment] 2016-02-13 11:13
@clifg s0, our first server, died. The DNS round-robin seems to work in such a way that clients which point to a dead server take some time to learn to ask the live one. I'm learning more about DNS every day. I restarted s0.

**Comment by espadrine** [comment] 2016-02-13 11:28
Haha, and a few minutes after I turned it back on, OVH's built-in DDoS prevention system flagged the sudden incoming flood of requests. Many requests were blocked for 15min. Back online.

**Comment by blitzprog** [comment] 2016-02-13 11:48
@espadrine Thank you!

**Comment by tankerkiller125** [comment] 2016-02-13 12:15
At this point I think it might truly be in our best interest to get github to host it... They have more resources than what this project could possibly use. Not to mention unlike us they have money and vast networking capabilities.

**Comment by clifg** [comment] 2016-02-13 15:51
@espadrine thanks! I appreciate you trying to keep this thing afloat. Also agree that it would be awesome if github would host it since so many projects use it.

**Comment by Juanlu001** [comment] 2016-03-02 18:02
Folks, it's great that everyone made their suggestions and all but this project receives less than $ 5 a week.

https://gratipay.com/shields/

I don't know what's the sustainability status of shields.io, maybe @espadrine can tell.

**Comment by 304NotModified** [comment] 2016-03-09 17:19
Related: https://github.com/badges/shields/issues/655

**Comment by kkodev** [comment] 2016-05-05 16:36
It keeps failing again with 520 over last few days.
I'd be happy to host my own version, but it doesn't install anymore.

**Comment by espadrine** [comment] 2016-05-05 17:39
Currently, the DNS points to two IPs, which both seem to work fine:

- https://192.99.59.72/try.html
- https://51.254.114.150/try.html

(The self-signed certificate is normal, it's the procedure for using CloudFlare's Universal SSL.)

**Comment by kkodev** [comment] 2016-05-05 17:42
https://img.shields.io/badge/1.1.0-37-blue.png doesn't work for me now

**Comment by 304NotModified** [comment] 2016-05-05 17:45
PS last link works for me

**Comment by 304NotModified** [comment] 2016-05-05 17:46
And now also 520

Error 520 Ray ID: 29e601d97efc0c05 • 2016-05-05 17:45:38 UTC
Web server is returning an unknown error

**Comment by espadrine** [comment] 2016-05-05 17:46
@kkodev Ah, that is a lot more specific, and I think I know why it doesn't work. While I attempt to fix it, I would recommend the use of SVG images instead.

**Comment by kkodev** [comment] 2016-05-05 17:46
Thanks a lot man!

**Comment by 304NotModified** [comment] 2016-05-05 17:47
If you are the owner of this website:
There is an issue between CloudFlare's cache and your origin web server. CloudFlare monitors for these errors and automatically investigates the cause. To help support the investigation, you can pull the corresponding error log from your web server and submit it our support team. Please include the Ray ID (which is at the bottom of this error page). Additional troubleshooting resources.

**Comment by espadrine** [comment] 2016-05-05 18:11
It ought to be fixed, although I can't recommend using SVG enough.

**Closed** 2016-05-05 18:10 UTC

**Comment by espadrine** [comment] 2016-05-05 18:42
Further maintenance was necessary on the Canadian server. It should now work across the board.

**Comment by kkodev** [comment] 2016-05-05 21:56
Will certainly look into SVG as an alternative but for now being held up by https://github.com/fastlane/fastlane as a dependency:(
Thanks for help anyway, much appreciated!
