### ISSUE TITLE
Microsoft Edge Add-Ons

### ISSUE THREAD

**Issue by LukePrior** [badges/shields#7605] opened 2022-02-12 04:36 UTC
:clipboard: **Description**

This badge would mirror those available for the Chrome Web Store and Firefox Add-On Store.

The three main badges should be:
- total number of users (`/chrome-web-store/users/` & `/amo/users/`)
- current rating (`/chrome-web-store/rating/` & `/amo/rating/`)
- current extension version (`/chrome-web-store/v/` & `/amo/v/`)

:link: **Data**

Microsoft currently has a limited API in private testing that can only be used to programmatically update existing extensions.

I'm not sure if there are plans to add support for Microsoft Edge to https://github.com/awesome-webextension/webextension-store-meta.

:microphone: **Motivation**

The badges should be implemented the same way as with Chrome and Firefox badges accepting the extension id e.g. `bcoemipadbcdgdgoijfejceofakdnmgo`.

The badge would be used to display stats for extensions published on all three stores.

**Comment by calebcartwright** [comment] 2022-02-12 04:44
Thanks for sharing your idea, but going to close as a duplicate of #4690, see also #7349

**Closed by calebcartwright** 2022-02-12 04:44 UTC
Labels: service-badge

**Comment by LukePrior** [comment] 2022-02-12 06:06
My apologies, thanks.

**Comment by calebcartwright** [comment] 2022-02-12 19:10
No worries!
