### ISSUE TITLE
💡 Badge Request: ghcr.io Docker

### ISSUE THREAD

**Issue by mrclfd** [badges/shields#6997] opened 2021-09-08 16:30 UTC
- For **ghcr.io Docker** services like [this](https://ghcr.io/mrclfd/lamphor:latest)
- Information type:
`"download by tag | {download by tag}"`, `"total download | {total download}"`, `"image size | {size}MB"`, `"version | {version}` or `version | v{version}`"

**Comment by chris48s** [comment] 2021-09-08 17:11
Thanks. This is a valid feature request, but I'm going to close as I think it is a duplicate of https://github.com/badges/shields/issues/5594
Lets track it there

**Closed by chris48s** 2021-09-08 17:11 UTC
Labels: service-badge

**Comment by mrclfd** [comment] 2021-09-09 04:37
oh sorry, thanks Sur
