### ISSUE TITLE
Can you update more facebook follow badges

### ISSUE THREAD

**Issue by QuangNguyen1607** [badges/shields#6711] opened 2021-07-04 16:46 UTC
You can update the facebook follow display feature on the shields, because I see that there are currently no facebook badges, and I think it is really necessary and useful. Thank you for making such a great utility.

**Comment by calebcartwright** [comment] 2021-07-04 21:17
hello @QuangNguyen1607 :wave: Thank you for reaching out, but I think this is a duplicate of #2120 and unlikely to go anywhere unless things have changed on the Facebook/Instagram end.

As an aside, we've structured our issue templates with a specific set of questions so that there's sufficient information to facilitate a more productive dialog. I imagine we'll need to close this just like the other prior Facebook requests, but on the off chance it is possible to proceed then we'd need you to provide responses to the questions that were posed in the issue template.

@PyvesB - I believe you were the most closely involved with the previous Facebook badge requests, what are your thoughts on this one?

**Comment by chris48s** [comment] 2021-07-05 18:59
I think the issues with the rate limits on the instagram/facebook APIs are still the same now as they were then.

If you just want follow buttons you can do  something like this with the static badges though
* ![](https://img.shields.io/badge/follow--000?style=social&logo=facebook) https://img.shields.io/badge/follow--000?style=social&logo=facebook
* ![](https://img.shields.io/badge/follow--000?style=social&logo=instagram) https://img.shields.io/badge/follow--000?style=social&logo=instagram

**Closed by chris48s** 2021-07-05 18:59 UTC
Labels: service-badge
