### ISSUE TITLE
Suggests badges not working because of cross-origin browser policies

### ISSUE THREAD

**Issue by lukeramsden** [badges/shields#851] opened 2017-01-06 17:03 UTC
If you try to suggest badges it throws up this error:
```
XMLHttpRequest cannot load https://img.shields.io/$suggest/v1?url=https%3A%2F%2Fgithub.com%2FTissLTD%2Ftiss_mobile. The 'Access-Control-Allow-Origin' header has a value 'http://shields.io' that is not equal to the supplied origin. Origin 'https://shields.io' is therefore not allowed access.
```

**Comment by paulmelnikow** [comment] 2017-03-28 04:47
Hi, thanks for reporting this. I can't reproduce this problem. I went to https://shields.io/, entered `https://github.com/TissLTD/tiss_mobile`, and clicked Suggest badges.

This was the JSON response:

```json
{"badges":[],"err":{}}
```

Where were you loading the page from?

**Comment by paulmelnikow** [comment] 2017-03-28 05:22
This was fixed in 9816a50. Dupe of #779.

**Closed by paulmelnikow** 2017-03-28 05:22 UTC
Labels: question
