### ISSUE TITLE
Dynamic XML Badge not working

### ISSUE THREAD

**Issue by Washingtonwei** [badges/shields#9784] opened 2023-12-06 16:56 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I put in the URL pointing to my pom.xml on GitHub and the XPath for the Spring Boot version. The tool didn't return anything.

pom.xml URL: https://raw.githubusercontent.com/Washingtonwei/hogwarts-artifacts-online/main/pom.xml
XPath: 
/project/parent/version
./project/parent/version
.//project/parent/version

Tried all three.

Thanks!

### 🔗 Link to the badge

https://img.shields.io/badge/dynamic/xml?url=https%3A%2F%2Fraw.githubusercontent.com%2FWashingtonwei%2Fhogwarts-artifacts-online%2Fmain%2Fpom.xml&query=.%2Fproject%2FmodelVersion

**Comment by chris48s** [comment] 2023-12-06 19:33
I think this is a duplicate of https://github.com/badges/shields/issues/4250

A working badge URL that achieves what you are trying to do would be

https://img.shields.io/badge/dynamic/xml?url=https%3A%2F%2Fraw.githubusercontent.com%2FWashingtonwei%2Fhogwarts-artifacts-online%2Fmain%2Fpom.xml&query=%2F*%5Blocal-name()%3D'project'%5D%2F*%5Blocal-name()%3D'parent'%5D%2F*%5Blocal-name()%3D'version'%5D

**Closed** 2023-12-06 19:33 UTC
Labels: question

**Comment by Washingtonwei** [comment] 2023-12-06 20:42
Thanks! It would be great if this can be put in the document.

**Comment by chris48s** [comment] 2023-12-10 18:31
Yep reasonable point. I've submitted https://github.com/badges/shields/pull/9798 which makes some improvements to the documentation for this badge.
