### ISSUE TITLE
Alternative icon URLs to Simple Icons

### ISSUE THREAD

**Issue by HariSekhon** [badges/shields#10464] opened 2024-08-16 17:48 UTC
:clipboard: **Description**

Feature request to use other icons by URL instead of just Simple Icons or base64 embedded icons which make URLs huge.

Motivation is that Simple Icons are removing some icons that I use eg.

https://github.com/simple-icons/simple-icons/issues/11372

For example, D2 and Python diagrams languages pull icons dynamically which you can see in many diagrams-as-code here:

https://github.com/HariSekhon/Diagrams-as-Code#readme

**Comment by HariSekhon** [comment] 2024-08-16 18:26
I've just rustled up a quick script to work around this:

https://github.com/HariSekhon/DevOps-Bash-tools/blob/master/bin/shields_embed_logo.sh

which I've documented in both the `--help` usage of the script as well as my [Knowlege-Base](https://github.com/HariSekhon/Knowledge-Base) repo here:

https://github.com/HariSekhon/Knowledge-Base/blob/35e9697416afc2e7531a6dbb0c8de81b61ca2acc/markdown.md#removed-icons

I think it would be nice if shields.io could pull from icon URLs like my favourite [D2lang](https://d2lang.com/) does.

But I also appreciate this would have a performance cost as the diagramming tech above is local and not internet and therefore latency sensitive.

Thank you for your time to review and feed back on this either way.

And also I'm big fan of your work on shields.io, thank you for this excellent project.

**Comment by HariSekhon** [comment] 2024-08-16 19:12
Any idea why this embedded data icon is dark compared to the simple icons one which is white?

The simple icons version is light:

```markdown
[![My LinkedIn](https://img.shields.io/badge/LinkedIn%20Profile-HariSekhon-blue?logo=linkedin)](https://www.linkedin.com/in/HariSekhon/)
```

[![My LinkedIn](https://img.shields.io/badge/LinkedIn%20Profile-HariSekhon-blue?logo=linkedin)](https://www.linkedin.com/in/HariSekhon/)

Compared to this embedded version where I even added the `logoColor=white` parameter but it doesn't seem to be working:

``` markdown
[![My LinkedIn](https://img.shields.io/badge/LinkedIn%20Profile-HariSekhon-blue?logoColor=white&logo=data:image/svg%2bxml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+TGlua2VkSW48L3RpdGxlPjxwYXRoIGQ9Ik0yMC40NDcgMjAuNDUyaC0zLjU1NHYtNS41NjljMC0xLjMyOC0uMDI3LTMuMDM3LTEuODUyLTMuMDM3LTEuODUzIDAtMi4xMzYgMS40NDUtMi4xMzYgMi45Mzl2NS42NjdIOS4zNTFWOWgzLjQxNHYxLjU2MWguMDQ2Yy40NzctLjkgMS42MzctMS44NSAzLjM3LTEuODUgMy42MDEgMCA0LjI2NyAyLjM3IDQuMjY3IDUuNDU1djYuMjg2ek01LjMzNyA3LjQzM2MtMS4xNDQgMC0yLjA2My0uOTI2LTIuMDYzLTIuMDY1IDAtMS4xMzguOTItMi4wNjMgMi4wNjMtMi4wNjMgMS4xNCAwIDIuMDY0LjkyNSAyLjA2NCAyLjA2MyAwIDEuMTM5LS45MjUgMi4wNjUtMi4wNjQgMi4wNjV6bTEuNzgyIDEzLjAxOUgzLjU1NVY5aDMuNTY0djExLjQ1MnpNMjIuMjI1IDBIMS43NzFDLjc5MiAwIDAgLjc3NCAwIDEuNzI5djIwLjU0MkMwIDIzLjIyNy43OTIgMjQgMS43NzEgMjRoMjAuNDUxQzIzLjIgMjQgMjQgMjMuMjI3IDI0IDIyLjI3MVYxLjcyOUMyNCAuNzc0IDIzLjIgMCAyMi4yMjIgMGguMDAzeiIvPjwvc3ZnPgo=)](https://www.linkedin.com/in/HariSekhon/)
```

[![My LinkedIn](https://img.shields.io/badge/LinkedIn%20Profile-HariSekhon-blue?logoColor=white&logo=data:image/svg%2bxml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+TGlua2VkSW48L3RpdGxlPjxwYXRoIGQ9Ik0yMC40NDcgMjAuNDUyaC0zLjU1NHYtNS41NjljMC0xLjMyOC0uMDI3LTMuMDM3LTEuODUyLTMuMDM3LTEuODUzIDAtMi4xMzYgMS40NDUtMi4xMzYgMi45Mzl2NS42NjdIOS4zNTFWOWgzLjQxNHYxLjU2MWguMDQ2Yy40NzctLjkgMS42MzctMS44NSAzLjM3LTEuODUgMy42MDEgMCA0LjI2NyAyLjM3IDQuMjY3IDUuNDU1djYuMjg2ek01LjMzNyA3LjQzM2MtMS4xNDQgMC0yLjA2My0uOTI2LTIuMDYzLTIuMDY1IDAtMS4xMzguOTItMi4wNjMgMi4wNjMtMi4wNjMgMS4xNCAwIDIuMDY0LjkyNSAyLjA2NCAyLjA2MyAwIDEuMTM5LS45MjUgMi4wNjUtMi4wNjQgMi4wNjV6bTEuNzgyIDEzLjAxOUgzLjU1NVY5aDMuNTY0djExLjQ1MnpNMjIuMjI1IDBIMS43NzFDLjc5MiAwIDAgLjc3NCAwIDEuNzI5djIwLjU0MkMwIDIzLjIyNy43OTIgMjQgMS43NzEgMjRoMjAuNDUxQzIzLjIgMjQgMjQgMjMuMjI3IDI0IDIyLjI3MVYxLjcyOUMyNCAuNzc0IDIzLjIgMCAyMi4yMjIgMGguMDAzeiIvPjwvc3ZnPgo=)](https://www.linkedin.com/in/HariSekhon/)

The exact instructions I followed as in the Knowledge Base link in the comment above?

**Comment by LitoMore** [comment] 2024-08-28 21:43
@HariSekhon Simply append the attribute `fill="#0A66C2"` to the SVG source before the base64 encoding.

**Comment by HariSekhon** [comment] 2024-08-29 12:17
Thanks, that's worked

**Comment by calebcartwright** [comment] 2024-08-29 18:23
Closing as a duplicate of #9143

**Closed by calebcartwright** 2024-08-29 18:23 UTC
