### ISSUE TITLE
Infinite Redirect in Edge Browser

### ISSUE THREAD

**Issue by paolobarbolini** [badges/shields#2164] opened 2018-10-10 19:36 UTC
Are you experiencing this issue on shields.io or your own instance?
 - [x] shields.io
 - [ ] My instance

**Browser Info**:
Microsoft Edge 41.16299.699.0
Microsoft EdgeHTML 16.16299

:beetle: **Description**:
* Visit shields.io in Edge browser
* Click on an example, like _Chat_ (it doesn't happen with all examples, so trying the test with different ones might be necessary)
* Press the back button
* You will be stuck in a infinite redirect between https://shields.io/ and https://shields.io/#/ and the only option will be to kill the process.

Might be related to #2109

**Comment by chris48s** [comment] 2018-10-10 20:07
Thanks for reporting this with steps to reproduce. I've just tried this on a windows machine and I see the same thing in Edge. No idea what is causing it though :thinking:

**Comment by paulmelnikow** [comment] 2019-02-06 22:55
Pretty sure this will have been fixed by #2906 😄

**Comment by calebcartwright** [comment] 2019-02-07 01:19
I just tried to reproduce in Edge, with every category, and was unable to reproduce so I'm thinking it was indeed addressed by #2906

**Closed** 2019-02-07 19:08 UTC
Labels: bug, frontend
