### ISSUE TITLE
Bring back NuGet download stats

### ISSUE THREAD

**Issue by kzu** [badges/shields#792] opened 2016-09-13 19:42 UTC
The new APIs in NuGet v3 server should make this fairly straightforward now.

For example, to get the stats for GitLink, you would issue an HTTP get to:

https://api-v2v3search-0.nuget.org/query?q=packageid:gitlink

Which gives you json with `data.totalDownloads = 11605` as of this writing.

**Comment by paulmelnikow** [comment] 2017-04-17 22:53
Hi, thanks for suggesting this.

Would you like to open a pull request?

**Comment by paulmelnikow** [comment] 2017-04-18 02:04
Looks like a duplicate of #678, so closing in favor of that.

**Closed by paulmelnikow** 2017-04-18 02:04 UTC
Labels: vendor-badge

**Comment by Daniel15** [comment] 2017-04-18 05:26
Submitted a pull request: https://github.com/badges/shields/pull/945
