### ISSUE TITLE
Matplotlib package badge

### ISSUE THREAD

**Issue by SaeedShurrab** [badges/shields#6685] opened 2021-06-28 16:37 UTC
:clipboard: **Description**

- Which service is this badge for e.g: MatPlotLib python package
- What sort of information should this badge show?
 The name of the package as well as its logo in a static format

:link: **Data**

Where can we get the data from?

- All required data are available from the official website in [Matplotlib](https://matplotlib.org/)

:microphone: **Motivation**

Most python packages have their own badges such as pandas, numpy, plotly and Keras however this important package does not have a badge.

it will be very useful to add it as most of the developers use this package and hence there is a need to be implemented.

**Comment by calebcartwright** [comment] 2021-06-28 17:14
> What sort of information should this badge show?
> The name of the package as well as its logo in a static format

Thanks for reaching out but going to close this. Shields provides the ability for users to create freeform static badges via our static badge builder, but we very much by design do not provide pre-canned static badges. Folks are free to use our static badge builder to serve whatever use case they see fit, as would be the case here

**Closed by calebcartwright** 2021-06-28 17:14 UTC
