### ISSUE TITLE
AppStore and PlayStore badges

### ISSUE THREAD

**Issue by mrpatiwi** [badges/shields#649] opened 2016-02-05 02:16 UTC
It would be awesome to have an AppStore and PlayStore badges for open source mobile apps.

![appstore](https://mrpatiwi.github.io/app-badges/appstore.png) ![playstore](https://mrpatiwi.github.io/app-badges/playstore.png)

**Comment by espadrine** [comment] 2016-03-28 18:34
I agree. It would be fantastic. For Google Play, there's this thing that seems related, which we might be able to use to copy functionality: https://code.google.com/archive/p/android-market-api/.
I have no idea how to do it for the App Store, but I didn't dig.

**Comment by paulmelnikow** [comment] 2017-03-28 19:49
Related: #840

**Comment by paulmelnikow** [comment] 2017-04-10 18:41
Update: iTunes App Store was added via #840 (pending deploy).

**Comment by paulmelnikow** [comment] 2017-04-18 02:58
Play Store store is a duplicate of #358, so closing.

**Closed by paulmelnikow** 2017-04-18 02:58 UTC
Labels: vendor-badge
