### ISSUE TITLE
dynamic badge don't change color if file inaccessible or key not existant

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1442] opened 2018-01-12 16:04 UTC
As seen in https://github.com/Cockatrice/Magic-Spoiler/pull/193
- It only displays `label | invalid resource` in green for the json file not existing
- It only displays `label | ` in green for a non-existing $key in the linked json (no example in the linked pr)

The badge right side should change the color to highlight a problem.
For the second case it should print an error, too. It looks like it's returning an empty value, but it should say "key not found" for example.

**Comment by paulmelnikow** [comment] 2018-01-14 22:01
Makes sense. Should be red for a nonexistent file IMO.

A non existing key is probably not an error, but we should print something like “no result,” which looks reasonable if it’s intentional and also makes it clear what the problem is to someone setting one of these up.

**Comment by paulmelnikow** [comment] 2018-01-14 22:01
@RedSparr0w thoughts?

**Comment by tooomm** [comment] 2018-01-14 22:08
@paulmelnikow Should the color for the non existing key case change, too?
Yellow/orange for example? Or still green?

**Comment by paulmelnikow** [comment] 2018-01-14 22:13
Agreed that green doesn’t really make sense. Maybe gray is better for a missing value. If we don’t consider it an error.

**Comment by RedSparr0w** [comment] 2018-01-15 00:50
They should have all been `lightgrey` for 404 or anything that isn't `200 OK` but looks like it is using the old `badgeData.colorB = 'lightgrey'` rather than `badgeData.colorscheme = 'lightgrey'`

Will create a PR to fix that soon.

I think they should probably all stay as `lightgrey`,
As that is what most of the other badges return for those same errors,
Though i feel `red` does make more sense.
But IIRC this should also not matter so much in the `node-8` branch as the 404/!=200 errors are all handled in 1 place rather than by each individual service?

**Comment by paulmelnikow** [comment] 2018-01-15 02:51
Yea, while transient errors are reasonable to present in gray since they have nothing to do with the caller / don't require anything to be fixed on the caller's side, I think a 404 or our equivalent of a 400 would reasonably be red, since it's always a problem with the request and requires a change.

I have some error-handling code drafted, though it could always be overridden on a service-by-service basis…

**Closed** 2018-01-16 00:53 UTC
Labels: service-badge

**Comment by tooomm** [comment] 2018-01-16 10:08
Thanks for looking into that @RedSparr0w !

**Comment by RedSparr0w** [comment] 2018-01-16 19:53
No Worries :smile:
