### ISSUE TITLE
Badge request: itch.io

### ISSUE THREAD

**Issue by MagicLike** [badges/shields#6906] opened 2021-08-18 17:27 UTC
:clipboard: **Description**

[itch.io](https://itch.io) is mainly an indie game platform.
The badge(s) should include something like this:
* Download counter for a game: ![Download counter](https://img.shields.io/badge/downloads-download%20counter-brightgreen)
* View counter for a game: ![View counter](https://img.shields.io/badge/views-view%20counter-brightgreen)
* Compatability for a game (Windows, Linux, MacOS, Android & Browser): ![OS - true](https://img.shields.io/badge/os-true-success) ![OS- false](https://img.shields.io/badge/os-false-critical)

:link: **Data**

There is an public API, but it requires an API key. (Which can only be get via an account.)
API documentation: https://itch.io/docs/api/serverside

:microphone: **Motivation**

I want to be able to embed for example a download counter of my game onto my website...

**Comment by calebcartwright** [comment] 2021-08-18 17:47
Thanks for reaching out but going to close as a duplicate of #3592 so that we can keep the discussion focused in one place

**Closed by calebcartwright** 2021-08-18 17:47 UTC
Labels: service-badge
