### ISSUE TITLE
当star数超过1k时，如何显示具体数字而不是1.x k

### ISSUE THREAD

**Issue by zrsaber** [badges/shields#7981] opened 2022-05-18 07:25 UTC
:clipboard: **Description**

当star数超过1k时，如何显示具体数字而不是1.x k

**Comment by chris48s** [comment] 2022-05-18 18:30
I ran this through google translate and it said:

> When the number of stars exceeds 1k, how to display the specific number instead of 1.x k

This appears to be a duplicate of issues like https://github.com/badges/shields/issues/999 and https://github.com/badges/shields/issues/742 so I am going to close it. We don't plan to offer it in shields.io but you could implement it using a custom endpoint badge if you really wanted. Hopefully you will be able to translate.

**Closed by chris48s** 2022-05-18 18:30 UTC
