### ISSUE TITLE
Badge request: GitHub actions

### ISSUE THREAD

**Issue by xiaoxiangmoe** [badges/shields#2574] opened 2018-12-22 11:44 UTC
:clipboard: **Description**

badges for github actions 

:link: **Data**

Being consulted, this is just an idea. No API available now.

https://developer.github.com/actions/

**Comment by paulmelnikow** [comment] 2018-12-23 03:13
Some questions for you:

1. What's the problem you're wanting to solve?
2. How do you want to use github actions to solve it?
3. How would the badge be part of that?

**Comment by xiaoxiangmoe** [comment] 2018-12-24 05:03
* Q: What's the problem you're wanting to solve?
  A: Badge for unit test status and coverages in github actions.
* Q: How do you want to use github actions to solve it?
  A: I'll use github actions as runner for testing.
* Q: How would the badge be part of that?
  A: Badge will show result of testing..

**Comment by devblackops** [comment] 2018-12-30 23:09
Here is an example: https://github.com/CultureHQ/github-actions-badge

**Comment by dougnukem** [comment] 2019-03-12 20:10
@devblackops I'm using the badge from @kddeisz and it works great, they added functionality to link to github action results as well, maybe that can be added to `shields.io` (right now its a Lambda JS function).

- https://github.com/cedrickring/golang-action/blob/6fb2e21b8a312a444d7ce88ebb93783739d82f8f/README.md

[![Actions Status](https://wdp9fww0r9.execute-api.us-west-2.amazonaws.com/production/badge/cedrickring/golang-action)](https://wdp9fww0r9.execute-api.us-west-2.amazonaws.com/production/results/cedrickring/golang-action)

**Comment by gr2m** [comment] 2019-05-18 06:40
See also https://github.com/JasonEtco/action-badges

**Comment by imbsky** [comment] 2019-08-18 18:09
+1

**Comment by chris48s** [comment] 2019-08-18 19:19
It looks like the other example posted is calling a URL like https://api.github.com/repos/badges/shields/commits/master/check-suites with the header `Accept: application/vnd.github.antiope-preview+json`, e.g:

```
curl -H "Accept: application/vnd.github.antiope-preview+json" https://api.github.com/repos/badges/shields/commits/master/check-suites
```

..and then looking for a check-suite with the name "GitHub Actions". GitHub's docs on this API call say

> The API may change without advance notice during the preview period. Preview features are not supported for production use

( see https://developer.github.com/v3/checks/suites/#list-check-suites-for-a-specific-ref )

but tbh, if someone's interested in working on this, I'd be inclined to take a PR for it even though the API is beta at this stage.

**Comment by qoomon** [comment] 2019-08-19 13:29
FYI official badge api https://github.com/{github_id}/{repository}/workflows/{workflow_name}/badge.svg

**Comment by chris48s** [comment] 2019-08-19 17:14
> official badge api

How interesting..

![](https://github.com/actions/toolkit/workflows/Main%20workflow/badge.svg) https://github.com/actions/toolkit/workflows/Main%20workflow/badge.svg

Do you have a link to the docs for that, or do you have to be in the actions beta to see them? I'd be interested to read more about this.

**Comment by qoomon** [comment] 2019-08-19 21:16
Found it at reddit -> https://www.reddit.com/r/github/comments/csehoc/github_actions_official_status_badges/

**Comment by calebcartwright** [comment] 2019-08-19 21:35
I wonder if we went the SvgScraping route if we'd be able to avoid having to use tokens from the pool/hitting the throttling limits 🤔

**Comment by khakiout** [comment] 2019-08-23 15:13
> FYI official badge api [https://github.com/{github_id}/{repository}/workflows/{workflow_name}/badge.svg](https://github.com/%7Bgithub_id%7D/%7Brepository%7D/workflows/%7Bworkflow_name%7D/badge.svg)

Based on my testing, the workflow should be on the main branch for the badge to be generated. How about you?

**Comment by calebcartwright** [comment] 2019-08-25 18:56
@khakiout - I believe that is true based on what I've seen

**Comment by calebcartwright** [comment] 2019-08-25 19:00
I've opened #3899 and #3913 with two different implementations we could consider using. However, my takeaway from working on these is that any support we may potentially add for GitHub Actions to Shields in the short term would inevitably have some limitations and wouldn't be able to support certain edge cases. 

At this moment GH Actions are still pretty new/beta, and there's just not a good official/well documented approach for Shields to get the GH Actions data, so we're stuck using the undocumented/unofficial approaches.

**Comment by calebcartwright** [comment] 2019-08-25 19:42
Also if anyone is using GitHub Actions in your repos and is willing to test...

Try out your repo/workflow in the staging apps:
- https://shields-staging-pr-3898.herokuapp.com (named workflow, master branch only)
- https://shields-staging-pr-3913.herokuapp.com (by branch/ref)

**Comment by crazy-max** [comment] 2019-08-25 21:09
@calebcartwright Works fine for me on [WindowsSpyBlocker](https://github.com/crazy-max/WindowsSpyBlocker) :ok_hand:

![GitHub Actions](https://shields-staging-pr-3898.herokuapp.com/github/actions/crazy-max/WindowsSpyBlocker/build)
![GitHub Actions](https://shields-staging-pr-3913.herokuapp.com/github/actions/crazy-max/WindowsSpyBlocker/master)

**Comment by vintagesucks** [comment] 2019-08-26 11:45
@calebcartwright Works fine for me, too. 👍

[![3898](https://shields-staging-pr-3898.herokuapp.com/github/actions/vintagesucks/random-starred-repository/Build "3898")](https://github.com/vintagesucks/random-starred-repository/actions)
[![3913](https://shields-staging-pr-3913.herokuapp.com/github/actions/vintagesucks/random-starred-repository/b934554 "3913")](https://github.com/vintagesucks/random-starred-repository/actions)

**Comment by knocte** [comment] 2019-08-30 05:53
> https://github.com/{github_id}/{repository}/workflows/{workflow_name}/badge.svg

Interestingly, in my case, I had to uppercase `{workflow_name}` (even if my yml file is lower case) for this pattern to work. HTH

**Comment by Herohtar** [comment] 2019-09-01 20:42
> 
> 
> > [https://github.com/{github_id}/{repository}/workflows/{workflow_name}/badge.svg](https://github.com/%7Bgithub_id%7D/%7Brepository%7D/workflows/%7Bworkflow_name%7D/badge.svg)
> 
> Interestingly, in my case, I had to uppercase `{workflow_name}` (even if my yml file is lower case) for this pattern to work. HTH

That is incorrect; the `{workflow_name}` must match the case of your workflow's name. In your situation, your file was named `ci.yml`, but inside you had defined `name: CI`, which is why you had to use uppercase. The filename is only used if you do not specify `name:` in your YAML file.

**Comment by williamfzc** [comment] 2019-09-02 02:21
Well done. 

If you have some spaces in your workflow name, just replace them with %20.

Python package -> Python%20package

**Comment by knocte** [comment] 2019-09-02 02:37
> That is incorrect

Confirmed, my bad. Thanks

**Comment by williamfzc** [comment] 2019-09-10 06:32
OK, finally I found a official link

https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

**Comment by metaskills** [comment] 2019-09-10 10:45
Beat me to it... noticed this last night too. Maybe they same my article where I mentioned this thread too. :P Thanks y'all. https://technology.customink.com/blog/2019/09/02/from-travis-ci-to-github-actions/

**Comment by calebcartwright** [comment] 2019-09-11 22:37
Awesome thanks for sharing that link @williamfzc (and good to have confirmation that it'll only work with the default branch)

**Comment by calebcartwright** [comment] 2019-09-11 22:39
> Well done. If you have some spaces in your workflow name, just replace them with %20.
> 
> Python package -> Python%20package
> 
> But I have no idea if a '-' / '_' in it. Seems did not work.

Thanks for sharing that as well, I think that's probably a bug on my part (forgot the URL encoding). Will update that for the review app 👍

**Comment by calebcartwright** [comment] 2019-09-11 22:45
> This made me question things. Since I think you can have multiple workflows in any given branch I wonder which would be more useful. I imagine most people would come looking for branch/ref as it's closer to existing badges for other CI, but GitHub had to go and give us more features 😄

I'm of two minds on this one as well, as I can certainly see value in both use cases.

> I wonder if they will expand the API to offer branch/ref? 

IMO the challenge that we have today, given that Actions is still in a beta mode, is that there isn't an  API specifically for Actions/Workflows (at least not that we've been able to find anywhere). So at the moment we're stuck with using the Checks API which unsurprisingly does not have first class querying/filtering support on Actions specific constructs.

> Surely they have a repo where an issue could be opened requesting the API add branch/ref so that we could maybe have both options?

I'm sure that once Actions is officially launched/comes out of beta that there will be an official API as well. It never hurts to ask in the interim, though I don't personally know what the best channel/repo would be to make that request

**Comment by calebcartwright** [comment] 2019-09-11 22:49
@badges/shields-maintainers - what are others thoughts on this? It seems that there's a lot of community interest in Shields providing _some_ kind of support for GitHub Actions badges. 

IMO we could provide our own alpha/beta support for GH Actions badges via #3898 or #3913

**Comment by hugovk** [comment] 2019-09-12 04:32
> I'm sure that once Actions is officially launched/comes out of beta that there will be an official API as well. It never hurts to ask in the interim, though I don't personally know what the best channel/repo would be to make that request

Try here, I [requested a feature](https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/td-p/30678) and they said they'd take a look:

* https://github.community/t5/GitHub-Actions/bd-p/actions

**Comment by danielcompton** [comment] 2019-09-15 18:13
For the lazy among us, the incantation you're probably looking for is:

```
[![Actions Status](https://github.com/{owner}/{repo}/workflows/{workflow_name}/badge.svg)](https://github.com/{owner}/{repo}/actions)
```

which I found at https://github.com/CultureHQ/github-actions-badge.

**Comment by stevenvachon** [comment] 2019-09-20 14:53
@danielcompton that's not working for me. I'm getting a "Not Found" for https://github.com/stevenvachon/broken-link-checker/workflows/nodejs/badge.svg

**Comment by matteocontrini** [comment] 2019-09-20 15:02
@stevenvachon you need to use the name of the workflow, that you can set in the yml file

https://help.github.com/en/articles/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository

**Comment by stevenvachon** [comment] 2019-09-20 15:07
@matteocontrini thanks! That was it.

**Comment by SerafimArts** [comment] 2019-09-30 14:12
There are doubts that this functionality works as it should. At the moment, all the links on the `badge.svg` returns 404 for me.

Do you have exactly the same?

**Comment by knocte** [comment] 2019-10-01 04:13
> Do you have exactly the same?

It works for me, look at the CI badges in my project: https://github.com/knocte/geewallet

**Comment by SerafimArts** [comment] 2019-10-01 06:03
@knocte Yes, it’s working now. Maybe it was just a temporary problem.

Thx 👍

**Comment by sunsheeppoplar** [comment] 2019-10-01 21:46
Does anyone know whether or not this works on private repos?

**Comment by calebcartwright** [comment] 2019-10-01 21:50
Hi Folks - just a friendly reminder that if you have questions about GitHub's native badge for GitHub Actions/Workflows, you should probably use a different channel to pose those questions. I'd suggest going to one of the GitHub forums to try to get answer directly from GitHub. 

This thread is getting really long, with a lot of non-Shields related comments. Would like to try keep this thread focused on the OT of Shields.io support for GH Actions badges. 

Thanks!

**Comment by svoop** [comment] 2019-10-22 16:30
@calebcartwright Given the case-sensitive workflow names: It would be nice, if the actions badge implementation accepted an optional query parameter `label=` to override the name rendered on the badge. This way, you could have consistent badge labels (e.g. all lowercase) and still use different cases (or even names) for the workflows themselves.

(BTW: When an issue gets OT comments like the ones above, you can hide them by clicking on the "Hide" in the `...` menu next to each comment. Hidden comments are only collapsed, those interested can read them anyways.)

**Comment by calebcartwright** [comment] 2019-10-22 16:35
> It would be nice, if the actions badge implementation accepted an optional query parameter label= to override the name rendered on the badge

This is supported on all Shields badges, and will also be available for Shields badges for GH Actions

> BTW: When an issue gets OT comments like the ones above, you can hide them by clicking on the "Hide" in the ... menu next to each comment. Hidden comments are only collapsed, those interested can read them anyways.

Thanks @svoop, I'm aware of this but deliberately left them as-is since they contain information folks may find useful outside the Shields context.

**Comment by marketlend** [comment] 2019-11-19 23:04
> Does anyone know whether or not this works on private repos?

It certainly works on private repos!

**Comment by svoop** [comment] 2019-11-20 16:04
A lil heads-up since Actions are now out of beta.

Given the SVG from GH won't change much in the near future, I'd opt for a pragmatic "works for now" approach by just extracting the label and result from the SVG:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="101" height="20">
  <defs>
    <linearGradient id="workflow-fill" x1="50%" y1="0%" x2="50%" y2="100%">
      <stop stop-color="#444D56" offset="0%"></stop>
      <stop stop-color="#24292E" offset="100%"></stop>
    </linearGradient>
    <linearGradient id="state-fill" x1="50%" y1="0%" x2="50%" y2="100%">
      <stop stop-color="#34D058" offset="0%"></stop>
      <stop stop-color="#28A745" offset="100%"></stop>
    </linearGradient>
  </defs>
  <g fill="none" fill-rule="evenodd">
    <g font-family="&#39;DejaVu Sans&#39;,Verdana,Geneva,sans-serif" font-size="11">
      <path id="workflow-bg" d="M0,3 C0,1.3431 1.3552,0 3.02702703,0 L51,0 L51,20 L3.02702703,20 C1.3552,20 0,18.6569 0,17 L0,3 Z" fill="url(#workflow-fill)" fill-rule="nonzero"></path>
      <text fill="#010101" fill-opacity=".3">
        <tspan x="22.1981982" y="15">Test</tspan>
      </text>
      <text fill="#FFFFFF">
        <tspan x="22.1981982" y="14">Test</tspan>
      </text>
    </g>
    <g transform="translate(51)" font-family="&#39;DejaVu Sans&#39;,Verdana,Geneva,sans-serif" font-size="11">
      <path d="M0 0h46.939C48.629 0 50 1.343 50 3v14c0 1.657-1.37 3-3.061 3H0V0z" id="state-bg" fill="url(#state-fill)" fill-rule="nonzero"></path>
      <text fill="#010101" fill-opacity=".3">
        <tspan x="4" y="15">passing</tspan>
      </text>
      <text fill="#FFFFFF">
        <tspan x="4" y="14">passing</tspan>
      </text>
    </g>
    <path fill="#959DA5" d="M11 3c-3.868 0-7 3.132-7 7a6.996 6.996 0 0 0 4.786 6.641c.35.062.482-.148.482-.332 0-.166-.01-.718-.01-1.304-1.758.324-2.213-.429-2.353-.822-.079-.202-.42-.823-.717-.99-.245-.13-.595-.454-.01-.463.552-.009.946.508 1.077.718.63 1.058 1.636.76 2.039.577.061-.455.245-.761.446-.936-1.557-.175-3.185-.779-3.185-3.456 0-.762.271-1.392.718-1.882-.07-.175-.315-.892.07-1.855 0 0 .586-.183 1.925.718a6.5 6.5 0 0 1 1.75-.236 6.5 6.5 0 0 1 1.75.236c1.338-.91 1.925-.718 1.925-.718.385.963.14 1.68.07 1.855.446.49.717 1.112.717 1.882 0 2.686-1.636 3.28-3.194 3.456.254.219.473.639.473 1.295 0 .936-.009 1.689-.009 1.925 0 .184.131.402.481.332A7.011 7.011 0 0 0 18 10c0-3.867-3.133-7-7-7z"></path>
  </g>
</svg>
```

Doable, but a little tricky with regexp, quite easy though if you actually parse the XML.

**Comment by calebcartwright** [comment] 2019-11-20 16:06
@svoop - please note that this has already been done in the PR linked aboved in this thread #3898

**Comment by svoop** [comment] 2019-11-20 16:11
@calebcartwright Jeez, me, always one step behind 😄 Thanks for the hint!

**Comment by calebcartwright** [comment] 2019-11-20 16:20
no worries!

**Comment by calebcartwright** [comment] 2019-11-28 05:10
Closed via #3898

**Closed by calebcartwright** 2019-11-28 05:10 UTC
Labels: good first issue, service-badge

**Comment by calebcartwright** [comment] 2019-11-28 05:14
This feature has been implemented is now live! Thanks to @paulmelnikow for getting it shipped so quickly after the PR was merged🎉 

Some examples:
https://img.shields.io/github/workflow/status/apache/arrow/Python
![](https://img.shields.io/github/workflow/status/apache/arrow/Python)

And one with all sorts of Shields-customization goodness
https://img.shields.io/github/workflow/status/apache/arrow/Python?color=orange&label=actions&logo=github&logoColor=orange&style=for-the-badge
![](https://img.shields.io/github/workflow/status/apache/arrow/Python?color=orange&label=actions&logo=github&logoColor=orange&style=for-the-badge)

There's another issue open to track the work for implenting Job-level status badges in https://github.com/badges/shields/issues/4364 if anyone is interested in tracking that work (or implementing! ❤️)

**Comment by PyvesB** [comment] 2019-11-29 22:22
Tweet about this new badge: https://twitter.com/Shields_io/status/1200540112368611328

Like and retweet to give us more visibility! 😉

**Comment by the-j0k3r** [comment] 2020-02-27 17:26
I cant get this to work 

https://github.com/bus-stop/x-terminal/workflows/main/badge.svg

**Comment by paulmelnikow** [comment] 2020-02-27 17:35
Ah, the `name` is defined in the YML file; it doesn't come from the name of the YML file.

https://img.shields.io/github/workflow/status/bus-stop/x-terminal/CI
https://github.com/bus-stop/x-terminal/workflows/CI/badge.svg
