### ISSUE TITLE
Crowdin badges!

### ISSUE THREAD

**Issue by Albert221** [badges/shields#6154] opened 2021-02-05 17:13 UTC
:clipboard: **Description**

It would be awesome to have few Crowdin badges! Like:

- overall localized %
- number of languages (every, 100% translated?, 100% proofread?)
- localized % for a given language

:link: **Data**

I didn't find any API endpoint for stuff like that, but maybe they have some, they look like cool guys and may warmly reply to an email :)

If not the API, scrapping is also an option. The projects reside on `/project/<project-name>`, for example https://crowdin.com/project/fast-shopping which is not disallowed for scrapping: https://crowdin.com/robots.txt

:microphone: **Motivation**

I want to have cool shields in my open-source app's README!

> Love Shields? Please consider donating $10 to sustain our activities:
> 👉  https://opencollective.com/shields

I love them! I donated a little :)

**Comment by calebcartwright** [comment] 2021-02-05 17:37
> I love them! I donated a little :)

thanks :heart: going to close this as a duplicate of #4906 though

**Closed by calebcartwright** 2021-02-05 17:37 UTC
Labels: service-badge
