### ISSUE TITLE
GitHub yearly commit activity badge is flaky

### ISSUE THREAD

**Issue by paulmelnikow** [badges/shields#2704] opened 2019-01-08 20:32 UTC
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)

:beetle: **Description**

This badge shows invalid.
![https://img.shields.io/github/commit-activity/y/badges/shields.svg](https://img.shields.io/github/commit-activity/y/badges/shields.svg)

:link: **Link to the badge**

- https://img.shields.io/github/commit-activity/y/badges/shields.svg

These work:

- https://img.shields.io/github/commit-activity/4w/badges/shields.svg
- https://img.shields.io/github/commit-activity/4w/eslint/eslint.svg
- https://img.shields.io/github/commit-activity/y/eslint/eslint.svg

:bulb: **Possible Solution**

Not sure! Refactoring the service is probably a good start!

**Comment by paulmelnikow** [comment] 2019-01-08 20:32
Amazing. It was showing "invalid" a moment ago. 🤦‍♂️

**Comment by chris48s** [comment] 2019-01-08 21:11
There's something subtle going on here.. try it on a repo that hasn't been queried before it'll say invalid the first time. Then give it a moment and add `?foo=bar` to cache-bust it and it will work.

**Comment by paulmelnikow** [comment] 2019-01-08 21:35
Yea… I noticed that switching it to `.json` works too.

**Comment by MaximeAubanel** [comment] 2019-05-12 14:59
I've been dealing with this issue as well.

**Comment by paulmelnikow** [comment] 2019-05-13 04:00
You can :+1: the top post. That’s what it’s for :)

**Comment by Areso** [comment] 2019-11-19 07:16
Ran in the same problem, ?foo=bar doesn't help me

**Comment by luqmansen** [comment] 2020-03-21 04:25
Issue still randomly appearing out of nowhere, any fix for this issue?

**Comment by ikostan** [comment] 2020-03-22 03:06
Hi all. I encounter same issue here: https://github.com/ikostan/BotDetectCaptcha

**Comment by lnogueir** [comment] 2020-08-03 23:33
Any solutions to this issue?

**Comment by ltpitt** [comment] 2020-10-06 09:17
Still experiencing it today:
https://github.com/ltpitt/java-spring-cloud-drive

Thanks for your help!

**Comment by ltpitt** [comment] 2020-10-14 12:48
A short update, it works for me now.

I don't know if a fix was applied in the meantime or if it was just a matter of waiting for the sync.

**Comment by TheTechRobo** [comment] 2021-01-04 22:04
Same issue, sometimes it works, sometimes it doesn't.

And this is for monthly and weekly !

**Comment by acusti** [comment] 2021-06-28 23:51
i tried monthly, yearly, and weekly to see if i could get the badge to work with no luck. then i tried “/ four weeks” (`/4w/` in the URL) and it started working again. i notice that github seems to be caching the images and serving them from camo.githubusercontent.com (e.g. `https://camo.githubusercontent.com/4ab411a79cb82b0e7390ca57399e33fb1ea5c3e05d2e1fa00943e66754d39f7a/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f636f6d6d69742d61637469766974792f34772f6163757374692f75696b69743f7374796c653d666f722d7468652d6261646765`). my hypothesis is that the badge often shows as invalid the first time(s?) it is requested, so if that first request originates from the github service scraping the image to save it to their own server, you wind up with an invalid badge. workaround might be to load the badge manually by going directly to the image URL in your browser, refreshing until the badge no longer shows as invalid, then update the README file to point to the badge URL (not sure when github tries to fetch/cache images from readme files).

**Comment by calebcartwright** [comment] 2021-07-02 03:36
Doing some issue cleanup here to help facilitate a more focused discussion should anyone be interested in digging into this one. As a reminder to folks, please refrain from the update requests and "me too" type of comments; those aren't particularly helpful and just add noise.

There's two separate circumstances that can result in folks seeing the badge show an `invalid` message:

1. Your target repository is too new for your target time period, and you just need to wait a bit for the data to start showing up in the GitHub API
2. The badge in long-standing projects will randomly on occasion change from showing an expected message to showing `invalid`, without any explanation.

This issue is really focused on that second use case. It's true that in either case one often tweak the badge url which busts the cache, and that'll often work because the underlying issue is very temporal in nature. However, that's not a necessary step, as the badge gets corrected fairly quickly on its own (hence the reference to the flaky behavior).

We currently fetch the commit data from GitHub's [commit activity](https://docs.github.com/en/rest/reference/repos#get-the-last-year-of-commit-activity) v3 API and the root cause for the temporary `invalid` message on badges is _most_ likely that we temporarily get an unexpected HTTP response code from that endpoint.

What _would_ be helpful for anyone interested in assisting with the resolution of this issue:
* For existing/working badges (second use case from above) that suddenly see an `invalid` message, check the corresponding API response for your project and capture/share the results here (or ping us in our Discord server if you'd prefer). The API call would like something like this, with your owner and repo name replaced: https://api.github.com/repos/badges/shields/stats/commit_activity
* Evaluate whether the commit data is readily available via GitHub's v4 API (GraphQL based), and share any findings, suggested queries, etc. and consider submitting a PR to refactor the [existing service providing this badge](https://github.com/badges/shields/blob/master/services/github/github-commit-activity.service.js) to use the v4 API instead. We have various other examples of such migrations for reference and happy to help anyone interested

**Comment by chris48s** [comment] 2021-07-03 15:40
> Evaluate whether the commit data is readily available via GitHub's v4 API (GraphQL based)

Good thinking :+1:  This was not an option when this issue was first raised but I reckon this is probably the most likely path to a solution.

I think the `/stats/commit_activity` endpoint is probably slow to generate if the stats aren't cached on Github's side. If we can issue a more constrained query via the GQL api then maybe we can avoid the issue? If anyone is interested in helping resolve this, then I suspect that is the best line of attack.

**Comment by calebcartwright** [comment] 2021-08-28 00:26
Finally managed to capture this in action. This occurs when GitHub is responding to us with a 202 status code and an empty body.

I'm going to take a look at a graphql query for this, and if it looks like too big a hurdle to convert in the near future then I'd suggest we investigate checking for the 202 specifically and set the message to something like `github processing` accordingly

**Closed** 2021-08-29 17:59 UTC
Labels: bug, service-badge
