### ISSUE TITLE
GitHub Release badge with prefix filter

### ISSUE THREAD

**Issue by DAmNRelentless** [badges/shields#7082] opened 2021-09-30 05:02 UTC
:clipboard: **Description**

Another GitHub badge which shows the latest release would be nice but with a filter option.
Since releases are not grouped by branches, you will always have your latest release showing in the currently available badges.
It would be nice if there was a filter like `?prefix=whatever`.

:link: **Data**

I am not a web developer so I am not able to provide a custom endpoint for something like this and I am also not sure if there is something like this already.
At least I haven't found something.

:microphone: **Motivation**

I am developing mods for different versions of a game and the different game versions are defined by different branches of the repository.
The difference when it comes to releases/tags, is the tag prefix. If the game version is 1.16, all the tags created from this branch are prefixed with `v1.16-` and the same thing for other game versions.

The badge would be handy to have different latest release badges for the readmes of the different branches.

**Comment by calebcartwright** [comment] 2021-10-01 04:13
Thanks for reaching out, but going to close as a duplicate of #6275 and #6253

**Closed by calebcartwright** 2021-10-01 04:13 UTC
Labels: service-badge
