### ISSUE TITLE
Allowing on-prem azure devops repos

### ISSUE THREAD

**Issue by powerlimit** [badges/shields#10243] opened 2024-06-10 13:49 UTC
:clipboard: **Description**

Hello,
the current azure service seems to be hardwired to work only with the public domain https://dev.azure.com. I looked into extending the service to accept an azure base url. But this doesn't seem easily possible, a couple of other services allow baseurls to be supplied. I wasn't able to fiddle one in for azure myself :'( Perhaps someone better at js would have an easier time?

Cheers,
Manuel

**Comment by calebcartwright** [comment] 2024-06-11 20:31
I'm actually going to close this as a duplicate of #3429 

In particular I'd point back to https://github.com/badges/shields/issues/3429#issuecomment-489795661 and the second point within relative to API compatibility. We do have precedent for this with SonarCloud vs. SonarQube, but I know the API surface for Azure DevOps Server has evolved enough over the years that I'd still strongly suggest we start with some form of versioning scheme

**Closed by calebcartwright** 2024-06-11 20:31 UTC
Labels: good first issue, service-badge
