### ISSUE TITLE
Some badges are not working

### ISSUE THREAD

**Issue by MD-AZMAL** [badges/shields#1748] opened 2018-06-25 09:44 UTC
I have only two badges (license and downloads) on my repo and both are not working?
Though when i visit the link directly it takes way more time but at least loads successfully :|
Any fixes or alternatives?

**Comment by chris48s** [comment] 2018-06-25 18:11
If they time out when you view them on GitHub but work when you visit the URL directly this means the badge is taking >4 seconds to load when GitHub's camo proxy tries to load it and it gives up. I suspect this is a dupe of https://github.com/badges/shields/issues/1568 but sometimes it is related to a particular upstream service taking a long time to respond.

**Comment by RussKie** [comment] 2018-06-28 08:20
Got the same problem
![image](https://user-images.githubusercontent.com/4403806/42022179-ef08290c-7aff-11e8-8489-1d227dc89079.png)

**Comment by MD-AZMAL** [comment] 2018-06-28 09:12
![screenshot from 2018-06-28 20-11-02](https://user-images.githubusercontent.com/33421347/42025067-57bbc388-7ae1-11e8-848e-c987b0d69039.png)

even higher load time in my case

**Comment by RedSparr0w** [comment] 2018-06-28 09:22
Closing as dupe of #1568 if we could move the conversation over there 😄

_Feel free to reopen if you think this may be unrelated._

**Closed by RedSparr0w** 2018-06-28 09:22 UTC

**Comment by MD-AZMAL** [comment] 2018-06-28 09:36
@RedSparr0w cool! no problem will go to #1568 if necessary 😃
