### ISSUE TITLE
Gratipay badge doesn't work for teams

### ISSUE THREAD

**Issue by joeyespo** [badges/shields#563] opened 2015-11-13 19:48 UTC
It works for individuals (if you exclude the `~` from the URL):

```markdown
![Example individual](https://img.shields.io/gratipay/joeyespo.svg)
```

![Example individual](https://img.shields.io/gratipay/joeyespo.svg)

But shows "anonymous" for teams:

```markdown
![Example team](https://img.shields.io/gratipay/grip.svg)
```

![Example team](https://img.shields.io/gratipay/grip.svg)

Related issues:
- [API for Team receiving amount](https://github.com/gratipay/gratipay.com/issues/3726)
- [Gratipay badge no longer works](https://github.com/badges/shields/issues/520)

**Comment by espadrine** [comment] 2015-11-14 13:12
Thanks for raising the issue! This is a duplicate of https://github.com/badges/shields/issues/520. We no longer have an API for that. We raised the issue to Gratipay here: https://github.com/gratipay/gratipay.com/issues/3726.

**Closed by espadrine** 2015-11-14 13:12 UTC
