### ISSUE TITLE
Pypi downloads badge inaccessible

### ISSUE THREAD

**Issue by sigma67** [badges/shields#5397] opened 2020-08-06 12:06 UTC
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

Pypi download badges are marked as inaccessible.

:link: Link

![](https://camo.githubusercontent.com/a099a631b488947ede576ddb7d95851f3c6395a2/68747470733a2f2f696d672e736869656c64732e696f2f707970692f646d2f79746d757369636170693f7374796c653d666c61742d737175617265)

Seems all pypi download badges are affected, regardless of package and period.

:bulb: **Possible Solution**

**Comment by chris48s** [comment] 2020-08-06 17:33
This is an issue with https://pypistats.org/
Lets call this a dupe of https://github.com/badges/shields/issues/5371 even though its a new error

**Closed by chris48s** 2020-08-06 17:33 UTC
Labels: question
