### ISSUE TITLE
Crowdin badges

### ISSUE THREAD

**Issue by Albert221** [badges/shields#6155] opened 2021-02-05 17:14 UTC
:clipboard: **Description**

It would be awesome to have few Crowdin badges! Like:

- overall localized %
- number of languages (every, 100% translated?, 100% proofread?)
- localized % for a given language

:link: **Data**

I didn't find any API endpoint for stuff like that, but maybe they have some, they look like cool guys and may warmly reply to an email :)

If not the API, scrapping is also an option. The projects reside on `/project/<project-name>`, for example https://crowdin.com/project/fast-shopping which is not disallowed for scrapping: https://crowdin.com/robots.txt

:microphone: **Motivation**

I want to have cool Crowdin badges in my open-source app's README!

> Love Shields? Please consider donating $10 to sustain our activities:
> 👉  https://opencollective.com/shields

I love them! I donated a little something :)

**Comment by calebcartwright** [comment] 2021-02-05 17:36
Apart from an exclamation mark in the issue title, this seems like quite a literal dupe of #6154 so going to close...

**Closed by calebcartwright** 2021-02-05 17:36 UTC
Labels: service-badge

**Comment by Albert221** [comment] 2021-02-05 17:38
Oh, sorry!!! My Chromium crashed when I was submitting the issue and I thought it didn't submit properly. I'll better check twice next time, sorry!

**Comment by calebcartwright** [comment] 2021-02-05 17:39
no worries!

**Comment by ElectronicsArchiver** [comment] 2022-08-08 12:49
Any progress on this?

**Comment by chris48s** [comment] 2022-08-08 20:18
There are some more notes on this in https://github.com/badges/shields/issues/4906 but due to the constraints discussed there I can't see us adding a native badge for CrowdIn.
