### ISSUE TITLE
Website JavaScript errors

### ISSUE THREAD

**Issue by ygoe** [badges/shields#3188] opened 2019-03-10 21:42 UTC
Are you experiencing an issue with...

- [x] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [gh-badges NPM package](https://www.npmjs.com/package/gh-badges)

:beetle: **Description**

When I search for a package by entering its URL, the page gets blank and dies. There are multiple JavaScript errors visible in the browser console. Firefox and Chrome are affected. The page is unusable.

I'm not including the details because you can easily check that yourself and get all the details you need.

Ad blocker disabled, no other browser extensions affecting the page.

:link: **Link to the badge**

:bulb: **Possible Solution**

**Comment by calebcartwright** [comment] 2019-03-10 22:45
Thanks @ygoe. This is a duplicate of #3033 so going to close this one

**Closed by calebcartwright** 2019-03-10 22:45 UTC
