### ISSUE TITLE
npm start front end errors on windows

### ISSUE THREAD

**Issue by RedSparr0w** [badges/shields#3208] opened 2019-03-17 21:13 UTC
Are you experiencing an issue with...

- [x] My own instance

## :beetle: **Description**

Tested on `Windows 10` & `Windows Server 2008`
HEAD @ https://github.com/badges/shields/commit/e43593e3bbfaaa2e519b1e97560645f92048171b
`gatsby-plugin-page-creator@2.0.8`

When running `npm start`, the frontend errors with:
```
ReferenceError: describe is not defined
Module../frontend/pages/endpoint.spec.js
G:/shields/frontend/pages/endpoint.spec.js:7
```
<details>
<summary>More Details/Image:</summary>

![image](https://user-images.githubusercontent.com/7288322/54497897-10916780-4965-11e9-8ab8-7a0a5026ef0b.png)
</details>

**Comment by chris48s** [comment] 2019-03-17 21:38
Cheers for having a go at reproducing this. FWIW I also have `gatsby-plugin-page-creator@2.0.8` and can't reproduce running on linux.

Nyc is a test coverage tool, so I think those settings in `.nycrc-frontend.json` are only about what we're measuring test coverage on, not what we include in the front-end build. I think `gatsby-plugin-page-creator` should be excluding the `.spec.js` files for us: https://www.gatsbyjs.org/packages/gatsby-plugin-page-creator/ I don't think we explicitly define includes/excludes.

**Comment by RedSparr0w** [comment] 2019-03-17 21:45
Ah I see, that is strange it's still including these 2 files (`index.spec.js`, `endpoint.spec.js`)
I'll have a look if I can see any issues open on their repo in regards to this.

**Comment by paulmelnikow** [comment] 2019-03-18 20:10
If there isn't an easy way to provide an exclude path, we could remove the plugin and create the couple auto-created pages manually in `gatsby-node.js`.

**Comment by RedSparr0w** [comment] 2019-03-19 21:22
Seems there is no way to manually exclude files yet, But there is a PR (https://github.com/gatsbyjs/gatsby/pull/11304).

Although i'm not sure if that would help as the files are already supposed to be excluded.
It seems like it might be something to do with micromatch as if I add an `_` to the start of the files, they are excluded as expected.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/validate-path.js#L23-L28

**Comment by paulmelnikow** [comment] 2019-03-20 21:59
Hmm… that's very strange.

I played around with this a bit and confirmed this code prints `true` twice on my machine:

```js
const mm = require('micromatch')

const filePath = 'endpoint.spec.js'

const testPatterns = [
  `**/__tests__/**/*.(js|ts)?(x)`,
  `**/(*.)+(spec|test).(js|ts)?(x)`,
]

console.log('mm.isMatch', mm.isMatch(filePath, testPatterns))

const testFileRegexes = [
  /\/__tests__\/.+?\.(js|ts)x?$/,
  /\.(spec|test)\.(js|ts)x?$/
]

console.log('other', testFileRegexes.some(regex => Boolean(regex.test(filePath))))
```

I imagine that will be true on Windows as well. Want to give that a shot to make sure?

It could be that `filePath` is getting an incompatible value on your machine. On mine, these are the values:

```
endpoint.js
endpoint.spec.js
index.js
index.spec.js
```

**Comment by RedSparr0w** [comment] 2019-03-20 23:49
Yup I also got `true` for both of those,

I changed [this file](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/validate-path.js#L9-L14) to use:
```javascript
function isTestFile(filePath) {
  const testPatterns = [
    `**/__tests__/**/*.(js|ts)?(x)`,
    `**/(*.)+(spec|test).(js|ts)?(x)`,
  ]

  const isMatch = mm.isMatch(filePath, testPatterns);
  console.log('filePath:', filePath, '\nmm.isMatch:', isMatch);
  return isMatch;
}
```
and this was my output:
```command
[frontend] filePath: ../../../G:/shields/frontend/pages/endpoint.js
[frontend] mm.isMatch: false
[frontend] filePath: ../../../G:/shields/frontend/pages/endpoint.spec.js
[frontend] mm.isMatch: false
[frontend] filePath: ../../../G:/shields/frontend/pages/index.js
[frontend] mm.isMatch: false
[frontend] filePath: ../../../G:/shields/frontend/pages/index.spec.js
[frontend] mm.isMatch: false
```
This almost makes sense, as it should include the folder names in case they contain `__tests__`.
<details>
<summary>But it seems `micromatch` can't handle having `../../../` at the beginning of the string.</summary>

```javascript
const mm = require('micromatch')

const testPatterns = [
  `**/__tests__/**/*.(js|ts)?(x)`,
  `**/(*.)+(spec|test).(js|ts)?(x)`,
]

const testFileRegexes = [
  /\/__tests__\/.+?\.(js|ts)x?$/,
  /\.(spec|test)\.(js|ts)x?$/
]

let filePath;

filePath = '../../../G:/shields/frontend/pages/endpoint.spec.js'
console.log('filePath:', filePath)
console.log('mm.isMatch:', mm.isMatch(filePath, testPatterns))
console.log('other:', testFileRegexes.some(regex => Boolean(regex.test(filePath))))

console.log('-----------------------------------')
filePath = 'G:/shields/frontend/pages/endpoint.spec.js'
console.log('filePath:', filePath)
console.log('mm.isMatch:', mm.isMatch(filePath, testPatterns))
console.log('other:', testFileRegexes.some(regex => Boolean(regex.test(filePath))))

console.log('-----------------------------------')
filePath = '../../../shields/frontend/pages/endpoint.spec.js'
console.log('filePath:', filePath)
console.log('mm.isMatch:', mm.isMatch(filePath, testPatterns))
console.log('other:', testFileRegexes.some(regex => Boolean(regex.test(filePath))))
```
```command
filePath: ../../../G:/shields/frontend/pages/endpoint.spec.js
mm.isMatch: false
other: true
-----------------------------------
filePath: G:/shields/frontend/pages/endpoint.spec.js
mm.isMatch: true
other: true
-----------------------------------
filePath: ../../../shields/frontend/pages/endpoint.spec.js
mm.isMatch: false
other: true
```
</details>

**Comment by paulmelnikow** [comment] 2019-03-21 01:53
The `../` don't make sense to me, that seems almost certainly a bug.

We're specifying the path like this:

https://github.com/badges/shields/blob/4f5268aa0fe0ea04a1bf17bb69196ebec8a0e2e7/gatsby-config.js#L14

Can you see what `__dirname` is? I highly doubt it would have `../` in it, though just wondering if it is partly our problem, or entirely a Gatsby issue.

**Comment by RedSparr0w** [comment] 2019-03-21 02:54
Looks like the change is happening [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/gatsby-node.js#L85):
```http
pagesDirectory: G:\shields/frontend/pages
filePath: G:/shields/frontend/pages/endpoint.js
modifiedPath: ../../../G:/shields/frontend/pages/endpoint.js
//modifiedPath = systemPath.posix.relative(pagesDirectory, filePath)
```

Haven't had a chance to look into why yet though.

**Comment by paulmelnikow** [comment] 2019-03-21 16:04
`G:\shields/frontend/pages` is a sort of frankenstein. What if we change `path` in our config to wither `frontend/pages` or `require('path').join(__dirname, 'frontend', 'pages')`? I'm curious which of those work. I _think_ I got `_dirname` from some documentation, and if that's the case I can try to make some doc updates…

What I guess is still strange is that the messed-up path is allowing gatsby-plugin-page-creator to find the files, but is not properly rejecting them. I wonder if calling `systemPath.posix.abspath()` on the result would properly canonicalize it.

**Comment by Warped2713** [comment] 2019-03-21 20:51
While working on the add-ignore-option PR (gatsbyjs/gatsby#11304) I noticed that the paths being passed to micromatch had extra leading `../` (on Windows) and resolved this by applying `slash()` to pagesDirectory in gatsby-plugin-page-creator:

https://github.com/gatsbyjs/gatsby/blob/f22850dd15ddd921c1f164f33e7ab148aba67c1a/packages/gatsby-plugin-page-creator/src/gatsby-node.js#L52-L68

**Comment by RedSparr0w** [comment] 2019-03-21 22:10
It looks like there is no easy way around this and will need to be fixed upstream.

I've tried the following all with mixed results:

<details>
<summary><code>${__dirname}/frontend/pages</code> (current)</summary>

### Output:
```http
--standard filePath--
pagesDirectory: G:\shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/endpoint.js
modifiedPath: ../../../G:/shields/frontend/pages/endpoint.js
microMatch: false

--standard filePath--
pagesDirectory: G:\shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/endpoint.spec.js
modifiedPath: ../../../G:/shields/frontend/pages/endpoint.spec.js
microMatch: false

--standard filePath--
pagesDirectory: G:\shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/index.js
modifiedPath: ../../../G:/shields/frontend/pages/index.js
microMatch: false

--standard filePath--
pagesDirectory: G:\shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/index.spec.js
modifiedPath: ../../../G:/shields/frontend/pages/index.spec.js
microMatch: false
```
</details>

<details>
<summary><code>${__dirname.replace(/\\/g, '/')}/frontend/pages</code></summary>

When done this way, it seems [chokidar](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-page-creator/src/gatsby-node.js#L59-L66) detects the files as new files because it uses windows style slashes `\`, and then we get the `../` problem again.
This means that micromatch doesn't match these files so they are added to the directory:

### Output:
```http
--standard filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/endpoint.js
modifiedPath: endpoint.js
microMatch: false

--standard filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/endpoint.spec.js
modifiedPath: endpoint.spec.js
microMatch: true

--standard filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/index.js
modifiedPath: index.js
microMatch: false

--standard filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:/shields/frontend/pages/index.spec.js
modifiedPath: index.spec.js
microMatch: true

--chokidar filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:\shields\frontend\pages\endpoint.js
modifiedPath: ../../../../G:\shields\frontend\pages\endpoint.js
microMatch: false

--chokidar filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:\shields\frontend\pages\endpoint.spec.js
modifiedPath: ../../../../G:\shields\frontend\pages\endpoint.spec.js
microMatch: false

--chokidar filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:\shields\frontend\pages\index.js
modifiedPath: ../../../../G:\shields\frontend\pages\index.js
microMatch: false

--chokidar filePath--
pagesDirectory: G:/shields/frontend/pages
baseFilePath: G:\shields\frontend\pages\index.spec.js
modifiedPath: ../../../../G:\shields\frontend\pages\index.spec.js
microMatch: false
```
</details>

<details>
<summary><code>require('path').join(__dirname, 'frontend', 'pages')</code></summary>

Uses windows style slashes `\` which seems to add the `../` to the start again.

### Output:
```http
--standard filePath--
pagesDirectory: G:\shields\frontend\pages
baseFilePath: G:/shields/frontend/pages/endpoint.js
modifiedPath: ../G:/shields/frontend/pages/endpoint.js
microMatch: false

--standard filePath--
pagesDirectory: G:\shields\frontend\pages
baseFilePath: G:/shields/frontend/pages/endpoint.spec.js
modifiedPath: ../G:/shields/frontend/pages/endpoint.spec.js
microMatch: false

--standard filePath--
pagesDirectory: G:\shields\frontend\pages
baseFilePath: G:/shields/frontend/pages/index.js
modifiedPath: ../G:/shields/frontend/pages/index.js
microMatch: false

--standard filePath--
pagesDirectory: G:\shields\frontend\pages
baseFilePath: G:/shields/frontend/pages/index.spec.js
modifiedPath: ../G:/shields/frontend/pages/index.spec.js
microMatch: false
```
</details>

<details>
<summary>notes</summary>

`--standard filePath--` refers to the files object.
`--chokidar filePath--` refers to the chokidar filepath.
`pagesDirectory` is the path we provide.
`baseFilePath` is the `standard/chokidar filePath`.
`modifiedPath` is what `systemPath.posix.relative` returns.
`microMatch` is if it matched as a test file or not.
</details>

**Comment by paulmelnikow** [comment] 2019-03-21 22:38
> I wonder if calling `systemPath.posix.abspath()` on the result would properly canonicalize it.

Any luck with this?

**Comment by RedSparr0w** [comment] 2019-03-21 23:06
It looks like @Warped2713 PR is definitely the best solution for this, I didn't originally realize it also fixed this problem
👍

`systemPath.posix.resolve()` does convert it to `G:/shields/frontend/pages/index.spec.js`.
But looking over it again, we do only want to check against the relative path from the base folder for `__test__`.

**Comment by paulmelnikow** [comment] 2019-03-21 23:27
Hey @Warped2713 I'm going to leave you a comment in that PR :)

**Comment by paulmelnikow** [comment] 2019-03-26 01:36
Looks like this will be merged shortly! Thank you so so much @Warped2713!

Not sure if you might be interested in working on Shields, though we are planning some big improvements to the frontend, and it'd be great to have help! (#1899 #2846)

**Comment by Warped2713** [comment] 2019-03-27 02:01
It's merged! 🎉 

And sure, I can look into some of the Shields issues. Looks nifty.

**Comment by paulmelnikow** [comment] 2019-03-27 15:40
If I can help carve out some interesting work, hit me up! There is lots to do!

**Closed** 2019-03-27 20:55 UTC
Labels: developer-experience, frontend
