### ISSUE TITLE
[Badge Request] & [Feature Request]: Add Logos from URL of SVG

### ISSUE THREAD

**Issue by chrimaho** [badges/shields#8843] opened 2023-01-24 05:10 UTC
---

## :microphone: Motivation

I want to be able to quickly and easily add new logo's to my shields. These can and should be in the raw form of a SVG icon somewhere on the internet, and should be able to be easily linked through the badge URL to pull through the SVG data from the source.

---

## :clipboard: Description

As documented [here](https://shields.io/#:~:text=Insert%20one%20of%20the%20named%20logos%20from%20(bitcoin%2C%20dependabot%2C%20gitlab%2C%20npm%2C%20paypal%2C%20serverfault%2C%20stackexchange%2C%20superuser%2C%20telegram%2C%20travis)%20or%20simple%2Dicons.%20Simple%2Dicons%20are%20referenced%20using%20icon%20slugs%20which%20can%20be%20found%20on%20the%20simple%2Dicons%20site%20or%20in%20the%20slugs.md%20file%20in%20the%20simple%2Dicons%20repository.), we can currently add icons which are existing in the [simple-icons](https://simpleicons.org/) library:

> Insert one of the named logos from (bitcoin, dependabot, gitlab, npm, paypal, serverfault, stackexchange, superuser, telegram, travis) or [simple-icons](https://simpleicons.org/). Simple-icons are referenced using icon slugs which can be found on the simple-icons site or in the [slugs.md file](https://github.com/simple-icons/simple-icons/blob/develop/slugs.md) in the simple-icons repository.

And as documented [here](https://shields.io/#:~:text=Insert%20custom%20logo%20image%20(%E2%89%A5%2014px%20high).%20There%20is%20a%20limit%20on%20the%20total%20size%20of%20request%20headers%20we%20can%20accept%20(8192%20bytes).%20From%20a%20practical%20perspective%2C%20this%20means%20the%20base64%2Dencoded%20image%20text%20is%20limited%20to%20somewhere%20slightly%20under%208192%20bytes%20depending%20on%20the%20rest%20of%20the%20request%20header.), it is possible to add custom logos using [base-64](https://en.wikipedia.org/wiki/Base64) encoding:

> Insert custom logo image (≥ 14px high). There is a limit on the total size of request headers we can accept (8192 bytes). From a practical perspective, this means the base64-encoded image text is limited to somewhere slightly under 8192 bytes depending on the rest of the request header.

However, this approach has a few issues:

1. The Base64-encoded image cannot have it's colour changed with the `logoColor=` element of the URL
2. If the Base64-encoded image is too large, it will not render
3. As documented on the [simple-icons CONTRIBUTING page](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md), they _only_ include _popular_ icons, and _do not_ include icons that are:
    - Symbols (flags, banners, etc)
    - Sports clubs
    - Universities or educational institutions
    - plus some other niche restrictions

Therefore, leading to the issue whereby if I wanted to include a simple home ( [<img width="20px" src="https://raw.githubusercontent.com/chrimaho/simple-icons/home/icons/home.svg"></img>](https://github.com/chrimaho/simple-icons/blob/home/icons/home.svg) ) or globe ( [<img width="20px" src="https://raw.githubusercontent.com/chrimaho/simple-icons/globe/icons/globe.svg"></img>](https://github.com/chrimaho/simple-icons/blob/globe/icons/globe.svg) ) icon (or any other icon freely available on the open source), in order to create a super simple badge like this ![](https://img.shields.io/static/v1?style=flat&label=+&color=grey&logoColor=black&labelColor=gainsboro&message=Website&logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+R2xvYmU8L3RpdGxlPjxwYXRoIGQ9Ik0xMiAwYTEyIDEyIDAgMSAwIDAgMjQgMTIgMTIgMCAwIDAgMC0yNFpNMS41NCAxMi43NWgzLjc0Yy4wNSAxLjQuMjUgMi42NS41NCAzLjc1aC0zLjNjLS41NS0xLjE4LS44OS0yLjQ1LS45OC0zLjc1Wk0xMi43NSA2VjEuNjZjLjcuNTIgMi4yNSAxLjg3IDMuMzIgNC4zNWgtMy4zMlY2Wm0zLjg4IDEuNWMuMzIgMS4wOC41MyAyLjMyLjYgMy43NWgtNC40OFY3LjVoMy44OFpNMTAuOSAxLjkybC4zNC0uMjZWNkg3LjkyYy40LS45Ljg2LTEuNjcgMS4zLTIuMjguNjItLjgzIDEuMjMtMS40MyAxLjctMS44Wm0uMzQgNS41OHYzLjc1SDYuNzhjLjA2LTEuNDMuMjgtMi42Ny42LTMuNzVoMy44N1ptLTUuOTcgMy43NUgxLjU0Yy4xLTEuMzQuNDQtMi42Ljk5LTMuNzVoMy4yOWMtLjMgMS4xLS40OSAyLjM2LS41NCAzLjc1Wm0xLjUgMS41aDQuNDd2My43NUg3LjM3YTE1LjQyIDE1LjQyIDAgMCAxLS42LTMuNzVoLjAxWk0xMS4yNSAxOHY0LjM0Yy0uNy0uNTItMi4yNS0xLjg3LTMuMzItNC4zNGgzLjMyWm0xLjg0IDQuMDgtLjM0LjI2VjE4aDMuMzNjLS40LjktLjg1IDEuNjUtMS4zMSAyLjI3LS40OS42Ny0xLjA1IDEuMjctMS42OCAxLjh2LjAxWm0tLjM0LTUuNTh2LTMuNzVoNC40N2ExNS43IDE1LjcgMCAwIDEtLjYgMy43NWgtMy44N1ptNS45Ny0zLjc1aDMuNzRjLS4xIDEuMy0uNDMgMi41Ny0uOTkgMy43NWgtMy4yOWMuMy0xLjEuNDktMi4zNi41NC0zLjc1Wm0wLTEuNWExNy4wMyAxNy4wMyAwIDAgMC0uNTQtMy43NWgzLjNjLjU0IDEuMTUuODggMi40MS45OCAzLjc1aC0zLjc0Wk0yMC42IDZoLTIuOTJhMTMuMzYgMTMuMzYgMCAwIDAtMi4zMy0zLjk0YzIuMTUuNzIgMy45OCAyLjEyIDUuMjUgMy45NFpNOC42NSAyLjA2Yy0xIDEuMTctMS43OSAyLjUtMi4zMyAzLjk0SDMuMzlhMTAuNTIgMTAuNTIgMCAwIDEgNS4yNi0zLjk0Wk0zLjQgMThoMi45MmMuNjUgMS43MSAxLjUyIDMgMi4zMiAzLjk0QTEwLjUyIDEwLjUyIDAgMCAxIDMuNCAxOFptMTEuOTUgMy45NGMxLTEuMTcgMS43OS0yLjUgMi4zMy0zLjk0aDIuOTJhMTAuNTIgMTAuNTIgMCAwIDEtNS4yNSAzLjk0WiIvPjwvc3ZnPg==), I need to do the following:

1. Fetch the raw SVG from the source
3. Manually manipulate it to fit my purposes (I tend to use [boxy-svg.com](https://boxy-svg.com/))
4. Convert it from SVG to Base-64 (I tend to use [base64.guru](https://base64.guru/converter/encode/image/svg))
5. Ass it to the shields.io URL as a whopping great big base-64 string  eg:

`https://img.shields.io/static/v1?style=flat&label=+&color=grey&logoColor=black&labelColor=gainsboro&message=Website&logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+R2xvYmU8L3RpdGxlPjxwYXRoIGQ9Ik0xMiAwYTEyIDEyIDAgMSAwIDAgMjQgMTIgMTIgMCAwIDAgMC0yNFpNMS41NCAxMi43NWgzLjc0Yy4wNSAxLjQuMjUgMi42NS41NCAzLjc1aC0zLjNjLS41NS0xLjE4LS44OS0yLjQ1LS45OC0zLjc1Wk0xMi43NSA2VjEuNjZjLjcuNTIgMi4yNSAxLjg3IDMuMzIgNC4zNWgtMy4zMlY2Wm0zLjg4IDEuNWMuMzIgMS4wOC41MyAyLjMyLjYgMy43NWgtNC40OFY3LjVoMy44OFpNMTAuOSAxLjkybC4zNC0uMjZWNkg3LjkyYy40LS45Ljg2LTEuNjcgMS4zLTIuMjguNjItLjgzIDEuMjMtMS40MyAxLjctMS44Wm0uMzQgNS41OHYzLjc1SDYuNzhjLjA2LTEuNDMuMjgtMi42Ny42LTMuNzVoMy44N1ptLTUuOTcgMy43NUgxLjU0Yy4xLTEuMzQuNDQtMi42Ljk5LTMuNzVoMy4yOWMtLjMgMS4xLS40OSAyLjM2LS41NCAzLjc1Wm0xLjUgMS41aDQuNDd2My43NUg3LjM3YTE1LjQyIDE1LjQyIDAgMCAxLS42LTMuNzVoLjAxWk0xMS4yNSAxOHY0LjM0Yy0uNy0uNTItMi4yNS0xLjg3LTMuMzItNC4zNGgzLjMyWm0xLjg0IDQuMDgtLjM0LjI2VjE4aDMuMzNjLS40LjktLjg1IDEuNjUtMS4zMSAyLjI3LS40OS42Ny0xLjA1IDEuMjctMS42OCAxLjh2LjAxWm0tLjM0LTUuNTh2LTMuNzVoNC40N2ExNS43IDE1LjcgMCAwIDEtLjYgMy43NWgtMy44N1ptNS45Ny0zLjc1aDMuNzRjLS4xIDEuMy0uNDMgMi41Ny0uOTkgMy43NWgtMy4yOWMuMy0xLjEuNDktMi4zNi41NC0zLjc1Wm0wLTEuNWExNy4wMyAxNy4wMyAwIDAgMC0uNTQtMy43NWgzLjNjLjU0IDEuMTUuODggMi40MS45OCAzLjc1aC0zLjc0Wk0yMC42IDZoLTIuOTJhMTMuMzYgMTMuMzYgMCAwIDAtMi4zMy0zLjk0YzIuMTUuNzIgMy45OCAyLjEyIDUuMjUgMy45NFpNOC42NSAyLjA2Yy0xIDEuMTctMS43OSAyLjUtMi4zMyAzLjk0SDMuMzlhMTAuNTIgMTAuNTIgMCAwIDEgNS4yNi0zLjk0Wk0zLjQgMThoMi45MmMuNjUgMS43MSAxLjUyIDMgMi4zMiAzLjk0QTEwLjUyIDEwLjUyIDAgMCAxIDMuNCAxOFptMTEuOTUgMy45NGMxLTEuMTcgMS43OS0yLjUgMi4zMy0zLjk0aDIuOTJhMTAuNTIgMTAuNTIgMCAwIDEtNS4yNSAzLjk0WiIvPjwvc3ZnPg==`

And before you ask the question, yes I have already asked [simple-icons](https://github.com/simple-icons/simple-icons) to add these icons... And they were rejected.<br>See examples:

- https://github.com/simple-icons/simple-icons/pull/8210
- https://github.com/simple-icons/simple-icons/pull/8206
- https://github.com/simple-icons/simple-icons/pull/8208
- https://github.com/simple-icons/simple-icons/pull/8207

---

## :bulb: Idea

My feature idea would be to enhance the `logo=` element of the URL to enable it to receive _either_:
1. logo name (already implemented :white_check_mark:), or
2. base-64 encoding of image (already implemented :white_check_mark:), or
3. url pointing to raw SVG image (my suggestion :+1:)

This would be that (using the above example), instead of this huge mess:

`https://img.shields.io/static/v1?style=flat&label=+&color=grey&logoColor=black&labelColor=gainsboro&message=Website&logo=data:image/svg+xml;base64,PHN2ZyByb2xlPSJpbWciIHZpZXdCb3g9IjAgMCAyNCAyNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48dGl0bGU+R2xvYmU8L3RpdGxlPjxwYXRoIGQ9Ik0xMiAwYTEyIDEyIDAgMSAwIDAgMjQgMTIgMTIgMCAwIDAgMC0yNFpNMS41NCAxMi43NWgzLjc0Yy4wNSAxLjQuMjUgMi42NS41NCAzLjc1aC0zLjNjLS41NS0xLjE4LS44OS0yLjQ1LS45OC0zLjc1Wk0xMi43NSA2VjEuNjZjLjcuNTIgMi4yNSAxLjg3IDMuMzIgNC4zNWgtMy4zMlY2Wm0zLjg4IDEuNWMuMzIgMS4wOC41MyAyLjMyLjYgMy43NWgtNC40OFY3LjVoMy44OFpNMTAuOSAxLjkybC4zNC0uMjZWNkg3LjkyYy40LS45Ljg2LTEuNjcgMS4zLTIuMjguNjItLjgzIDEuMjMtMS40MyAxLjctMS44Wm0uMzQgNS41OHYzLjc1SDYuNzhjLjA2LTEuNDMuMjgtMi42Ny42LTMuNzVoMy44N1ptLTUuOTcgMy43NUgxLjU0Yy4xLTEuMzQuNDQtMi42Ljk5LTMuNzVoMy4yOWMtLjMgMS4xLS40OSAyLjM2LS41NCAzLjc1Wm0xLjUgMS41aDQuNDd2My43NUg3LjM3YTE1LjQyIDE1LjQyIDAgMCAxLS42LTMuNzVoLjAxWk0xMS4yNSAxOHY0LjM0Yy0uNy0uNTItMi4yNS0xLjg3LTMuMzItNC4zNGgzLjMyWm0xLjg0IDQuMDgtLjM0LjI2VjE4aDMuMzNjLS40LjktLjg1IDEuNjUtMS4zMSAyLjI3LS40OS42Ny0xLjA1IDEuMjctMS42OCAxLjh2LjAxWm0tLjM0LTUuNTh2LTMuNzVoNC40N2ExNS43IDE1LjcgMCAwIDEtLjYgMy43NWgtMy44N1ptNS45Ny0zLjc1aDMuNzRjLS4xIDEuMy0uNDMgMi41Ny0uOTkgMy43NWgtMy4yOWMuMy0xLjEuNDktMi4zNi41NC0zLjc1Wm0wLTEuNWExNy4wMyAxNy4wMyAwIDAgMC0uNTQtMy43NWgzLjNjLjU0IDEuMTUuODggMi40MS45OCAzLjc1aC0zLjc0Wk0yMC42IDZoLTIuOTJhMTMuMzYgMTMuMzYgMCAwIDAtMi4zMy0zLjk0YzIuMTUuNzIgMy45OCAyLjEyIDUuMjUgMy45NFpNOC42NSAyLjA2Yy0xIDEuMTctMS43OSAyLjUtMi4zMyAzLjk0SDMuMzlhMTAuNTIgMTAuNTIgMCAwIDEgNS4yNi0zLjk0Wk0zLjQgMThoMi45MmMuNjUgMS43MSAxLjUyIDMgMi4zMiAzLjk0QTEwLjUyIDEwLjUyIDAgMCAxIDMuNCAxOFptMTEuOTUgMy45NGMxLTEuMTcgMS43OS0yLjUgMi4zMy0zLjk0aDIuOTJhMTAuNTIgMTAuNTIgMCAwIDEtNS4yNSAzLjk0WiIvPjwvc3ZnPg==`

It would be simplified to be like this:

`https://img.shields.io/static/v1?style=flat&label=+&color=grey&logoColor=black&labelColor=gainsboro&message=Website&logo=https://upload.wikimedia.org/wikipedia/commons/c/c4/Globe_icon.svg`

Which I'm sure you can appreciate is a heck of a lot cleaner and simpler to handle.

But it currently does not work: ![](https://img.shields.io/static/v1?style=flat&label=+&color=grey&logoColor=black&labelColor=gainsboro&message=Website&logo=https://upload.wikimedia.org/wikipedia/commons/c/c4/Globe_icon.svg)

My suggestion here is to enhance this feature, so that we can use URL's of raw SVG's in addition to base-64 encoded images.

---

## :warning: Potential Problems

I foresee that there may be a few potential problems that may need to be handled. Here are just some that I can think of:

|  | Issue | Potential Workaround |
|---|---|---|
| 1. | How to embed a URL within another URL | This is necessary for the proper pointer to the raw SVG image. However, I'm not exactly sure how to handle this one...
| 2. | Raw SVG icon too big | It is possible to scale SVG's to smaller sizes. That's the beauty of SVG's; they're scalable. So it should be possible to set the default width/height of the SVG as it is rendered back to the web page.
| 3. | Raw SVG icon has complex colours | Overwrite the default SVG colour scheme and automatically re-write the SVG to handle a single colour scheme, which can then be controlled with the `labelColour=` element of the URL.

---

I hope that is clear and detailed enough for you! :+1:!
I love using [shields.io](https://shields.io/) badges :heart:!
And I am looking forward to further enhancements to your amazing tool :blush:!
Thank you so much :smiling_face_with_three_hearts:!

**Comment by calebcartwright** [comment] 2023-01-24 05:20
Thank you for reaching out and taking the time to write up your request in such detail!

Unfortunately, however, I'm going to have to close this because it's a duplicate of several previous issues where we've already responded to, and rejected, this feature request.

Refs #760, #6153, #7404, and various others

**Closed by calebcartwright** 2023-01-24 05:20 UTC
