### ISSUE TITLE
download badge shows zero

### ISSUE THREAD

**Issue by River-Mochi** [badges/shields#8951] opened 2023-03-03 10:32 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

- Download badge shows zero
- we have releases, it's python script
- there have definitely been downloaded
- API does not show download_count
https://api.github.com/repos/builder555/PineSAM/releases

This is the Github Repo:  **https://github.com/builder555/PineSAM**

thank you for any help. I saw another ticket where someone mentioned the API which is only reason I knew to check api page for download_count. othwise I'm lost as to how to get download badge to work. 
thanks.

### 🔗 Link to the badge

https://camo.githubusercontent.com/d5c8e1b0dbc58928bcd7b04537b0f1abfb7dad14d92e36a6b46a57a197c845bd/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f646f776e6c6f6164732f6275696c6465723535352f50696e6553414d2f746f74616c3f636f6c6f723d626c7565267374796c653d706c6173746963

![GitHub all releases](https://img.shields.io/github/downloads/builder555/Pinesam/total)

**Comment by calebcartwright** [comment] 2023-03-03 13:59
Thanks for reaching out but going to close as a duplicate of #833, which contains the details/explanation of GitHub's behavior and some alternative approaches you could consider taking.

**Closed by calebcartwright** 2023-03-03 13:59 UTC
Labels: question
