### ISSUE TITLE
'Telegram' logo does not respect logoColor value

### ISSUE THREAD

**Issue by Welding-Torch** [badges/shields#7576] opened 2022-02-05 21:04 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

So basically, while I was trying to fancy up my GitHub readme with some badges, I added Instagram first and then I added Telegram. Now I realised that I could use the `logoColor` property on Instagram (for example `https://img.shields.io/badge/-Instagram-red?color=DD2A7B&logo=instagram&logoColor=white` to make the Instagram logo become white. But when I tried to make the Telegram logo white, I realised that **the Telegram logo remains blue regardless of logoColor**. 

This is a bit of an annoying problem seeing as how I'm trying to give the badges in my ReadMe a consistent look, and the Telegram logo sticks out like a **sore thumb**.

### 🔗 Link to the badge

https://simpleicons.org/icons/telegram.svg

And for reference help: https://simpleicons.org/icons/instagram.svg

Images for visual help:
![image](https://user-images.githubusercontent.com/46340124/152658530-81bf7415-e00d-4461-9081-b4e7235a05be.png)

![image](https://user-images.githubusercontent.com/46340124/152658772-1167df3e-01f5-4252-8423-0318d2606939.png)

The code for the image directly above is:
```
![Telegram](https://img.shields.io/badge/-telegram-red?color=white&logo=telegram&logoColor=black)
![Instagram](https://img.shields.io/badge/-Instagram-red?color=white&logo=instagram&logoColor=black)
```
---
**As you can see, while the logo color for the Instagram logo changes, the logo color for Telegram does not.** 

### 💡 Possible Solution

Possible solution: Talk to the people who run the Simple Icons API and let them know about this problem and ask them to fix it.

**Comment by calebcartwright** [comment] 2022-02-05 22:17
That's by design as we use a custom logo for telegram that takes preference over the SI reference. I believe the underlying calculus, which led us to keep telegram as one of the handful of custom logos we maintain, remains unchanged so I don't anticipate changing anything on our side.

In this case I think your best bet is to get the logo you want (via SI or otherwise) and adjust the color as needed, and then leverage our [custom logo](https://github.com/badges/shields/blob/master/doc/logos.md#custom-logos) feature to embed that version in your badge 

https://github.com/badges/shields/blob/master/doc/logos.md
https://github.com/badges/shields/issues/2510
https://github.com/badges/shields/pull/2880

**Comment by PyvesB** [comment] 2022-02-06 11:59
This is by and large a duplicate of #6208, shall we continue the discussion there?

**Comment by calebcartwright** [comment] 2022-02-07 02:17
Agreed, closing

**Closed by calebcartwright** 2022-02-07 02:17 UTC
Labels: question

**Comment by chris48s** [comment] 2022-11-26 14:04
update: https://github.com/badges/shields/issues/6208#issuecomment-1328051956
