### ISSUE TITLE
Allow changing font of text inside badge

### ISSUE THREAD

**Issue by themightywolfie** [badges/shields#9591] opened 2023-09-20 13:47 UTC
:clipboard: **Description**

I searched high and low and there does not seem to be an option to change the font of the text inside the badge. I think it would be great if we were allowed to change the font to customize the badge and match a website's font where the badge is used

**Comment by Kanav-Arora** [comment] 2023-09-26 11:58
@chris48s Can I start working on this? Please share some views on this

**Comment by calebcartwright** [comment] 2023-09-26 16:11
Thanks for reaching out but going to close as a duplicate of #127 and something we're not going to do, though we can reopen in the event any other maintainers want to reopen this discussion. 

While I understand the desire for controlling the font in the context of the use case noted in the issue description, I remain opposed to this, with a few reasons being:

* We've consistently and recently rejected other customization requests that are comparatively less impactful/challenging, e.g. font colors
* AFAIK our SVGs still rely on a standard set of fonts that (a) achieve our design goals and (b) are readily available on a wide range of platforms/contexts.
* Opening up the font face to customization would, I imagine, introduce the need for a lot of CPU bound work on our prod environment to derive proper widths/spacing/kerning on the fly based on the label/message contents, and would accordingly introduce a new attack vector, and/or require _substantial_, pervasive changes to the badge-maker lib which I don't think justifies the means 
* Potential for emoji chaos

**Closed by calebcartwright** 2023-09-26 16:11 UTC
