### ISSUE TITLE
Packagist version badges not being updated

### ISSUE THREAD

**Issue by Majkl578** [badges/shields#1586] opened 2018-03-19 22:47 UTC
We have some libraries using Shilds.io badges. The latest version badges are stuck and not being updated.

Package [kdyby/datetime-provider](https://packagist.org/packages/kdyby/datetime-provider):
Version stuck at 1.0.0-BETA1 while current is 1.0.0: [![Latest stable](https://img.shields.io/packagist/v/kdyby/datetime-provider.svg)](https://packagist.org/packages/kdyby/datetime-provider)

Package [kdyby/datetime-provider-bundle](https://packagist.org/packages/kdyby/datetime-provider-bundle):
Version stuck at 1.0.0-BETA2 while current is 1.0.0: [![Latest stable](https://img.shields.io/packagist/v/kdyby/datetime-provider-bundle.svg)](https://packagist.org/packages/kdyby/datetime-provider-bundle)

Both releases are over a month old, yet not updated.

**Comment by paulmelnikow** [comment] 2018-03-19 23:32
Hi there! Thanks for reporting this.

![](https://img.shields.io/packagist/v/kdyby/datetime-provider.svg)
https://img.shields.io/packagist/v/kdyby/datetime-provider.svg

![](https://img.shields.io/packagist/v/kdyby/datetime-provider-bundle.svg)
https://img.shields.io/packagist/v/kdyby/datetime-provider-bundle.svg

Hmm, **beta** is supposed to be lowercase.

Is this the same issue as #885? It would be great if packagist enforced the [composer versioning scheme](https://getcomposer.org/doc/04-schema.md#version)…

**Comment by Majkl578** [comment] 2018-03-19 23:44
Imho there's difference between composer version and tag name. Composer parses the tags and creates versions from those. Also upper-case BETA is used in examples directly in Composer's documentation: https://getcomposer.org/doc/articles/versions.md#vcs-tags-and-branches.
Semver also only talks about lexicographic order, not mentioning upper/lower case explicitly: https://semver.org/spec/v2.0.0.html#spec-item-11
Finally the Composer Semver version parser is case-insensitive: https://github.com/composer/semver/blob/1.4.2/src/VersionParser.php#L59

So this may be similar/same issue as #885, but this seems to be an issue in your code (as per the comment there):
> It looks like our code recognizes RC1 but not rc1.

**Comment by chris48s** [comment] 2018-03-22 18:06
I've had a brief look at this and I think the way forward here is we should be using the `version_normalized` property rather than using the object key as the version on that badge. That should do the appropriate transformation into the published composer version scheme for us to compare to. I'll try and have a proper look at it later and submit a patch.

**Comment by chris48s** [comment] 2018-03-22 20:43
Started digging into this and realised that the algorithm for working out the latest version from packagist has changed several times over the years. It looks like initially, this was actually being done by comparing `version_normalized` (which seems to have some strange values for stuff like versions derived from branch aliases) but this was removed and has changed several times since to solve various issues. `version_normalized` probably is not the silver bullet here..

**Comment by Geolim4** [comment] 2018-05-30 12:06
Same here: we're getting stuck to 7.0.0-rc4:
https://img.shields.io/packagist/v/phpfastcache/phpfastcache.svg

While the 7.0.0 has been released days ago:
https://github.com/PHPSocialNetwork/phpfastcache/releases

**Comment by Geolim4** [comment] 2018-06-01 15:37
Nevermind, I edited and uppercased all my Git RC releases tags (plus packagist tags & update) and it's now working.

**Comment by Majkl578** [comment] 2018-06-01 15:41
Editing/re-pushing tags is absolute no-go so this still needs to be fixed anyway. :S

**Comment by RedSparr0w** [comment] 2018-06-02 21:50
Is there any reason we aren't using semver `latestVersion()` for this?
As this issue would be fixed by #1628 - [[relevant test]](https://github.com/badges/shields/pull/1628/files#diff-860a977a1246cd56517111999db2d3f1R39)

**Comment by Geolim4** [comment] 2018-06-03 13:35
Maybe this will give you an idea why the choice of RC in uppercase:
https://github.com/composer/packagist/issues/911

**Comment by paulmelnikow** [comment] 2018-06-16 16:11
As far as I can tell, this remains a duplicate of #885: a request that Shields ignore case when computing latest versions for Packagist. Apologies if I'm missing something there.

Reading composer/packagist#911 and composer/composer#7347 further convinces me that we should stick with a strict interpretation of the Packagist versions.

I agree that this is not a good developer experience, because they are publishing versions expecting a certain behavior, and for surprising nitpicky reasons it doesn't happen. However, a lenient interpretation in Shields is not doing them a favor, because the version will continue to behave strangely in other tools. In fact we're the canary: the first-noticed indication that something has gone wrong.

Since the right place to fix this problem is in the Packagist API, I have opened an issue there: composer/packagist#921.

I recognize mine is an unpopular perspective, so I urge you to read the issues I've linked to, and to please upvote my feature request.

**Closed by paulmelnikow** 2018-06-16 16:11 UTC
Labels: question

**Comment by antonioribeiro** [comment] 2020-10-17 08:44
This keeps happening:

![](https://img.shields.io/packagist/v/pragmarx/health.svg?style=flat-square)
https://img.shields.io/packagist/v/pragmarx/health.svg?style=flat-square

Version on packagist:
https://packagist.org/packages/pragmarx/health
![image](https://user-images.githubusercontent.com/3182864/96332652-9a377880-1065-11eb-8215-405afd39dc87.png)
