### ISSUE TITLE
Bintray badges not working

### ISSUE THREAD

**Issue by Squeazer** [badges/shields#934] opened 2017-04-07 12:12 UTC
Badges for Bintray do not seem to be working.

For instance, the example that is offered on [shields.io](http://shields.io/):

https://bintray.com/asciidoctor/maven/asciidoctorj
https://img.shields.io/bintray/v/asciidoctor/maven/asciidoctorj.svg
[![Bintray](https://img.shields.io/bintray/v/asciidoctor/maven/asciidoctorj.svg)]()

**Comment by paulmelnikow** [comment] 2017-04-07 12:19
It looks like the badge has been flaky for a long time. Duplicate of #658, let's discuss there.

**Closed by paulmelnikow** 2017-04-07 12:19 UTC
