### ISSUE TITLE
This page crashed. URI malformed

### ISSUE THREAD

**Issue by DJStompZone** [badges/shields#9519] opened 2023-08-29 06:19 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

When using the badge maker/tester UI at https://shields.io/badges, the page instantly crashes if the user attempts to input an emoji into the topmost field, showing the message "This page crashed. URI malformed"

### 🔗 Link to the badge

![](https://img.shields.io/badge/🤔-interesting-purple)
![](https://img.shields.io/badge/🤷‍♂️-api_works_fine-black)

### 💡 Possible Solution

Something's presumably choking on extra-long unicode characters such as emojis. Will investigate further

**Comment by chris48s** [comment] 2023-08-29 16:35
I just tried to reproduce this and I am not seeing this issue

![Screenshot at 2023-08-29 17-34-16](https://github.com/badges/shields/assets/6025893/2a8ae113-46ed-4598-8c3c-5933b587803f)

Are you able to provide any additional info? Whta browser/OS are you using? I'd guess this might be something that only affects a subset of browsers?

**Comment by DJStompZone** [comment] 2023-08-30 19:44
So far I've only reproduced this bug on Microsoft Edge (Version 114.0.1823.36 64-bit) on Xbox One, I can check to see if there's any other browsers that do it as well. I've tested it on Chrome 114 on Android 9 and was unable to reproduce.

**Comment by DJStompZone** [comment] 2023-08-30 19:48
Update, the crash only occurs when typing in an emoji in the box, if I paste a complete set of params all at once such as `🤨-interesting-blue`  it works fine and doesn't crash.

**Comment by jNullj** [comment] 2023-09-06 20:13
I think color is not optional, you can not only pick up an emoji without setting a color as well.
I think this is a technical limit due to other paths, if you use the url with one parameter only it might search for a badge with that name as the static badge has a path of `https://shields.io/badge\{label-msg-color}` while other badges follow a similar address like `/badge/dynamic/json`, `/badge/dynamic/xml`, `/badge/dynamic/yaml`. without the dash (-) to seperate parameters in badge name.
![image](https://github.com/badges/shields/assets/15849761/f354ba82-f052-40fe-8f1b-370cca19b9de)

**Comment by jNullj** [comment] 2023-09-06 20:17
Cool, was able to reproduce on win10 just now, I did not have an issue with regular emoji or win+. emoji
It only happend when using the on-screen keyboard, i use it lots for VR. It happends on edge and chrome

**Comment by jNullj** [comment] 2023-09-06 20:40
Was able to confirm it in the demo of https://github.com/cloud-annotations/docusaurus-openapi plugin we use:
1. go to the demo at https://docusaurus-openapi.netlify.app/cos/create-a-bucket
2. Insert emoji using the built in on screen win10 keyboard in the first input field on the side menu
3. Same issue: 
![image](https://github.com/badges/shields/assets/15849761/6a4964d0-b234-48a1-ada9-3eb9a91902f9)
I will open an issue on the plugin repo

**Comment by jNullj** [comment] 2023-09-06 22:19
I found the bug on docusaurus-openapi, this is the result of onInput for UTF-16 encoded emoji by the keyboard, The current on input solution tries to translate those to URI which fails and results in this error. I will PR a solution today or tomorrow.

**Comment by chris48s** [comment] 2024-03-23 20:59
This took longer than I wanted it to, but the fix for this is now deployed

**Closed by chris48s** 2024-03-23 20:59 UTC
Labels: question, needs-upstream-help, frontend
