### ISSUE TITLE
[SonarQube] Shield does not display tech debt

### ISSUE THREAD

**Issue by damianszczepanik** [badges/shields#877] opened 2017-02-15 22:56 UTC
For the net.masterthought:cucumber-reporting project shield does not display tech debt.

Problematic:
https://img.shields.io/sonar/http/nemo.sonarqube.org/net.masterthought:cucumber-reporting/tech_debt.svg
Working:
https://img.shields.io/sonar/http/nemo.sonarqube.org/com.puppycrawl.tools:checkstyle/tech_debt.svg

Project site at Sonar
https://sonarqube.com/dashboard/index?id=net.masterthought%3Acucumber-reporting

**Comment by dannil** [comment] 2017-03-11 12:20
Same issue here with https://img.shields.io/sonar/http/sonarqube.com/com.github.dannil:scb-java-client/tech_debt.svg

Project at Sonar https://sonarqube.com/dashboard?id=com.github.dannil%3Ascb-java-client

**Comment by bbilger** [comment] 2017-03-12 21:49
In case it's helpful for anyone: 
I had the same issue and saw that SonarQube has its own badge API - so I switched to using that for the time being:
https://github.com/QualInsight/qualinsight-plugins-sonarqube-badges/wiki/Measure-badges
e.g.: `https://sonarqube.com/api/badges/measure?key=net.masterthought:cucumber-reporting&metric=sqale_debt_ratio`
, or `https://sonarqube.com/api/badges/measure?key=com.github.dannil:scb-java-client&metric=sqale_debt_ratio`

**Comment by sgrillon14** [comment] 2017-04-01 21:09
Sonarqube API change: https://sonarqube.com/web_api/api/resources (deprecated since 5.4)

Old sample (sonarqube 5.1.2): http://sonar.qatools.ru/api/resources?resource=ru.yandex.qatools.allure:allure-core&depth=0&metrics=sqale_debt_ratio&includetrends=true

New sample (sonarqube 6.3): https://sonarqube.com/api/measures/component?componentKey=com.github.noraui:noraui&metricKeys=sqale_debt_ratio&includetrends=true

**You need change code in this part of shields/server.js to calling new API:**

```
var apiUrl = scheme + '://' + serverUrl + '/api/resources?resource=' + buildType
          + '&depth=0&metrics=' + encodeURIComponent(sonarMetricName) + '&includetrends=true'; 
```

The new API return this json sample:
{"component":`{"id":"AVsmTVHJGqR9xtJfHMWb","key":"com.github.noraui:noraui","name":"NORAUI","description":"Non-Regression Automation for User Interfaces","qualifier":"TRK","measures":[{"metric":"sqale_debt_ratio","value":"0.4","periods":[{"index":1,"value":"0.0"}]}]}}`

**You need change code in this part of shields/server.js to use response of new API:**
```
var value = data[0].msr[0].val;
```

var value = component.measures[0].value

**Comment by paulmelnikow** [comment] 2017-04-01 21:24
Hi, thanks for this issue. Seems like we should try to support both versions. Could you open a pull request?

**Comment by sgrillon14** [comment] 2017-04-01 22:02
How can test this part "camp.route(/^\/sonar\/(http|https)\/(.*)\/(.*)\/(.*)\.(svg|png|gif|jpg|json)$/,...." in a development environnement please?
I thought I would add a parameter with the version of the target sonarqube

**Comment by paulmelnikow** [comment] 2017-04-02 05:09
Ah, to fix that, you'll need to upgrade to Node 6. Would be worth adding that to the tutorial.

Thanks for looking into this!

**Comment by sgrillon14** [comment] 2017-04-02 19:26
I install node 7,
http://[::]:8080/try.html ready on my personal macbook, I read this issue this week.

**Comment by sgrillon14** [comment] 2017-04-03 21:21
I valid in my macbook:
![capture d ecran 2017-04-03 a 23 14 10](https://cloud.githubusercontent.com/assets/5530550/24632338/13998648-18c4-11e7-9d2d-5d209ebc9393.png)

I create a PR: https://github.com/badges/shields/pull/931 but travis-ci is KO with this trace:
gh-badges@1.3.0 lint /home/travis/build/badges/shields
> eslint '**/*.js'
/home/travis/build/badges/shields/server.js
  911:15  error  'apiUrl' is already defined  no-redeclare
  928:19  error  'value' is already defined   no-redeclare
✖ 2 problems (2 errors, 0 warnings)
npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.10.1/bin/node" "/home/travis/.nvm/versions/node/v6.10.1/bin/npm" "run" "lint"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! gh-badges@1.3.0 lint: `eslint '**/*.js'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gh-badges@1.3.0 lint script 'eslint '**/*.js''.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the gh-badges package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint '**/*.js'
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs gh-badges
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls gh-badges
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/badges/shields/npm-debug.log
npm ERR! Test failed.  See above for more details.
The command "npm test" exited with 1.

**Comment by paulmelnikow** [comment] 2017-04-03 21:33
Here's some explanation of that error: http://eslint.org/docs/rules/no-redeclare

Because a `var` is scoped to the containing function and [JavaScript does something called hoisting](http://stackoverflow.com/a/21727020/893113) for variable declarations, putting multiple `var` declarations for the same identifier is allowed, yet confusing to the reader.

You're probably writing something like this:

```
if (...) {
    var apiUrl = ...
} else {
    var apiUrl = ...
}
```

You can write this instead:

```
var apiUrl;
if (...) {
    apiUrl = ...
} else {
    apiUrl = ...
}
```

**Comment by sgrillon14** [comment] 2017-04-03 21:43
I fixed issue (from javascript). This PR is finished and ready.

**Comment by sgrillon14** [comment] 2017-04-05 19:18
Hello @paulmelnikow, when do you put this evolution online?

**Comment by paulmelnikow** [comment] 2017-04-05 21:35
I'll review and test PR #931 within the next week or so. We can discuss the changes there. Thanks again for opening that!

**Comment by paulmelnikow** [comment] 2017-10-31 02:36
PRs #855 and #931 needed work and were closed without being merged. If anyone would like to revive them, feel free.

**Closed** 2017-11-11 20:26 UTC
Labels: bug, good first issue, service-badge
