### ISSUE TITLE
Github: Vendor unresponsive

### ISSUE THREAD

**Issue by sagikazarmark** [badges/shields#564] opened 2015-11-16 13:09 UTC
![screenshot 2015-11-16 14 08 07](https://cloud.githubusercontent.com/assets/1226384/11182489/89701828-8c6b-11e5-86d2-2a6fc6174419.png)

**Comment by anowlcalledjosh** [comment] 2015-12-04 15:58
Duplicate of #529.

**Comment by espadrine** [comment] 2015-12-15 22:38
Thanks for reporting! It is indeed a duplicate.

**Closed by espadrine** 2015-12-15 22:38 UTC
