### ISSUE TITLE
Badge request: Lines of code (LOC)

### ISSUE THREAD

**Issue by rugk** [badges/shields#2731] opened 2019-01-11 09:05 UTC
:clipboard: **Description**

It would be great to have a badge that just counts all lines of code (no markdown, or so obviously) and shows that number to the user.

service: GitHub
shows: "101|LOC" or "42|LOC"

:link: **Data**

GitHub, don't know the details here

:microphone: **Motivation**

That is useful for projects that aim to be minimal/small, or artistic stuff that does something in exactly 42 lines of code or any other "special number".

**Comment by calebcartwright** [comment] 2019-01-11 15:53
Hi @rugk interesting idea! I think for this to feasible Shields would need to be able to retrieve this information from some API/endpoint (not attempt to calculate it ourselves).

If someone wants to try to dig in to what services are available that provide this information we can certainly look into adding this!

**Comment by calebcartwright** [comment] 2019-01-11 16:01
Possibly worth investigating as a solution: https://github.com/jolav/codetabs and https://codetabs.com/count-loc/count-loc-online.html in particular

**Comment by calebcartwright** [comment] 2019-01-22 00:21
I also just realized this _may_ be a duplicate of #390 😄

**Comment by paulmelnikow** [comment] 2019-01-22 02:56
Aha! This one is a little more coherent :)

**Comment by PyvesB** [comment] 2019-02-05 21:03
We briefly discussed this [here](https://github.com/badges/shields/pull/1160#discussion_r144375319). There didn't seem to be a clean and reliable way to get the number of lines of code in a GitHub repository.

**Comment by conao3** [comment] 2019-03-10 14:09
FYI: "tokei" can count LoC and prepared badge API, but there is not json API...
You may be able to use it by parsing information yourself from returning svg.
https://github.com/Aaronepower/tokei#badges

`[![](https://tokei.rs/b1/github/badges/shields)]()` will shows [![](https://tokei.rs/b1/github/badges/shields)]()
```
$ curl https://tokei.rs/b1/github/badges/shields
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="70" height="20">
  <linearGradient id="smooth" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>

  <mask id="round">
    <rect width="70" height="20" rx="3" fill="#fff"/>
  </mask>

  <g mask="url(#round)">
    <rect width="28" height="20" fill="#555"/>
    <rect x="28" width="42" height="20" fill="#007ec6"/>
    <rect width="70" height="20" fill="url(#smooth)"/>
  </g>

  <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
    <text x="14" y="15" fill="#010101" fill-opacity=".3">LoC</text>
    <text x="14" y="14">LoC</text>
    <text x="49" y="15" fill="#010101" fill-opacity=".3">73.6K</text>
    <text x="49" y="14">73.6K</text>
  </g>
</svg>
```

**Comment by conao3** [comment] 2019-03-10 14:15
I also want to display this information in the Readme, but I would like to display it in Shields' `flat-square` style.

**Comment by rugk** [comment] 2019-03-10 14:22
Created issue for requesting a JSON web API: https://github.com/Aaronepower/tokei/issues/310

**Comment by chris48s** [comment] 2019-03-10 14:50
If the information is available as an SVG, you could write a badge using the `BaseSvgScrapingService` class. There are various examples of other badges that do this:

https://github.com/badges/shields/search?q=BaseSvgScrapingService&type=Code

**Comment by rugk** [comment] 2019-03-21 06:56
https://github.com/Aaronepower/tokei_rs/issues/8 has been solved 🎉:
> I have now implemented this in tokei.rs if you change your Accept HTTP header to `application/json` you will receive JSON data.

**Comment by feluelle** [comment] 2019-05-24 09:10
I would like to show the line count of a specific file. Is that possible as well?

**Comment by jnm2** [comment] 2019-06-22 23:18
Line count under a specific folder would be nice so the badge can show product LOC and test LOC.

**Comment by Kerndog73** [comment] 2019-08-19 01:51
@jnm2 Yeah the badge is showing 106.1K for my repo even though there's only 16.5K under src. It's rather misleading!

**Comment by MonliH** [comment] 2019-12-21 17:55
Have you seen this: `https://sloc.xyz/github/<user>/<repo>`? I found it but there is still no way to use a custom badge style (comes with the defualt style)

**Comment by calebcartwright** [comment] 2019-12-22 02:10
Sounds like there are a couple endpoints that provide the data in a way Shields can consume and provide badges for.

We've got a great [tutorial](https://github.com/badges/shields/blob/master/doc/TUTORIAL.md) if anyone is interested in implementing this in Shields!

**Comment by AndrewB330** [comment] 2020-08-14 20:23
You can also try https://github.com/AndrewB330/XLOCC
It supports file filtering, ignoring empty lines, ignoring comments

I think later I may try to add this to shields.io

**Closed** 2020-09-18 03:34 UTC
Labels: good first issue, service-badge
