### ISSUE TITLE
Github license and issue badges are not working

### ISSUE THREAD

**Issue by caarlos0** [badges/shields#628] opened 2016-01-11 18:11 UTC
"Vendor unresponsible"

![image](https://cloud.githubusercontent.com/assets/245435/12242032/bbb144f4-b87d-11e5-921b-f2e014974d61.png)

or sometimes just this:

![image](https://cloud.githubusercontent.com/assets/245435/12242049/e3916c92-b87d-11e5-9747-f61d7447a940.png) (repo: https://github.com/getantibody/antibody)

**Comment by hlandau** [comment] 2016-01-17 19:30
Experiencing this also, for github/release and github/downloads. It takes so long to respond that camo.githubusercontent.com times out, so you don't even see 'vendor unresponsive'. What's going on here?

**Comment by tomschenkjr** [comment] 2016-01-20 15:42
Also experiencing long latency in loading the embedded shields. Reported in Chicago/opengrid#137 and confirmed for some other repos.

**Comment by sotojuan** [comment] 2016-01-21 17:00
Yeah none of my badges are loading, and I am just using the Travis one :/

**Comment by Bilge** [comment] 2016-01-23 02:56
Confirmed, long-standing issue with GitHub badges.

**Comment by zbeekman** [comment] 2016-01-25 18:24
I too am experiencing this problem. A real show stopper, thinking about removing shields.io badges from project due to this.

**Comment by groggemans** [comment] 2016-02-07 12:08
+1, Any idea what's going on? or when this will be fixed?

**Comment by lillian-lemmer** [comment] 2016-02-23 05:48
I find that the license working is a bit of a cointoss...

**Comment by espadrine** [comment] 2016-03-29 21:20
Yep, the original issue is here: https://github.com/badges/shields/issues/529. I contacted GitHub on the subject. I'll close this issue to keep details on the old one.

**Closed by espadrine** 2016-03-29 21:20 UTC
Labels: performance
