### ISSUE TITLE
Broken images all the time in Github readme

### ISSUE THREAD

**Issue by g105b** [badges/shields#1598] opened 2018-03-23 13:09 UTC
I've been in touch with Github over the time period of about 4 months regarding this issue.

In short, I can **always** successfully visit the URL to the Shields image, but when it is proxied by Github's `githubusercontent.com` domain, Shields images often appear broken.

For an example, head over to https://github.com/PhpGt/Dom and keep refreshing. For me, one in every ten requests ends up looking something like this:

![unnamed 1](https://user-images.githubusercontent.com/358014/37831008-f3d81be6-2e9b-11e8-8e35-7666843dd62a.gif)

Which images are broken is different each time. 

Here is a screenshot of my network tab in Chrome Developer Tools for one of the broken images:

![image](https://user-images.githubusercontent.com/358014/37830959-c35e39b4-2e9b-11e8-816c-295f2268b0ce.png)

I'm not sure what to suggest, but Github have clearly stated that it is not their problem, it is the problem of the remote image server. Happy to help with whatever details you need from me.

**Comment by g105b** [comment] 2018-03-23 13:14
Another example website:

![image](https://user-images.githubusercontent.com/358014/37831048-1502d252-2e9c-11e8-8bb4-61872ad67cdd.png)

**Comment by g105b** [comment] 2018-03-23 13:16
Response from Github staff when I complained about this issue to them:

> From: Antonio Diaz (Github Staff)
> To: Greg Bowler
>
> Hey Greg,
> 
> Thanks for your patience as we investigated this. Looking in our logs, connections to the site 
> that hosts your badge images, sometimes fail. This does not appear to be a problem with our image 
> proxy.
> 
> If you're seeing broken images from that site, I would recommend reaching out to them to see what 
> might be causing these unreliable connections.
> 
> Cheers,
> Antonio

**Comment by MarkVaughn** [comment] 2018-03-23 15:57
also getting this from all over our projects e.g
https://github.com/paratestphp/paratest

<img width="587" alt="screen shot 2018-03-23 at 9 55 56 am" src="https://user-images.githubusercontent.com/39970/37839595-6eea2f3e-2e80-11e8-9f3b-3aa35a8a4879.png">

very common badges (travis, scrutinizer, packagist
```
[![Build Status](https://travis-ci.org/paratestphp/paratest.svg?branch=master)](https://travis-ci.org/paratestphp/paratest)
[![Code Coverage](https://scrutinizer-ci.com/g/brianium/paratest/badges/coverage.png?b=master)](https://scrutinizer-ci.com/g/brianium/paratest/?branch=master)
[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/brianium/paratest/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/brianium/paratest/?branch=master)
[![Packagist](https://img.shields.io/packagist/dt/brianium/paratest.svg)](https://packagist.org/packages/brianium/paratest)
```
[![Build Status](https://travis-ci.org/paratestphp/paratest.svg?branch=master)](https://travis-ci.org/paratestphp/paratest)
[![Code Coverage](https://scrutinizer-ci.com/g/brianium/paratest/badges/coverage.png?b=master)](https://scrutinizer-ci.com/g/brianium/paratest/?branch=master)
[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/brianium/paratest/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/brianium/paratest/?branch=master)
[![Packagist](https://img.shields.io/packagist/dt/brianium/paratest.svg)](https://packagist.org/packages/brianium/paratest)

**Comment by paulmelnikow** [comment] 2018-03-23 18:14
Hi, thanks for the report. The issue is caused by slow responses from the Shields server combined with GitHub's image proxy's timeout. (The combination causes slow images to be rendered as missing images.)

This is a duplicate of #1568. Let's discuss there.

**Closed by paulmelnikow** 2018-03-23 18:14 UTC
