### ISSUE TITLE
Option to use GitHub Octicons directly in badges

### ISSUE THREAD

**Issue by Andre601** [badges/shields#7588] opened 2022-02-10 23:11 UTC
:clipboard: **Description**

When using badges from shields do I really like to use the SVG icons from GitHub called Octicons, as the badges themself are often used in GitHub repositories and those icons fit the best for what the badges may represent.

The issue right now for me is, that I have to use the `logo=data:image/svg...` query parameter in the badge URL to achieve this which comes with 2 distinct problems:

1. The badge URL becomes quite long. While you can argue that this doesn't matter since people only would see the badge itself, do I say that the raw view of a readme - especially since you can now much easier view the raw version of markdown files - is also important, especially for new contributors, and that a large URL could be frightening to look at.
2. The SVGs are black by default since they don't have any specific fill color defined, this requires me to download, or at the very least copy the SVG code and insert a `fill="#fff"` attribute to the SVG in question, before putting it into a Base64 encoder and use the value as logo option. With shields natively supporting octicons could this become easier by having the logoColor option taking care of it.

Of course, considering support opens questions such as "How easy is it to implement?", "How much would it be used?" and "How to actually implement it?"
While I can't answer the first because I lack the coding knowledge of the framework shields uses, and can't answer the second because I don't have any statistics on how much octicons are used by people, can I give possible ideas for the third question:

1. Add to `logo` query parameter, but maybe with a `octicons:` prefix to avoid possible conflicts in naming (I.e. `logo=octicons:alert-24` would get the [Alert 24px SVG](https://primer.style/octicons/alert-24))
2. Add a separate `octicons` parameter to use (i.e. `octicons=alert-24`). If both octicons and logo parameter would be used would shield prioritize the logo one.

I also can't answer any real questions regarding legal parts. Octicons are Open source and licensed under MIT ([GitHub Repository](https://github.com/primer/octicons)), so it may or may not work fine with shields CC0 licensing?

Whatever the decision is, I thank you for reading this idea and hope to hear from you soon.

**Comment by calebcartwright** [comment] 2022-02-10 23:15
Thanks but I'm going to close this as a duplicate of #7131 to avoid bifurcation of discussion

**Closed by calebcartwright** 2022-02-10 23:15 UTC
