### ISSUE TITLE
Add a "Visitors" badge

### ISSUE THREAD

**Issue by RivanParmar** [badges/shields#7755] opened 2022-03-19 16:45 UTC
:clipboard: **Description**
Please add a  "Visitors" badge that shows number of visitors that visited your profile and your repository.

A clear and concise description of the new badge.

- Which service is this badge for : GitHub
- What sort of information should this badge show? : number of visitors

#### Static Example:
Link : https://img.shields.io/badge/visitors-400-green
![Github Visitors](https://img.shields.io/badge/visitors-400-green)

:link: **Data**

:microphone: **Motivation**

Please explain why this feature should be implemented and how it would be used.

- What is the specific use case? : This feature should be implemented so that users can show the number of visitors to their repository or profile through a badge in README files.

**Comment by calebcartwright** [comment] 2022-03-19 16:56
Thanks for reaching out but going to close as a duplicate of #4637

**Closed by calebcartwright** 2022-03-19 16:56 UTC
Labels: service-badge

**Comment by RivanParmar** [comment] 2022-03-20 04:37
But has it been added? If not, then I would like to contribute.

**Comment by calebcartwright** [comment] 2022-03-20 15:56
It's great that you're willing to contribute, and I really appreciate that! However, no the badge does not exist, and unfortunately it cannot be added. The details of why that's the case, along with some alternatives you may consider, are discussed in the thread I linked to previously (#4637).

In short, GitHub requires a higher level of authorization scope for that type of information, including repository visitors, and it's not possible for the Shields.io service to support that level of auth to user's GH repositories.

**Comment by RivanParmar** [comment] 2022-03-20 15:58
Ok , thank you!
