### ISSUE TITLE
GitHub Releases sort by semver always includes pre-releases

### ISSUE THREAD

**Issue by oktal3700** [badges/shields#5285] opened 2020-07-05 00:12 UTC
:beetle: **Description**

The badge "GitHub release (latest SemVer)" should **not** include pre-releases.

There is already a badge "GitHub release (latest SemVer including pre-releases)" for when that behavior is desired.

:link: **Link to the badge**

![example](https://img.shields.io/github/v/release/swift-project/pilotclient?sort=semver)
https://img.shields.io/github/v/release/swift-project/pilotclient?sort=semver

The release `v0.9.5.45` is a pre-release. The badge should display `v0.9.4.389` instead.

**Comment by calebcartwright** [comment] 2020-07-05 01:44
hi @oktal3700, thanks for reaching out. 

> The release v0.9.5.45 is a pre-release. The badge should display v0.9.4.389 instead.

From a semver perspective, both of these are pre-release versions and when a repo only has pre-releases (as defined by semver) then Shields falls back to using the pre-release versions instead of throwing an error. 

I can see that you leveraged GitHub's flag to mark one of your releases as non-production ready but not on the other one. [v0.9.5.45](https://github.com/swift-project/pilotclient/releases/tag/v0.9.5.45) has the flag set but your [v0.9.4.389](https://github.com/swift-project/pilotclient/releases/tag/v0.9.4.389) release does not. However, that flag isn't used, particularly so when the sort is set to semver.

This is the correct and expected behavior for a semver based sorting. 

That being said, I suppose we could consider incorporating that flag in some shape or form. @chris48s you've spent a lot of time with these, what are your thoughts?

If the GH flag was incorporated as another sort variant, there'd still be a question of how to sort between multiple versions that don't have the flag set (date or semver). I guess it could be an additional query param that allowed users to be able to filter out those releases missing the flag, but we'd have to think through how to handle conflicts (like this very scenario) and fallbacks. 

![image](https://user-images.githubusercontent.com/13042488/86523761-cfadb280-be36-11ea-8a0a-1ee6d1753b23.png)

**Comment by oktal3700** [comment] 2020-07-05 14:54
I see. Thank you for the explanation. I can see there's no easy answer for how this should behave in all circumstances.

**Comment by chris48s** [comment] 2020-07-05 16:23
If `0.9.5.45`, is a pre-release while `0.9.4.389` is a "stable" release, your project is not using semver. Try sorting by `date` :)

https://img.shields.io/github/v/release/swift-project/pilotclient?sort=date

**Comment by oktal3700** [comment] 2020-07-05 17:55
Understood. Thank you. Sorting by date is equally unsatisfactory for my purposes.

I would use a semver-conformant suffix e.g. `0.9.5.45-alpha` but I would prefer to be able to mark a pre-release tag as a stable tag at a later date (after some testing phase) without changing the tag string itself.

I will try using a custom endpoint badge.

**Comment by calebcartwright** [comment] 2020-07-05 18:03
> I would use a semver-conformant suffix e.g. 0.9.5.45-alpha

Technically the 4th component in your version strings makes these non-semver compliant anyway (regardless of any additional suffix), but semver's also explicit about versions that have `0` for the major version component being pre-release and unstable

> I will try using a custom endpoint badge.

That may indeed be your best bet given your current versioning strategy and pre-release vs release indicators

**Comment by chris48s** [comment] 2020-07-05 20:39
> Sorting by date is equally unsatisfactory for my purposes.

Are you sure about that? ![](https://img.shields.io/github/v/release/swift-project/pilotclient?sort=date) https://img.shields.io/github/v/release/swift-project/pilotclient?sort=date does what you said you want in your first post.

> I would prefer to be able to mark a pre-release tag as a stable tag at a later date (after some testing phase) without changing the tag string itself.

Sorting by date (and excluding pre-releases) ignores the tag string and just displays the most recent release that is not marked as a pre-release. If you later change the flag on a pre-release to mark it stable, the badge will reflect that. It is intended for projects that don't follow semver.

**Comment by oktal3700** [comment] 2020-07-05 21:22
It's conceivable that we might create a release for a historical version, with a version number that is lower than the "current" release. In that case, the historical release would appear to be newer when sorting by date.

It's working now with a custom endpoint. Thank you for your time.

**Comment by oktal3700** [comment] 2020-07-05 21:36
🤔 actually would it sort by the date of the commit used to create the tag? That's better I suppose. Still not sure. I'll have to think about it.

**Comment by oktal3700** [comment] 2020-07-05 22:58
Yeah, it's conceivable that we backport a bugfix to an older version, which would increment the patch version but not the minor version. Sorting by date, this bugfix would be the newest release, but the semantically newest release should be the one with the higher minor version (in which the bug was already fixed).

**Closed** 2020-07-06 18:52 UTC
Labels: question
