### ISSUE TITLE
Add changing message color!

### ISSUE THREAD

**Issue by Avnsx** [badges/shields#6710] opened 2021-07-04 06:08 UTC
:clipboard: **Description**

I've figured out a github repo stars shields icon like this: https://img.shields.io/github/stars/Avnsx/Escape-from-Tarkov-Auto-Examine?style=flat-square&label=%E2%AD%90%20Stars&color=ffc83d&messageColor=ffffff

but as you see the text that displays the amount of stars on the right is still black(wanted to change it to white by hex color code) even though I tried doing ``&messageColor=ffffff``. I'm guessing that it just doesn't exist, as I couldn't find anything about changing the color of the "message" as you guys call it in the docs.

**Comment by calebcartwright** [comment] 2021-07-04 15:16
The supported query parameters are enumerated [here](https://shields.io/#shields) on the main Shields.io website.

However, it sounds like you're asking if you can customize the color of the text, and if so then this would be a duplicate of various prior issues including dating back to #504.

We do not allow the text colors to be customized. That's very much by design, and not going to change.

If that's no what you're requesting, could you please rephrase and elaborate on your ask?

**Comment by Avnsx** [comment] 2021-07-04 15:21
> The supported query parameters are enumerated [here](https://shields.io/#shields) on the main Shields.io website.
> 
> However, it sounds like you're asking if you can customize the color of the text, and if so then this would be a duplicate of various prior issues including dating back to #504.
> 
> We do not allow the text colors to be customized. That's very much by design, and not going to change.
> 
> If that's no what you're requesting, could you please rephrase and elaborate on your ask?

That's pretty unfortunate, I was hoping to change the black 8 to a white 8 (the right text)

**Comment by calebcartwright** [comment] 2021-07-04 15:33
> That's pretty unfortunate, I was hoping to change the black 8 to a white 8 (the right text)

Thank you for clarifying. Being infinitely customizable is an explicit non-goal of the project and as I mentioned previously the decision to automatically select white/black text based on the color of the background is a decision we're sticking with. Using white text on that background would make the text borderline unreadable, which is one of several reasons why we made the decision.

Going to close this as a duplicate accordingly

**Closed by calebcartwright** 2021-07-04 15:33 UTC
