### ISSUE TITLE
Feature Request: Icon URL parameter to use any 3rd party icon from the internet

### ISSUE THREAD

**Issue by HariSekhon** [badges/shields#9143] opened 2023-05-05 03:04 UTC
:clipboard: **Description**

Sometimes the icons you want for badges aren't available on [simpleicons.org](https://simpleicons.org/).

I've recently been using the awesome new [D2 language](d2lang.com) for diagrams-ad-code and it's core functionality includes an icon url field which automatically pulls any icon you give it by URL to include it in the generated diagram.

Can [shields.io](https://shields.io/) be enhanced to allow passing a parameter similar to `logo` that just pulls the icon dynamically from the web?

So instead of:

```
?logo=python
```

I propose:

```
?logoUrl=https://.../path/to/icon.png
```
or
```
?logoUrl=https://.../path/to/icon.svg
```

or using the existing `logo` parameter as is done with custom logos:

```
?logo=https://.../path/to/icon.svg
```

I've found the doc on custom logos:

https://github.com/badges/shields/blob/master/doc/logos.md#custom-logos

which says that you can base64 encode a logo and pass it as data.

I've used this and it works, but I think it would be cleaner to pass a URL in the README shields badge and just have [shields.io](https://shields.io/) do the conversion.

It would certainly be cleaner and more readable in everybody's READMEs rather than having to go around embedding big base64 strings in them.

Relates to this discussion too: https://github.com/badges/shields/discussions/6882

**Comment by calebcartwright** [comment] 2023-05-07 20:15
Thanks but going to close as this is a duplicate of many prior requests for the same, see https://github.com/badges/shields/issues/8843#issuecomment-1401411190 and the various issues & discussions linked within for more info

**Closed by calebcartwright** 2023-05-07 20:15 UTC
