### ISSUE TITLE
All shields down

### ISSUE THREAD

**Issue by RIAEvangelist** [badges/shields#540] opened 2015-09-25 02:30 UTC
They are all broken.

![down shields](http://i.imgur.com/KNKnq3F.png)

**Comment by espadrine** [comment] 2015-09-25 06:16
Thanks for notifying us! It should be fixed now.

**Closed by espadrine** 2015-09-25 06:16 UTC

**Comment by SimenB** [comment] 2015-09-30 05:27
Down now as well.

![image](https://cloud.githubusercontent.com/assets/1404810/10185101/b2084e46-6744-11e5-8e38-963d81bfe7fa.png)

**Comment by espadrine** [comment] 2015-09-30 08:23
Thanks! It's up again. I have a couple of ideas of what may be causing this, I'll try exploring them.

**Comment by RIAEvangelist** [comment] 2015-09-30 19:59
should issue remain open in that case?

**Comment by espadrine** [comment] 2015-09-30 20:56
There is more information and history here, if you want to subscribe: https://github.com/badges/shields/issues/481

**Comment by RIAEvangelist** [comment] 2015-09-30 22:40
thanks

**Comment by arcanedev-maroc** [comment] 2015-11-19 15:58
@espadrine the badges are down again

**Comment by espadrine** [comment] 2015-11-19 16:18
@arcanedev-maroc Thanks for noticing. It restarted itself automatically. It seems to have been caused by an oom-kill.

**Comment by bogdanRada** [comment] 2015-12-17 06:05
it is down again. Currently getting error 522

**Comment by espadrine** [comment] 2015-12-17 21:38
Yet again, it seems that it restarted itself.
