### ISSUE TITLE
Not valid Github status badge for broken workflow

### ISSUE THREAD

**Issue by dmvict** [badges/shields#8146] opened 2022-07-01 06:23 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

I noticed that `shields.io` provide status badge `passing` for broken workflow

![image](https://user-images.githubusercontent.com/47529590/176834948-c0569144-a9a5-49ab-8f6f-917962ef0236.png)

The real results is : 

![image](https://user-images.githubusercontent.com/47529590/176835200-5a1494dd-f0ca-4f44-8c8f-a9734fbf568b.png)

[The link to the workflow run](https://github.com/Wandalen/wTools/actions/runs/2591315400) on the screenshot. [Repository](https://github.com/Wandalen/wTools) where shields.io status badges are used. 

The badge works well with valid workflow files. And this workflow is fixed now. Please, try to reproduce and fix the bug.

### 🔗 Link to the badge

https://img.shields.io/github/workflow/status/Wandalen/wTools/mod_interface?label=

**Comment by chris48s** [comment] 2022-07-01 21:00
Our badges for github workflows are basically just "scrapers" for github's own badges so when you call https://img.shields.io/github/workflow/status/Wandalen/wTools/mod_interface/alpha it calls https://github.com/Wandalen/wTools/workflows/mod_interface/badge.svg?branch=alpha and then reports the value from that. It is essentially just a "wrapper" that allows you to use the full range of shields styles. Looks like your builds are now fixed so I now can't reproduce it but if you can break one again, check the actual github badges and see what value you've got.

**Comment by dmvict** [comment] 2022-07-01 21:24
> 

I missed this screenshot in the issue description
![image](https://user-images.githubusercontent.com/47529590/176968383-194f5282-b35b-4ec1-b979-af6de4173c40.png)

The screenshot was maiden just before the issue was opened. So, the bug exists, and the working case for the bug is a broken workflow.

If I will have time to test this scenario, then I will report the results. 
I will close the issue after approval of the correct badge work for the described case.

**Comment by calebcartwright** [comment] 2022-07-01 22:18
Unfortunately I suspect this is reflective of some upstream changes GitHub have rolled out, relative to #7102

Here's what GitHub shows for some of your branches (screen grab at the bottom in case statuses change)
https://github.com/Wandalen/wTools/actions/workflows/ModuleModInterfacePush.yml/badge.svg?branch=master
![](https://github.com/Wandalen/wTools/actions/workflows/ModuleModInterfacePush.yml/badge.svg?branch=master)
https://github.com/Wandalen/wTools/workflows/mod_interface/badge.svg?branch=master
![](https://github.com/Wandalen/wTools/workflows/mod_interface/badge.svg?branch=master)

It looks like GitHub updated the docs back in https://github.com/github/docs/pull/3802/files#diff-95d58394efa588c4f92f85274259efb8ca1e10a02bd346549e65b57604c156c4. However, I think that there's either a new(ish) issue in the original, by-name endpoint, or that GitHub have just recently rolled out the changes.

As Chris noted we rely on the upstream providers to deliver information, which is what we then use. In this case the endpoint that we've always used for Workflow Status is claiming your master branch is passing, so that's what is being displayed.

I think this is something that needs to be tracked down with GitHub to get a definitive answer. We can't simply "just switch" to the workflow file name model either as that would break our existing users which is not something we want to do if GitHub plan to fix the by-name endpoint.


![image](https://user-images.githubusercontent.com/13042488/176973595-d8e21fdb-92fd-440f-8650-15a1f6e33d67.png)

**Comment by exoRift** [comment] 2022-08-14 01:39
@calebcartwright What if we have it fetch legacy first and if it's a 404, fetch the new URL?

**Comment by calebcartwright** [comment] 2022-08-14 15:50
That's an interesting idea @exoRift. I think I could get behind that as a tactical solution (since the badges currently appear to be broken for half the audience), so long as we keep tracking towards something more long term.

@chris48s would you have any concerns with this? I feel like it should be simple enough at the code level, and not like it would have any tangible impact on our token pool nor the traffic volume we throw github's way

**Comment by chris48s** [comment] 2022-08-14 20:11
So if we think

https://github.com/exoRift/react-fluent-mobile/workflows/Quality%20Assurance/badge.svg?branch=master is returning inaccurate or out-of-date info

and

https://github.com/exoRift/react-fluent-mobile/actions/workflows/quality_assurance.yml/badge.svg?branch=master is correct,

I think trying to serve information we believe is wrong or outdated first is the wrong call. I think there are really 2 sensible things we can do:

### Option 1:
- Create a new badge route that accepts the workflow file name as the param and call `/actions/workflows/<WORKFLOW_FILE>` to get the data
- Retire/deprecate our existing route, stop serving data and show some kind of error message advising users to switch

### Option 2:
Overload the existing route to take a generic `:param` which could be a workflow filename or name, but do it the other way round:
- Try to call `/actions/workflows/<param>` first
- Fall back to `/workflows/<param>` second

Option 2 has the advantage that all the existing badges out there in the wild will still "work", but if we think they are serving stale/inaccurate data then this is not necessarily much of an "advantage". I think serving an error saying "you need update your badge URL" is ultimately more useful then "here's a value that might not be right"

I guess the thing I'd like to be slightly more sure of is: what is the status of the `/workflows/<WORKFLOW_NAME>` endpoint we are currently using? It is certainly still returning _some data_. Beyond anec-data: The commit where this  changed in the GitHub docs is https://github.com/github/docs/commit/f9b50ac4387b46f8a3ca80ede226fb15384ff7f3 but it has no useful info in the commit message and the linked issue is a 404 so the trail goes cold there.

**Comment by calebcartwright** [comment] 2022-08-17 01:07
> I think trying to serve information we believe is wrong or outdated first is the wrong call.

Good point. I'd already forgotten that the two endpoints need different inputs

> I guess the thing I'd like to be slightly more sure of is: what is the status of the /workflows/<WORKFLOW_NAME> endpoint we are currently using? It is certainly still returning some data. Beyond anec-data: The commit where this changed in the GitHub docs is https://github.com/github/docs/commit/f9b50ac4387b46f8a3ca80ede226fb15384ff7f3 but it has no useful info in the commit message and the linked issue is a 404 so the trail goes cold there.

Yup, I'd found that too and expressed some of the same thinking earlier in the thread. It's an odd scenario and I'm not sure the best way to get in touch with GitHub for a definitive answer on this particular item. Guess we can try the user forum

**Comment by renanrcp** [comment] 2022-09-21 01:11
## I have a proposal for this issue:

- Add the `(legacy)` suffix in the name of all the current Github badges with the old path.
- Create new badges and new endpoints for the newer Github path, eg. the old path is `/github/workflow/status/:user/:repo/:workflow` the new can be `/github/actions/workflow/status/:user/:repo/:workflowFileName`

## Images example:

### Current behavior:

![image](https://user-images.githubusercontent.com/46636310/191390859-4249f8c7-fadb-49cb-9799-d6d8f7d86669.png)

### Proposed new behavior:
![image](https://user-images.githubusercontent.com/46636310/191391872-189b8c86-fbaa-4a81-a5b9-381cc6852a7b.png)

I am willing to do the PR too if this proposal eventually is approved 😉

<details>
  <summary>For now, I've created a Vercel app that uses the json badge for any people with this problem:</summary><br>
   Example for my repo <a href="https://github.com/NextAudio/NextAudio">NextAudio</a><br><br>
   Shields.io badge: <br>
   <img src="https://img.shields.io/github/workflow/status/NextAudio/NextAudio/.NET"> <br><br>
   App badge (using Shields.io json option): <br>
   <img src="https://img.shields.io/endpoint?url=https://github-workflow-status-badge.vercel.app/api/NextAudio/NextAudio/build-test-lint.yml"><br><br>
   <a href="https://github.com/renanrcp/github-workflow-status-badge">App Repo</a> <br>
   <a href="https://github-workflow-status-badge.vercel.app/">App Url</a>
</details>

**Comment by chris48s** [comment] 2022-09-21 19:40
Tbh, I'd rather just deprecate it rather than keep around a a "legacy" version if we can't rely on the data.

I've started a discussion over at https://github.com/orgs/community/discussions/33739 to try and get an answer. If we don't get to the bottom of it there, I'll try contacting support.

**Comment by chris48s** [comment] 2022-09-26 19:00
Nobody replied to https://github.com/orgs/community/discussions/33739
I've now raised a ticket with github support

**Comment by chris48s** [comment] 2022-09-29 17:15
I got this message back from support, which is quite helpful and does explain what is happening:

> Thank you for your patience while we investigated this.
> 
> I have been updated that the file name route is the recommended route and therefore the only one we currently document. The old badge route had some issues disambiguating between workflows with the same name, handling renames, etc. We no longer document that format.
> 
> Looking at the first example :
> 
> * one quirk in both versions of badges is that they first check for matching runs on the default branch (in this case, main) if no branch is provided. If none are found, it will fall back to querying all branches
> 
> * https://github.com/NextAudio/NextAudio/workflows/.NET/badge.svg searches for a run on the main branch across all workflows named ".NET". It finds https://github.com/NextAudio/NextAudio/actions/runs/1565789342 from 10 months ago. This run looks to be from a now-deleted workflow file build.yml. This is the run whose status is being displayed
> 
> * https://github.com/NextAudio/NextAudio/actions/workflows/build-test-lint.yml/badge.svg is only querying runs for the specific workflow build-test-lint.yml. There are none on the default branch, so it falls back to all branches and displays the status of https://github.com/NextAudio/NextAudio/actions/runs/3138965027
> 

I think my conclusion from this is that we should:

* Create a new badge route that accepts the workflow file name as the param and call `/actions/workflows/<WORKFLOW_FILE>` to get the data
* Deprecate our existing route instead of keeping it around, given it has some known spurious behaviours

I'll submit a PR doing this next week (I'm going to be away for a few days), unless someone wants to jump on it over the weekend.

**Comment by chris48s** [comment] 2022-12-15 18:47
See https://github.com/badges/shields/issues/8671 for the details of the fix for this

**Closed by chris48s** 2022-12-15 18:47 UTC
Labels: question, needs-upstream-help, service-badge

**Comment by alisafi93** [comment] 2023-01-23 21:59
> ### هل تواجه مشكلة مع ...
> الدروع
> 
> ### 🐞وصف
> لقد لاحظت أن `shields.io`تقديم شارة الحالة `passing`لسير العمل المعطل
> 
> ![صورة](https://user-images.githubusercontent.com/47529590/176834948-c0569144-a9a5-49ab-8f6f-917962ef0236.png)
> 
> النتائج الحقيقية هي:
> 
> ![صورة](https://user-images.githubusercontent.com/47529590/176835200-5a1494dd-f0ca-4f44-8c8f-a9734fbf568b.png)
> 
> [الارتباط إلى سير العمل يعمل](https://github.com/Wandalen/wTools/actions/runs/2591315400) على لقطة الشاشة. [المستودع](https://github.com/Wandalen/wTools) حيث يتم استخدام شارات حالة shields.io.
> 
> تعمل الشارة بشكل جيد مع ملفات سير العمل الصالحة. وقد تم إصلاح سير العمل هذا الآن. من فضلك ، حاول إعادة إنتاج وإصلاح الخطأ.
> 
> ### 🔗رابط للشارة
> [https://img.shields.io/github/workflow/status/Wandalen/wTools/mod_interface؟label=](https://img.shields.io/github/workflow/status/Wandalen/wTools/mod_interface?label=)
> 
> ### 💡حل ممكن
> _لا يوجد رد_
