### ISSUE TITLE
Shield server URL authentication

### ISSUE THREAD

**Issue by asharabu** [badges/shields#6167] opened 2021-02-12 12:05 UTC
Hi,

I could set up our own shield server in a Docker environment using the [document ](https://github.com/badges/shields/blob/master/doc/self-hosting.md).  Can setup authentication for this URL, now anyone can access this as it has no authentication.
![image](https://user-images.githubusercontent.com/42669995/107758155-80285100-6d4c-11eb-9224-68e98fb2c1cf.png)

**Comment by calebcartwright** [comment] 2021-02-12 17:46
hello @asharabu, thanks for reaching out! The Shields server codebase, and associated features, are developed and maintained to support the Shields.io service which is the main way users interact with our platform. The Shields.io service is very much by design an anonymous platform, which is why Shields.io and the associated server does not require auth to provide badges.

There are some instances when folks need to self-host their own Shields server, such as when you want badges from a platform that is not internet facing/accessible to Shields.io (e.g. a private Jira server on your corporate network) or badges for a project/user that is private (e.g. a private GitHub repository). We try to make it relatively straightforward for folks to self-host a Shields server to support these use cases, but we also don't develop the server code to explicitly provide features that aren't applicable for Shields.io or which could have drawbacks on the main Shields.io use case.

Incorporating authentication/authorization at the Server level is an example of this, because it has no value/practical use case for Shields.io. I don't anticipate this changing.

It looks like you're running your Server on a private address, which heavily implies you have options for some networking-imposed access restrictions around who can actually get to your self-hosted Server, and this is our typical recommendation for folks that want to restrict access.

If you really want some level auth for badges from your self-hosted Server, then you'd probably want to look at putting something like nginx in front of your Server. It's important to remember though that the core use case of a badge server is actually serving up the badges that users will then embed somewhere, most often in a markdown file in source control, so if you decide to pursue an auth layer make sure that it's compatible with how you/your users are actually planning to use the badges.

**Comment by PyvesB** [comment] 2021-04-25 07:33
Completely agree with @calebcartwright's reasoning. Will go ahead and close this issue for now. 😉

**Closed by PyvesB** 2021-04-25 07:33 UTC
Labels: question
