### ISSUE TITLE
Adding ?maxAge to all shields on the website breaks a few of them

### ISSUE THREAD

**Issue by fordhurley** [badges/shields#697] opened 2016-04-21 13:52 UTC
It looks like there was an attempt to get the website to more heavily cache all of the example images, but the implementation has some problems. Commit 89affa49f added `?maxAge= 2592000` to the end of every sheilds img url, but some of them already had other query parameters. This broke the parameter parsing. Examples:

![](https://img.shields.io/badge/style-flat--squared-green.svg?style=flat-square?maxAge=2592000)

```
https://img.shields.io/badge/style-flat--squared-green.svg?style=flat-square?maxAge=2592000
```

![](https://img.shields.io/gratipay/Shields.svg?style=social&label=Donate?maxAge=2592000)

```
https://img.shields.io/gratipay/Shields.svg?style=social&label=Donate?maxAge=2592000
```

While I appreciate the simplicity of the solution, it's obviously flawed. This is your friendly reminder that [parsing html with regex is never a good idea](http://stackoverflow.com/a/1732454/576932).

I'd be happy to submit a PR to fix this, but I would want some input from the maintainers on the preferred direction to go. Introduce a templating language? Manually add the `maxAge` param to each and remove it from the Makefile? Further complicate the regex so that it checks that a `?` isn't already present in the url, the conditionally prepends then param with a `?` or `&` as necessary (please no)?

**Comment by hugovk** [comment] 2016-04-25 13:50
Duplicate of https://github.com/badges/shields/issues/693?

**Comment by fordhurley** [comment] 2016-04-25 23:51
You're right, these are duplicates, I hadn't seen the other when I created the issue. Though, I think this issue more accurately describes the root problem, and shows that it also breaks the style examples.

**Comment by espadrine** [comment] 2016-04-26 07:52
Thanks for reporting!

> While I appreciate the simplicity of the solution, it's obviously flawed. This is your friendly reminder that parsing html with regex is never a good idea.

This is absolutely true (although I'd add that this particular problem would also require a URL parsing library), which is why I chose to fix it with MOAR REGEX

> (please no)

SORRY

**Closed** 2016-04-26 07:52 UTC
