### ISSUE TITLE
Badges for coverity

### ISSUE THREAD

**Issue by kyrias** [badges/shields#405] opened 2015-04-06 14:33 UTC
The coverity badges look rather broken, and it would be nice if there was shield.io support for it.

**Comment by kyrias** [comment] 2015-04-07 18:48
Finally managed to get it to work after noticing that the coverity badges has extra whitespace… Will send a PR in a little while.

**Comment by espadrine** [comment] 2015-04-11 20:51
As you realized, this is a duplicate of #325. Let's make your PR close the original bug.

**Closed by espadrine** 2015-04-11 20:51 UTC
