### ISSUE TITLE
Bintray badge is flaky

### ISSUE THREAD

**Issue by agemooij** [badges/shields#658] opened 2016-02-25 11:04 UTC
The Bintray badge seems to be broken; all versions are rendered as a grey "invalid".

Perhaps the API has changed? I've tested with multiple repositories but the example on shields.io itself is also broken:

[ ![Current Version](https://img.shields.io/bintray/v/asciidoctor/maven/asciidoctorj.svg) ](https://bintray.com/asciidoctor/maven/asciidoctorj/_latestVersion)

**Comment by migmruiz** [comment] 2016-03-10 14:15
Having the same issue here

**Comment by xvik** [comment] 2016-03-16 15:04
It works sometimes, but mostly not. Could it be caused by [bintray api limits](https://bintray.com/docs/api/#_limits)?

**Comment by nwalters512** [comment] 2016-03-30 22:24
Can confirm that this is still an issue. It was working yesterday, but all Bintray badges (at least the one for my project and the example from shields.io) are currently showing "invalid".

**Comment by raniejade** [comment] 2016-04-06 11:12
Badge is broken for my project as well. Rate limiting is very likely the culprit.

**Comment by espadrine** [comment] 2016-07-02 11:22
The request performed is `curl -v 'https://bintray.com/api/v1/packages/asciidoctor/maven/asciidoctorj/versions/_latest'`. I cannot find a `X-RateLimit-Limit` header in the response. Is this issue still ongoing? Did they switch their rate limiting system?

**Comment by cdeszaq** [comment] 2016-09-28 02:39
As of today, the issue is still present. Does anyone have contacts at Bintray to see if we can resolve this?

**Comment by xvik** [comment] 2016-09-28 08:50
Here is what bintray support answered about this issue:

> Thank you for contacting us.
> We were not able to reproduce this behaviour using a custom shield.
> We also verified that the 'getLatestVersion' API is not rate limited so this does not appear to be the issue.

So there are no limits on bintray side and probably the problem is on the shields side. 

Dear shield maintainers, please look actual error messages in your logs and try to investigate this.

P.S. I also asked bintray support to allow bintray badge customization (different message), but don't know if this ever happen:
> We have forwarded your request to our Product Team and will consider adding the option to customise the badge.

**Comment by Fi5t** [comment] 2016-10-31 18:39
The badge has broken again...

**Comment by paulmelnikow** [comment] 2017-04-07 12:23
It looks like the badge has been flaky for a long time.

Unfortunately the server doesn't log all the API calls. So I think the way to resolve this long-standing issue is to set up a recurring test over a week or more, and send documentation of the failures to their support.

If anyone is game, would be great to have your help!

**Comment by laughedelic** [comment] 2017-09-25 12:50
Still a problem. From the example on shields.io:

<img width="733" alt="screen shot 2017-09-25 at 14 39 07" src="https://user-images.githubusercontent.com/766656/30809079-d4e33932-a200-11e7-845c-49fd583d33f7.png">

**Comment by paulmelnikow** [comment] 2018-06-16 21:18
Copying from above: I think the way to resolve this long-standing issue is to set up a recurring test over a week or more, and send documentation of the failures to their support. If anyone is game, would be great to have your help!

**Comment by tovbinm** [comment] 2018-08-16 05:54
Just FYI, Bintray seem to have their own badge now. But it would still be nice to have the Shields one.

**Comment by enveeed** [comment] 2019-03-13 11:30
It is possible to use the Shields badge via the dynamic endpoint using the URL for the Bintray API and `query=name`, which seems to work for me when the normal bintray badge displays 'invalid', e.g. using

```
https://bintray.com/api/v1/packages/asciidoctor/maven/asciidoctorj/versions/_latest
```

```
https://img.shields.io/badge/dynamic/json.svg?label=latest&query=name&style=flat-square&url=https%3A%2F%2Fapi.bintray.com%2Fpackages%2Fasciidoctor%2Fmaven%2Fasciidoctorj%2Fversions%2F_latest
```

---

![dynamic](https://img.shields.io/badge/dynamic/json.svg?label=latest&query=name&style=flat-square&url=https%3A%2F%2Fapi.bintray.com%2Fpackages%2Fasciidoctor%2Fmaven%2Fasciidoctorj%2Fversions%2F_latest)
`https://img.shields.io/badge/dynamic/`

![bintray](https://img.shields.io/bintray/v/asciidoctor/maven/asciidoctorj.svg?label=version&style=flat-square)
`https://img.shields.io/bintray/`

**Comment by Andre601** [comment] 2019-10-18 15:04
I can confirm that this issue still exists.

**Comment by calebcartwright** [comment] 2019-10-18 15:23
Interestingly enough, it seems that the API call we use does not require any authentication for public packages:

https://bintray.com/docs/api/#_get_version
https://bintray.com/api/v1/packages/asciidoctor/maven/asciidoctorj/versions/_latest

And when I remove auth in our call, the badges work just fine

https://github.com/badges/shields/blob/7a7bf66233c1b5d5092b995d52f3a55bc9bfa20c/services/bintray/bintray.service.js#L47-L54

**Comment by calebcartwright** [comment] 2019-10-18 15:42
https://shields-staging-pr-4217.herokuapp.com/bintray/v/asciidoctor/maven/asciidoctorj
![](https://shields-staging-pr-4217.herokuapp.com/bintray/v/asciidoctor/maven/asciidoctorj)

**Comment by calebcartwright** [comment] 2019-10-18 16:09
@paulmelnikow - do you know if we have `bintray_username` and/or `bintray_password` set on the prod badge servers?

**Comment by paulmelnikow** [comment] 2019-10-19 00:59
Yes, they are both set. I think the auth was added not for private projects, but because it provided a higher rate limit.

We could try creating a second token and an auth pool for Bintray… though maybe they could give us a megatoken instead? Has anyone managed to reach them?

**Comment by calebcartwright** [comment] 2019-10-19 15:54
I'm thinking we may be able to solve this by unsetting `bintray_user` and `bintray_apikey` on the badge servers. 

Support for bintray goes _way_ back in Shields' history, so apologies if I've missed any relevant threads or discussion. 

From what I can tell, when bintray support was first added, the bintray API we use to get the latest version **required** authentication
https://github.com/badges/shields/issues/58
https://github.com/badges/shields/pull/517

As such, our calls were subject to the [rate limits imposed by JFrog](https://bintray.com/docs/api/#_authentication)
> The current limit per non-Premium user is 300 queries a day, and 1440 per month. Limits are returned in the X-RateLimit headers.


However, at some point over the years, JFrog made the bintry API available anonymously and non-rate limited for public packages (private packages still require auth), which would explain the response from the JFrog Support team that was shared [above](https://github.com/badges/shields/issues/658#issuecomment-250109117)

https://bintray.com/docs/api/#_get_version
> Security: Authenticated user with 'read' permission for private repositories, or version read entitlement.

For example: 
https://bintray.com/api/v1/packages/asciidoctor/maven/asciidoctorj/versions/_latest
```json
{ 
  "name":"2.1.0",
  "desc":null,
  "package":"asciidoctorj",
  "repo":"maven",
  "owner":"asciidoctor",
  "labels":[ 
    "asciidoctor",
    "java",
    "asciidoctorj",
    "asciidoc",
    "jruby"
  ],
  "published":true,
  "attribute_names":[ 

  ],
  "created":"2019-06-22T16:33:07.367Z",
  "updated":"2019-06-22T16:48:02.333Z",
  "released":"",
  "ordinal":36.0,
  "rating_count":0
}
```
Since we've got bintray auth configured on the badge servers, we're (IMO) unnecessarily authenticating and subjecting our calls to rate limiting which is resulting in the flaky badge behavior we are seeing. 

There is another issue (#1193) requesting bintray download count badges, and the [bintray APIs needed for download stats](https://bintray.com/docs/api/#_get_daily_downloads) _will_ require auth, but I think we can tackle the auth/rate limiting over there.

**Comment by paulmelnikow** [comment] 2019-10-19 16:06
Okay, I'm game to remove the credentials on the next deploy and see how it goes!

**Comment by calebcartwright** [comment] 2019-10-19 16:11
🤞

**Comment by calebcartwright** [comment] 2019-10-22 19:16
Were the creds removed on the last deploy? If so I'll try to keep checking on the badges to see if we get any more `invalid`'s

**Comment by paulmelnikow** [comment] 2019-10-22 21:51
Yes, they were. I'm rolling back the code now, but the creds will remain out.

**Comment by calebcartwright** [comment] 2019-10-26 14:59
AFAICT the bintray badges have been consistently working since we removed the creds. Has anyone seen anymore `invalid` badges in the last 4 days?

**Comment by calebcartwright** [comment] 2019-10-31 15:45
It's been over a week since the change was made and it appears this has been resolved. I'm going to close this issue out accordingly

**Closed by calebcartwright** 2019-10-31 15:45 UTC
Labels: bug, needs-upstream-help, operations, service-badge

**Comment by mpetuska** [comment] 2020-07-12 20:29
Could potentially be replaced with https://bintray.com/api/ui/package/:subject/:repo/:package which returns a lot of info including {..., "latestVersion": "x.y.z-M..."}
