### ISSUE TITLE
Broken heading anchors

### ISSUE THREAD

**Issue by PyvesB** [badges/shields#1954] opened 2018-08-22 18:08 UTC
Links with heading anchors no longer seem to work on our homepage, for instance:
https://shields.io/#your-badge

As a consequence, our Readme link named _Make your own badges!_ is broken and shows a blank page rather than bringing the user to the appropriate section on _shields.io_.

**Comment by chris48s** [comment] 2018-08-22 18:47
Good spot. Hadn;t though of this. It will be because we're now using react-router's HashRouter for the frond-end routing.

Doing a quick google, there are workaround but I _think_ [this package](https://github.com/rafrex/react-router-hash-link) exists to fix this problem, but I've not tried it.

**Comment by paulmelnikow** [comment] 2018-08-23 16:44
Another option would be to make a new page at `your-badge` for the "your badge" bit, and leave a shorter version on the home page.

**Comment by calebcartwright** [comment] 2018-08-31 00:47
I assume this is related (and thus already known), but opening any of the example pages in a new browser tab results in a 404 error. For example when opening the first item **build** in a new tab uses: https://shields.io/examples/build vs. https://shields.io/#/examples/build

**Comment by paulmelnikow** [comment] 2018-08-31 02:41
Huh, I can't reproduce that. Could you clarify?

**Comment by calebcartwright** [comment] 2018-08-31 02:53
Steps to reproduce (I'm seeing this on Windows, haven't checked Ubuntu)

1) Open web browser (occurs for me in Chrome, Firefox, Edge, and IE) to https://shields.io/ 
2) Right click on any of the category links listed at top of page (build, chat, dependencies, etc.)  -> open in new tab
3) New tab opens with http 404 error page

**Comment by paulmelnikow** [comment] 2019-02-06 22:58
This could be tackled now that #2906 is merged. I think it would be fixed by removing `your-badge` as an element ID and making it an anchor… I'm having a case of, "how did this ever work?" 😁

**Closed** 2019-02-20 21:34 UTC
Labels: bug, frontend
