### ISSUE TITLE
Docker builds PB?

### ISSUE THREAD

**Issue by fauust** [badges/shields#4663] opened 2020-02-19 15:03 UTC
:clock11: **When did the problem start?**

I don't know...

:camera: **Live badge**

https://img.shields.io/docker/build/fauust/docker-systemd-debian10?logo=docker

[![docker build status](https://img.shields.io/docker/build/fauust/docker-systemd-debian10?logo=docker)](https://hub.docker.com/r/fauust/docker-systemd-debian10)

:wrench: **Is the live badge working?**

No, it says "repo not found"

**Comment by calebcartwright** [comment] 2020-02-19 16:04
Hi @fauust 

You need to use the Docker cloud build badge, not the old build badge which exists to support repos created before the Docker hub merge a few years ago

https://img.shields.io/docker/cloud/build/fauust/docker-systemd-debian10?logo=docker
![](https://img.shields.io/docker/cloud/build/fauust/docker-systemd-debian10?logo=docker)

Refs/duplicate of #1400, #3140, and #4493,

**Closed by calebcartwright** 2020-02-19 16:04 UTC
Labels: keep-service-tests-green
