### ISSUE TITLE
Discord badge from invite instead of guild ID

### ISSUE THREAD

**Issue by MicaelJarniac** [badges/shields#9142] opened 2023-05-04 18:10 UTC
### 📋 Description

- Service: Discord
- Information: Similar to the Discord badge currently available

Current badge:
`![Discord](https://img.shields.io/discord/<GUILD_ID>)`

![Discord](https://img.shields.io/discord/308323056592486420)

DIY new badge:
`[![Discord](https://img.shields.io/badge/dynamic/json?color=green&label=chat&query=%24.approximate_presence_count&suffix=%20online&url=https%3A%2F%2Fdiscord.com%2Fapi%2Fv10%2Finvites%2F<INVITE_CODE>%3Fwith_counts%3Dtrue)](https://discord.gg/<INVITE_CODE>)`

[![Discord](https://img.shields.io/badge/dynamic/json?color=success&label=chat&query=%24.approximate_presence_count&suffix=%20online&url=https%3A%2F%2Fdiscord.com%2Fapi%2Fv10%2Finvites%2FHjJCwm5%3Fwith_counts%3Dtrue)](https://discord.gg/HjJCwm5)

A Discord badge generated by providing an invite code, instead of the guild ID.

Invite codes look like `HjJCwm5` (this one is Shields' Discord).

Having the `<INVITE_CODE>` also allows the generated badge Markdown to be clickable to join the server:
```md
[![Discord](https://img.shields.io/discord/invite/<INVITE_CODE>)](https://discord.gg/<INVITE_CODE>)
```

I believe this doesn't even require the widget setting to be enabled on the guild.

### 🔗 Data

Data can be fetched like so:
`https://discord.com/api/v10/invites/<INVITE_ID>?with_counts=true`
| Field | Description |
| -- | -- |
| `guild.id` | guild ID |
| `approximate_member_count` | approximate member count |
| `approximate_presence_count` | approximate online members |
| `expires_at` | expiration, if any |

`expires_at` could be used to warn the user, when creating a badge, if they try to use an invite that expires. This may require adding the query parameter `with_expiration=true`.

<details>
<summary>Example data with Shields' invite</summary>

https://discord.com/api/v10/invites/HjJCwm5?with_counts=true

```json
{
  "code": "HjJCwm5",
  "type": 0,
  "expires_at": null,
  "guild": {
    "id": "308323056592486420",
    "name": "shields",
    "splash": null,
    "banner": null,
    "description": null,
    "icon": "11a50197f2858fa14b74f41ceaacc4b6",
    "features": [],
    "verification_level": 1,
    "vanity_url_code": null,
    "premium_subscription_count": 0,
    "nsfw": false,
    "nsfw_level": 0
  },
  "channel": {
    "id": "308323056592486420",
    "name": "contributing",
    "type": 0
  },
  "inviter": {
    "id": "306496561301684224",
    "username": "paulmelnikow",
    "global_name": null,
    "display_name": null,
    "avatar": "7667ed8ea335982730a320c36102fc32",
    "discriminator": "9778",
    "public_flags": 0,
    "avatar_decoration": null
  },
  "approximate_member_count": 632,
  "approximate_presence_count": 46
}
```
</details>

- https://discord.com/developers/docs/reference
- https://discord.com/developers/docs/resources/invite

### 🎤 Motivation

This would simplify making a Discord badge (no need to enable the widget option on the guild), would make it so the badge is clickable to join the guild, and would result in a shorter badge URL (invite codes are shorter than guild IDs).

**Comment by calebcartwright** [comment] 2023-05-07 20:16
Thanks but closing as a duplicate of existing discussion in #4500, #9098, #5079 and others

**Closed by calebcartwright** 2023-05-07 20:16 UTC
Labels: service-badge
