### ISSUE TITLE
readme: badge logo broken

### ISSUE THREAD

**Issue by tooomm** [badges/shields#1301] opened 2017-12-01 11:05 UTC
![badge_readme](https://user-images.githubusercontent.com/9874850/33480029-ae7d0ac0-d68f-11e7-8820-284335af43d1.png)

It would make sense to include the official logo in the repo and link to that location instead.

I want to mention that the "twitter" social badge is only shown on chrome to me.
On Firefox (see pic) it's just not there.

**Comment by paulmelnikow** [comment] 2017-12-01 14:29
I fixed the logo.

I can't reproduce the Firefox issue with the Twitter badge. It does seem to load slower than the other badges. Maybe a transient issue? If you refresh, does it appear?

**Comment by tooomm** [comment] 2017-12-01 14:34
No, reloading doesn't change anything.

`uBlock Origin` seems to block it. Even though it is no official (tracking) badge from twitter...

**Comment by paulmelnikow** [comment] 2017-12-01 14:36
Right, nothing would be tracked unless the user clicks. Worth reporting to them?

**Comment by tooomm** [comment] 2017-12-01 14:51
Using the logger, the list `Fanboy’s Annoyance List` is triggering on `https://twitter.com/intent/follow?`.

One would have to report at their forums, which I'm not registered with: https://forums.lanik.us/

**Comment by paulmelnikow** [comment] 2017-12-01 15:20
Okay, will close this then, since it's not a problem with Shields.

**Closed by paulmelnikow** 2017-12-01 15:20 UTC
Labels: operations
