### ISSUE TITLE
Wrong composer version

### ISSUE THREAD

**Issue by theofidry** [badges/shields#510] opened 2015-08-17 23:26 UTC
I have [a library](https://packagist.org/packages/hautelook/alice-bundle) registered on [packagist](https://packagist.org/) for which the two lasts versions are `v1.0.0-beta` and `0.2`. Although the order is correct on packagist, the shields badge displays the old version `0.2` instead of the newer one.

Badge link: http://img.shields.io/packagist/v/hautelook/alice-bundle.svg

**Comment by espadrine** [comment] 2015-08-23 15:41
Thanks for pointing this out!

`/v/` is designed to ignore prerelease versions. You may want to try `http://img.shields.io/packagist/vpre/hautelook/alice-bundle.svg` instead.

Does this address your issue? Should this be made more clear? If you think the issue is addressed, don't hesitate to close the issue.

**Comment by theofidry** [comment] 2015-08-23 15:45
Indeed it works, but it would be nice to have it specified somewhere!

**Closed** 2015-08-23 15:51 UTC
