### ISSUE TITLE
dockercloud builds are failing

### ISSUE THREAD

**Issue by chris48s** [badges/shields#4808] opened 2020-03-22 11:44 UTC
Looks like this has been consistently failing for the last couple of days.
I don't have a login for dockercloud to get any more info on this.

**Comment by calebcartwright** [comment] 2020-03-23 05:09
I'm not sure what is up with the link from the PR check, but seems to be failing during dependency install due to Cypress (for some reason :thinking:)
 
https://hub.docker.com/repository/registry-1.docker.io/shieldsio/shields/builds/30289177-3125-4f59-afcc-343c188829cf

```bash
Step 5/14 : COPY package.json package-lock.json /usr/src/app/
---> 43eaac92919c
Step 6/14 : COPY gh-badges /usr/src/app/gh-badges/
---> eb54dfede451
Step 7/14 : RUN NODE_ENV=development CYPRESS_INSTALL_BINARY=0 npm ci
---> Running in f6120315507e
[91mnpm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/cypress-io/request.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
[0m
[91m
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-03-22T19_55_06_655Z-debug.log
[0m
Removing intermediate container f6120315507e
The command '/bin/sh -c NODE_ENV=development CYPRESS_INSTALL_BINARY=0 npm ci' returned a non-zero code: 1
```

**Comment by paulmelnikow** [comment] 2020-03-23 15:22
Right. I think the issue is that git it not installed.

Although, the purpose of `CYPRESS_INSTALL_BINARY=0` is to prevent the Cypress install – maybe something changed with that flag? We could also try `--no-scripts`.

**Comment by calebcartwright** [comment] 2020-03-23 15:36
> Although, the purpose of CYPRESS_INSTALL_BINARY=0 is to prevent the Cypress install

Exactly, that's the bit that's puzzling me. 

> maybe something changed with that flag?

I haven't seen anything and their docs still say that's the way to do it :man_shrugging: 
https://docs.cypress.io/guides/getting-started/installing-cypress.html#Environment-variables

**Comment by paulmelnikow** [comment] 2020-03-23 16:08
Looks like a regression in Cypress: cypress-io/cypress#6752

It's fixed, but not yet released. We could downgrade, or wait it out and upgrade.

**Comment by paulmelnikow** [comment] 2020-03-24 15:34
https://github.com/cypress-io/cypress/pull/6777#issuecomment-603081534

The release is scheduled for Monday, and Cypress 4.1.0 doesn't have this issue.

**Comment by paulmelnikow** [comment] 2020-04-06 17:22
The Cypress 4.3.0 update was merged in #4858, and did not seem to fix this problem.

**Comment by paulmelnikow** [comment] 2020-04-06 17:26
Err, maybe that's wrong. Master looks good. Perhaps these PR's that are still failing just need updating.

**Comment by paulmelnikow** [comment] 2020-04-29 20:30
I think this is fixed.

**Comment by PyvesB** [comment] 2021-05-09 16:43
This has been working for a while, therefore closing. :)

**Closed by PyvesB** 2021-05-09 16:43 UTC
Labels: developer-experience, self-hosting
