### ISSUE TITLE
Unable to get next Libraries.io token from pool

### ISSUE THREAD

**Issue by iccicci** [badges/shields#9845] opened 2023-12-26 19:01 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

The badge renders with the error in subject rather the number of dependents

### 🔗 Link to the badge

https://img.shields.io/librariesio/dependents/npm/next-json?logo=npm

### 💡 Possible Solution

Drop Libraries.io and use [npm](https://www.npmjs.com/package/next-json?activeTab=dependents) as source of data

**Comment by iccicci** [comment] 2023-12-28 01:37
This is not a question, this is the report of a problem in production.

Ok, the test passes, but (I guess) just because it uses a distinc pool of tokens from production.

**Comment by chris48s** [comment] 2023-12-28 11:32
I'm going to close this issue as a duplicate of https://github.com/badges/shields/issues/9839 - see there for more details.

In terms of

> Drop Libraries.io and use npm as source of data

The badges we serve from `https://img.shields.io/librariesio/...` are always going to use libraries.io as the source of data.

If you wanted to also implement a NPM dependents badge that gets data from another source, that would be a different badge badge route and a different issue. Although I am not sure NPM actually expose that data via an API.

**Closed** 2023-12-28 11:32 UTC
Labels: question

**Comment by iccicci** [comment] 2023-12-28 16:03
Hi @chris48s , thank you for you kind reply
