### ISSUE TITLE
shields.io domain not resolvable 

### ISSUE THREAD

**Issue by abraunegg** [badges/shields#5341] opened 2020-07-17 21:29 UTC
Are you experiencing an issue with...

- [X] [shields.io](https://shields.io/#/)
- [ ] My own instance
- [ ] [badge-maker NPM package](https://www.npmjs.com/package/badge-maker)

:beetle: **Description**

The IP address for 'sheilds.io' is not resolving:
```
sheilds.io’s server IP address could not be found.
Try running Windows Network Diagnostics.
DNS_PROBE_FINISHED_NXDOMAIN
```
DNS Query:
```
[user@localhost ~]# nslookup sheilds.io
Server:         127.0.0.1
Address:        127.0.0.1#53

** server can't find sheilds.io: NXDOMAIN

[user@localhost ~]# dig sheilds.io

; <<>> DiG xxxxxxx <<>> sheilds.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 39690
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;sheilds.io.                    IN      A

;; AUTHORITY SECTION:
io.                     767     IN      SOA     a0.nic.io. noc.afilias-nst.info. 1497889119 10800 3600 2764800 900

;; Query time: 22 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Jul 18 07:25:35 2020
;; MSG SIZE  rcvd: 91
```

**Comment by calebcartwright** [comment] 2020-07-17 21:35
FYI the domain is shields.io (not sheilds.io), though the same issue exists for our actual shields.io domain. 

I'm thinking this may be cloudflare related

![image](https://user-images.githubusercontent.com/13042488/87832375-7b013300-c84b-11ea-95ae-497967746673.png)

**Comment by calebcartwright** [comment] 2020-07-17 21:37
Yup, cloudflare is back and so is our frontend

https://shields.io/
![image](https://user-images.githubusercontent.com/13042488/87832485-bb60b100-c84b-11ea-9bea-c7033987c65a.png)

**Comment by abraunegg** [comment] 2020-07-17 21:37
@calebcartwright 
Ahh yes .. `typo` .. too early, need another coffee ...

**Comment by calebcartwright** [comment] 2020-07-17 21:38
No worries, I can relate to not being properly caffeinated :laughing: Will leave this open for a while in case Cloudflare is having some ongoing issues, but hopefully just something transient on their end that won't recur

**Comment by abraunegg** [comment] 2020-07-17 21:39
@calebcartwright 
No problem.

**Comment by tegarimansyah** [comment] 2020-07-18 00:15
Just wondering if this is related. Stackoverflow reputation badge returns invalid for today, but yesterday is okay.

![image](https://user-images.githubusercontent.com/11174711/87839701-3cf52500-c8c6-11ea-9ae7-897f99af3eac.png)

I check the user id from its API and result as intended

![image](https://user-images.githubusercontent.com/11174711/87839744-631ac500-c8c6-11ea-8e31-3280b270a28e.png)

**Comment by PyvesB** [comment] 2020-07-18 08:24
A [blog post](https://blog.cloudflare.com/cloudflare-outage-on-july-17-2020/) was written about the Cloudfare incident. No further action needed on our side, closing. :wink:

**Closed by PyvesB** 2020-07-18 08:24 UTC
Labels: needs-upstream-help, operations
