### ISSUE TITLE
Lines of code is showing `0` for several repositories that used to count lines OK

### ISSUE THREAD

**Issue by sgbaird** [badges/shields#7569] opened 2022-02-05 05:54 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

See https://github.com/sparks-baird/mat_discover and https://github.com/sgbaird-5DOF/interp for example. If it's not showing "lines 0" when you open this, then I'll assume this was fixed. Not sure if the issue is on the shields.io side or the `tokei` side.

### 🔗 Link to the badge

https://img.shields.io/tokei/lines/github/sparks-baird/mat_discover
![](https://img.shields.io/tokei/lines/github/sparks-baird/mat_discover)

**Comment by PyvesB** [comment] 2022-02-05 09:41
Hello @sgbaird ! :wave:

Thanks for reporting this! Seems like our [Tokei tests have started failing](https://app.circleci.com/pipelines/github/badges/daily-tests/1497/workflows/79b757da-4b9d-4553-ae04-3197a6428d15/jobs/2399/tests#failed-test-11) as well.

It does seem like a problem on the Tokei side, hitting the API for the [sparks-baird/mat_discover](https://img.shields.io/tokei/lines/github/sparks-baird/mat_discover), I get the following response:
````
{"blanks":0,"code":0,"comments":0,"lines":0,"stats":[],"inaccurate":false}
````

Other users have also reported this problematic behaviour here: https://github.com/XAMPPRocky/tokei/issues/881

**Comment by calebcartwright** [comment] 2022-02-17 02:03
Things appear to have been sorted upstream so going to close. If there's any recurrence in the near term please feel free to post here and we can reopen.

If anyone significantly in the future sees similar symptoms, it's probably better to open a new issue

**Comment by calebcartwright** [comment] 2022-03-03 15:11
Reopening as the upstream issue has recurred

**Comment by librity** [comment] 2022-05-01 02:57
I'm having the same problem. Examples:
- https://github.com/librity/ft_pipex
- https://github.com/librity/ft_libft
- https://github.com/librity/ft_get_next_line
- https://github.com/librity/ft_fractol

**Comment by igorskyflyer** [comment] 2022-05-01 16:28
+1, everything was working fine until like 2-3 days ago 👀

**Comment by calebcartwright** [comment] 2022-05-01 16:35
Folks, please refrain from posting the "me too" types of comments as they just add unhelpful noise. The above thread already contains relevant information explaining that the issue upstream.

Shields.io is not a system of record. It doesn't provide CI/pipeline capabilities, and it doesn't count lines of code either. We have to get the data from the relevant upstream endpoint, and we then display whatever data the upstream system of record provides. The upstream system in this case is Tokei, and they've been having this recurring issue for quite some time, as indicated above in the linked tokei issues. Tokei is the service responsible for counting lines of code, and for whatever reason it intermittently claims the count is 0, and thus 0 is displayed on the badges.

There's absolutely nothing we can do about this, so I'd encourage you to subscribe to those issues in the tokei repository if you're interested in receiving updates.

**Comment by librity** [comment] 2022-05-01 18:24
> Folks, please refrain from posting the "me too" types of comments as they just add unhelpful noise. The above thread already contains relevant information explaining that the issue is upstream.
> 
> Shields.io is not a system of record. It doesn't provide CI/pipeline capabilities, and it doesn't count lines of code either. We have to get the data from the relevant upstream endpoint, and we then display whatever data the upstream system of record provides. The upstream system in this case is Tokei, and they've been having this recurring issue for quite some time, as indicated above in the linked tokei issues. Tokei is the service responsible for counting lines of code, and for whatever reason it intermittently claims the count is 0, and thus 0 is displayed on the badges.
> 
> There's absolutely nothing we can do about this, so I'd encourage you to subscribe to those issues in the tokei repository if you're interested in receiving updates.

I will, thanks.

**Comment by Hongbo-Miao** [comment] 2023-01-15 08:57
Maybe a new shields badge using this service https://github.com/boyter/scc might help 😃

**Comment by AleixMT** [comment] 2023-07-27 14:48
Hello. I wanted to say that I have a similar issue with the lines of code badge too. The badge always say "Invalid response data". I tried with many repositories and I also tried giving shields.io more permissions, but the message is still shown. 

Here is the badge that I want to show:
[![Lines of code][loc-shield]][loc-url]

[loc-shield]: https://img.shields.io/tokei/lines/github/AleixMT/eChempad
[loc-url]: https://github.com/AleixMT/eChempad

The shield has the following URL: `https://img.shields.io/tokei/lines/github/AleixMT/eChempad`

Thank you for your response and for this wonderful project.

**Comment by chris48s** [comment] 2023-07-28 19:03
I think this is a duplicate of https://github.com/badges/shields/issues/9389 and the upstream issue is https://github.com/XAMPPRocky/tokei_rs/issues/233

**Comment by dishb** [comment] 2023-07-29 00:33
> I think this is a duplicate of #9389 and the upstream issue is [XAMPPRocky/tokei_rs#233](https://github.com/XAMPPRocky/tokei_rs/issues/233)

#9389 was created much later?

**Comment by chris48s** [comment] 2023-07-29 10:00
OK well https://github.com/badges/shields/issues/9389 is a duplicate of this.

The main point was I wanted to link to the upstream issue with tokei as this issue was bumped recently.

**Comment by Jonius7** [comment] 2024-06-07 14:38
Lines of code works if you don't use tokei and use `ghloc.vercel.app`, here's an example of mine:

`https://img.shields.io/endpoint?url=https://ghloc.vercel.app/api/Jonius7/SteamUI-OldGlory/badge?filter=.py$,.scss$,.rs$?style=flat&logoColor=white&label=Lines%20of%20Code`

**Comment by AleixMT** [comment] 2024-06-09 12:23
@Jonius7 Finally a valid solution!

**Closed** 2024-07-13 13:04 UTC
Labels: needs-upstream-help
