### ISSUE TITLE
pypi total downloads badge?

### ISSUE THREAD

**Issue by csinva** [badges/shields#6097] opened 2021-01-22 20:08 UTC
:clipboard: **Description**

This would be just like the current pypi downloads badge, but instead of showing downloads / mo, would show total downloads.

:link: **Data**

Same as original pypi downloads badge.

:microphone: **Motivation**

Would help track total downloads of a project.

**Comment by chris48s** [comment] 2021-01-23 19:17
Duplicate of https://github.com/badges/shields/issues/4319

**Closed by chris48s** 2021-01-23 19:17 UTC
Labels: service-badge
