### ISSUE TITLE
GitLab tag (latest by date)

### ISSUE THREAD

**Issue by guillermin** [badges/shields#6388] opened 2021-04-16 03:04 UTC
:clipboard: **Description**

Exactly the same as the already existing "GitHub tag (latest by date)" badge, but for a GitLab.com repository.
e.g. "tag | v1.3.0"

:link: **Data**

The data can be obtained from the public GitLab API (no key required). The call would be as follows:
`https://gitlab.com/api/v4/projects/{user}%2F{repo}/repository/tags`
(where `{user}` and `{repo}` should be replaced by their respective values)

The response is a JSON array that is by default sorted with the latest tag on top, so the value could be extracted as:
`result[0].name`

The documentation for the call can be found [here](https://docs.gitlab.com/ee/api/tags.html#list-project-repository-tags).

:microphone: **Motivation**

It can be used anywhere people are already using the equivalent GitHub badge, but for GitLab repositories. The main use case is to display the latest version of the app according to the repository.
In my case I want it alongside the F-Droid version badge so that it is clear whether the version that is published to F-Droid is the latest or not.

**Comment by calebcartwright** [comment] 2021-04-16 03:09
Thanks for reaching out but going to close as a duplicate of #4867

**Closed by calebcartwright** 2021-04-16 03:09 UTC
Labels: service-badge
