### ISSUE TITLE
[Self-Hosted] Allow endpoint to use "http" protocol

### ISSUE THREAD

**Issue by jorioux** [badges/shields#8622] opened 2022-11-11 18:11 UTC
:clipboard: **Description**

I'm running shields.io **self-hosted** on kubernetes.

I have a second service that returns JSON to generate custom badges in this format:

```json
{
  "schemaVersion": 1,
  "label": "hello",
  "message": "sweet world",
  "color": "orange"
}
```

Right now, my badges URL looks like this:

https://shields.domain.com/endpoint?url=https://custombadges.domain.com/service1/health

Since shields and my custom badges service are running on Kubernetes, **Shields should be able to call an endpoint on the same namespace (using Kubernetes internal DNS) in http like this:**

https://shields.domain.com/endpoint?url=http://custombadges/service1/health

**Proposition**

Could you add the option to not force the https protocol when calling an endpoint?

**Comment by calebcartwright** [comment] 2022-11-27 19:17
Thanks but going to close as a duplicate of #2891 to avoid bifurcation

**Closed by calebcartwright** 2022-11-27 19:17 UTC
Labels: self-hosting
