### ISSUE TITLE
Badges are not updated for codecov

### ISSUE THREAD

**Issue by damianszczepanik** [badges/shields#703] opened 2016-05-02 21:07 UTC
https://img.shields.io/codecov/c/github/damianszczepanik/cucumber-reporting/master.svg says 60%
while https://codecov.io/gh/damianszczepanik/cucumber-reporting and https://codecov.io/gh/damianszczepanik/cucumber-reporting/branch/master/graph/badge.svg 70%

**Comment by paulmelnikow** [comment] 2017-04-18 03:12
Shields caches the responses for 15 minutes. Could that be the problem?

**Comment by paulmelnikow** [comment] 2017-10-02 18:51
If the problem persists, please ping this issue or reopen.

**Comment by erayerdin** [comment] 2018-11-06 07:10
I know it's been a long time, but seems like I have a similar issue. In [this repo](https://github.com/erayerdin/pyairmore), whenever `development` branch's coverage changes, its badge changes as well.

However, `master` coverage, whatever I do, does not change. It is stuck on 86%. It has been, maybe one or two weeks since it didn't change, but `master` branch changed a lot.

**Comment by ronihcohen** [comment] 2018-11-06 15:33
I happens also [here](https://github.com/ronihcohen/fin-app-ng), stuck on 66%. 😭

**Comment by paulmelnikow** [comment] 2018-11-06 15:37
AFAIK nothing was ever done to address this. Sounds like this must be caused by something strange with their API?

**Comment by calebcartwright** [comment] 2019-03-11 01:01
Can anyone confirm whether they are still seeing this issue? 

We recently [refactored our Codecov service implementation](https://github.com/badges/shields/pull/3074) and switched to using their API as part of that process.

If these issues have been resolved then I'd like to close this one.

**Comment by erayerdin** [comment] 2019-03-11 09:30
The issue has been resolved for me.

**Comment by calebcartwright** [comment] 2019-03-11 15:51
Thanks @erayerdin, going to close this in that case

**Closed by calebcartwright** 2019-03-11 15:51 UTC
Labels: bug, service-badge

**Comment by wehs7661** [comment] 2020-08-26 08:44
Hi Codecov developers, I think I've been having the same issue as @erayerdin. My badge of Codecov in the master branch hasn't been updated for a while even if my code coverage actually changed. I'm not entirely sure if I should do anything according to [the refactored implementation of Codecov](https://github.com/badges/shields/pull/3074). Could you confirm if this is a solvable problem? Sorry if this is a naive question. Thanks!

**Comment by paulmelnikow** [comment] 2020-08-26 21:29
Hi! Could you open a new issue, please?
