### ISSUE TITLE
Github "Used by"

### ISSUE THREAD

**Issue by smarie** [badges/shields#3566] opened 2019-06-14 11:10 UTC
Github recently added a "Used by" badge on each repo where the number is more than 0.

![image](https://user-images.githubusercontent.com/3236794/59505407-9a3dcc00-8ea5-11e9-8540-10876bde54ed.png)

If I'm not mistaken there is not yet a corresponding badge in shields. I guess that the mechanism would be closely related to the "github stars" or "github issues" badges.

**Comment by chris48s** [comment] 2019-06-14 11:56
"used by" shows a subset of the GH dependency graph ( https://github.com/badges/shields/network/dependents ) , so this is a duplicate of https://github.com/badges/shields/issues/1550 Lets track it there

the `/librariesio/dependent-repos` or `/librariesio/dependents` badges might be worth a look (although note from the discussion in #1550 that they won't necessarily show the _exact_ same number for various reasons)

**Closed by chris48s** 2019-06-14 11:56 UTC
