### ISSUE TITLE
Unparseable JSON response in Twitter badge

### ISSUE THREAD

**Issue by franzihei** [badges/shields#8846] opened 2023-01-26 14:27 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

There seems to be an issue with getting follower stats from Twitter. This issue is not limited to only our badge but also appears on shields.io. I assume it's an issue with fetching data from Twitter and hence affects all Twitter badges.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/41991517/214860772-a51fc36c-c11c-48cc-aa13-f7de665e6807.png">

### 🔗 Link to the badge

https://img.shields.io/twitter/follow/solidity_lang?style=plastic&logo=twitter

**Comment by calebcartwright** [comment] 2023-01-26 14:47
Closing as a duplicate of #8837 

The issue is still being experienced because we've not yet been able to get a deployment through with the change

**Closed by calebcartwright** 2023-01-26 14:47 UTC
Labels: question
