### ISSUE TITLE
https://shields.io/ resource unavailable

### ISSUE THREAD

**Issue by andreynav** [badges/shields#8884] opened 2023-02-03 13:27 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

[525 error](https://take.ms/0vcog)

**Comment by jozefizso** [comment] 2023-02-03 21:41
Cloudflare Ray ID: 793e54c50b8d9235

**Comment by Jonathan357611** [comment] 2023-02-04 15:36
Same for me :/
Ray ID: 79447b780f8f929b

**Comment by calebcartwright** [comment] 2023-02-04 15:53
Duplicate of #8424

**Closed by calebcartwright** 2023-02-04 15:53 UTC
Labels: question

**Comment by andreynav** [comment] 2023-02-04 18:20
@calebcartwright I son't see the fix of the bug

**Comment by calebcartwright** [comment] 2023-02-04 20:03
I'm not really sure what the objective is in the downvote and subsequent comment, but the status/resolution of an issue is quite orthogonal to whether an issue is a duplicate of an existing one.

#8424 is the older, existing issue with more details around cause and discussion about potential resolution. That's where we intend to track the item that you've reported here in a separate, duplicative issue. There's no benefits in bifurcating that discussion and maintaining multiple duplicate issues, which is why this one has been closed and directed towards the main issue.
