### ISSUE TITLE
Add GitHub badge to GitLab

### ISSUE THREAD

**Issue by AkibAzmain** [badges/shields#5997] opened 2020-12-30 18:19 UTC
:clipboard: **Description**

Please add Github badge GitLab. There are many useful dynamic badges for GitHub, but I found none (maybe there are a very few) for GitLab.

:link: **Data**

GitLab has a public API ([documentation](https://docs.gitlab.com/ee/api/)), so it shouldn't be hard to do that.

**Comment by calebcartwright** [comment] 2020-12-30 18:26
Closing as duplicate of #541 

One of the best ways to review the badges Shields currently provides is by going to [Shields.io](https://shields.io) and utilizing the search box at the top of the page, for example with `gitlab` as the search term you can see our current Gitlab badges:

![image](https://user-images.githubusercontent.com/13042488/103373285-215b9080-4a9a-11eb-8b00-3336bdf9575b.png)

**Closed by calebcartwright** 2020-12-30 18:26 UTC
