### ISSUE TITLE
Microsoft Edge Addon downloads like Chrome webstore

### ISSUE THREAD

**Issue by max-programming** [badges/shields#5546] opened 2020-09-15 14:10 UTC
:clipboard: **Description**
I noticed that there are badges to see the amount of viewers of an extension for Chrome webstore and Firefox. And the [new Microsoft Edge](https://www.microsoft.com/en-us/edge) has it's own [Addons store](https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home?hl=en-US) too. So I wanted to have this badge also. 

:link: **Data**
A badge that shows how many users are using an extension on MS Edge Addons
![image](https://user-images.githubusercontent.com/51731966/93221256-287cbe00-f78b-11ea-9040-b3df1b793984.png)
Like this 👆

:microphone: **Motivation**
I think there is no public API for this thing.

**Comment by calebcartwright** [comment] 2020-09-15 14:48
Duplicate of #4690

**Closed by calebcartwright** 2020-09-15 14:48 UTC
Labels: service-badge
