### ISSUE TITLE
Chrome extension ratings badge shows NaN

### ISSUE THREAD

**Issue by gurrrung** [badges/shields#5498] opened 2020-09-07 05:31 UTC
:beetle: **Description**

My Chrome extension should show a rating of 5/5 but it shows NaN/5.

![Screenshot from 2020-09-07 11-00-50](https://user-images.githubusercontent.com/30543444/92351463-6d548500-f0f9-11ea-8a47-0bda06f4782f.png)

:link: **Link to the badge**

Check out the readme of https://github.com/gurrrung/coursera-HD-video-downloader

:bulb: **Possible Solution**

Rating should be shown

**Comment by calebcartwright** [comment] 2020-09-07 14:26
Duplicate of #5475

**Closed by calebcartwright** 2020-09-07 14:26 UTC
Labels: question
