### ISSUE TITLE
New badge: Patreons

### ISSUE THREAD

**Issue by pmtarantino** [badges/shields#6012] opened 2021-01-02 16:00 UTC
:clipboard: **A new badge to show how many Patreons are supporting a project.**

![Patreons](https://img.shields.io/static/v1?label=Patreons&message=151&color=orange)

:link: **Data**

Patreons offers an API to get the number of Patreon from a creator: 
https://docs.patreon.com/#fetch-a-creator-profile-and-campaign-info

:microphone: **Motivation**

It would be another way to show the support a project is receiving on Patreon, one of the most popular platforms to support creators. It could be used not only on Github, but any website that has a Patreon fanbase.

**Comment by calebcartwright** [comment] 2021-01-02 17:34
Closing as duplicate of #3585

**Closed by calebcartwright** 2021-01-02 17:34 UTC
Labels: service-badge
