### ISSUE TITLE
Wercker badges dont work

### ISSUE THREAD

**Issue by mbrevda** [badges/shields#825] opened 2016-10-31 15:55 UTC
Seems to be using the wrong api

**Comment by PyvesB** [comment] 2018-08-13 22:06
@mbrevda @iacchus I know it has been a while, but I have been looking into this and I am not able to reproduce the aforementioned issue. Could you provide us with any more information?

Our code is using the endpoint described in the [documentation](https://devcenter.wercker.com/development/api/endpoints/applications/#list-builds), and even though the badges on the homepage need updating, I can generate fresh badges using public applications that are currently registered in Wercker. For instance:
https://img.shields.io/wercker/ci/wercker/go-wercker-api.svg
![](https://img.shields.io/wercker/ci/wercker/go-wercker-api.svg)

**Comment by mbrevda** [comment] 2018-08-14 08:54
I don't remember the issues I was having, but  _think_ it was either with private repos or with branches other than master?

**Comment by PyvesB** [comment] 2018-08-17 19:19
I have done some work in #1920 to add branch support, to modernise/improve maintainability of our implementation, to clarify badge error messages and to fix the examples showing on the front page. You can benefit from these enhancements right now as this has already been deployed to our production servers.

As far as private applications are concerned, this is not yet supported as this point, but we have issue #604 to track progress on this. Therefore closing this issue.

Thank you for your patience! 😉

**Closed by PyvesB** 2018-08-17 19:19 UTC
Labels: bug, service-badge
