### ISSUE TITLE
Bug: Duplicate Menu Items

### ISSUE THREAD

**Issue by Sanchitbajaj02** [badges/shields#9766] opened 2023-11-29 07:31 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

While scrolling through the https://shields.io/ I found that some menu items are coming twice. Their URLs are like:

- https://shields.io/badges/git-hub-issues
- https://shields.io/badges/git-hub-issues-1

![image](https://github.com/badges/shields/assets/55249639/e995a7fa-f43d-4db3-86f8-97eab40ee786)

## Possible Problem
I think someone has made the duplicate or the page is rendering twice.

**Comment by chris48s** [comment] 2023-11-29 19:34
Hi.

I am going to close this as a duplicate of https://github.com/badges/shields/issues/9393

If you have a look at all these, you'll notice that these are not actually duplicate pages. They are actually slightly different variants of the same badge. They just have the same title in the menu, which I know is unhelpful.

We're aware of the issue. Basically, in order to launch the new frontend, we auto-converted all the old content as a first step, rather than manually reviewing it. I am gradually working through the process of reviewing every single documentation page. One of the things I am doing as part of that process is making sure every page on the site has a globally unique title. You can see the (long) list of PRs in https://github.com/badges/shields/issues/9285#ref-pullrequest-1774983388

I've made a lot of progress, but also there is a lot more to do. I'll reach these eventually.

**Closed** 2023-11-29 19:35 UTC
Labels: question
