### ISSUE TITLE
Wrong (expired?) TLS Certificate on https://shields.io

### ISSUE THREAD

**Issue by matteocorti** [badges/shields#8888] opened 2023-02-06 09:43 UTC
### Are you experiencing an issue with...

shields.io

### 🐞 Description

CloudFlare is giving "SSL handshake failed"

### 💡 Possible Solution

Update/check your TLS certifcates for shields.io (img.shields.io is OK)

**Comment by calebcartwright** [comment] 2023-02-06 19:06
Closing as a duplicate of https://github.com/badges/shields/issues/8424

**Closed by calebcartwright** 2023-02-06 19:06 UTC
Labels: question
